Repository chaos-polymtl/lethe, pull requests merged in 2021-07, with the labels that each got.

#196 Add module to calculate forces and torques applied over the boundary by the particles
  applications_tests/dem_2d/rotating_in_circle.prm
  applications_tests/dem_3d/force_boundary_box.output
  applications_tests/dem_3d/force_boundary_box.prm
  applications_tests/dem_3d/rotating_in_ball.prm
  applications_tests/dem_3d/torque_boundary_box.output
  applications_tests/dem_3d/torque_boundary_box.prm
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/dem_solver_parameters.h
  include/dem/output_force_torque_calculation.h
  include/dem/pw_contact_force.h
  include/dem/pw_linear_force.h
  include/dem/pw_nonlinear_force.h
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/find_boundary_cells_information.cc
  source/dem/output_force_torque_calculation.cc
  source/dem/pw_contact_force.cc
  source/dem/pw_linear_force.cc
  source/dem/pw_nonlinear_force.cc
Labels: ready_review

#204 Dem triangulation motion
  applications_tests/dem_3d/box_grid_rotation.output
  applications_tests/dem_3d/box_grid_rotation.prm
  applications_tests/dem_3d/box_grid_slide.output
  applications_tests/dem_3d/box_grid_slide.prm
  include/core/parameters_lagrangian.h
  include/dem/boundary_cells_info_struct.h
  include/dem/dem.h
  include/dem/dem_solver_parameters.h
  include/dem/find_boundary_cells_information.h
  include/dem/grid_motion.h
  include/dem/localize_contacts.h
  include/dem/pw_broad_search.h
  include/dem/pw_contact_info_struct.h
  include/dem/pw_fine_search.h
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/find_boundary_cells_information.cc
  source/dem/grid_motion.cc
  source/dem/input_parameter_inspection.cc
  source/dem/localize_contacts.cc
  source/dem/pw_broad_search.cc
  source/dem/pw_fine_search.cc
  tests/dem/boundary_cells_and_faces.cc
  tests/dem/normal_force.cc
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
  tests/dem/particle_wall_contact_pairs.cc
  tests/dem/particle_wall_fine_search.cc
  tests/dem/post_collision_velocity.cc
Labels: enhancement

#214 Add vector resizing after load-balancing
  source/dem/dem.cc
Labels: bug

#220 Add checkpoint_step to reinitialize vector containers
  source/dem/dem.cc
Labels: bug
