Repository chaos-polymtl/lethe, pull requests merged in 2022-07, with the labels that each got.

#497 Decompose force in pressure and viscous
  applications_tests/gd_navier_stokes_2d/cylinder_carreau_gd.output
  applications_tests/gls_navier_stokes_2d/cylinder_gls.output
  applications_tests/gls_nitsche_navier_stokes_22/noslip_22.output
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_22.output
  applications_tests/gls_nitsche_navier_stokes_23/couette_23.output
  applications_tests/gls_nitsche_navier_stokes_33/noslip33_simplex.mpirun=2.output
  applications_tests/gls_nitsche_navier_stokes_33/noslip_33.output
  applications_tests/gls_sharp_navier_stokes_2d/flow_around_multiple_objects.output
  applications_tests/gls_sharp_navier_stokes_2d/moving_ib_gls.output
  applications_tests/gls_sharp_navier_stokes_2d/moving_ib_gls_poisson.output
  applications_tests/gls_sharp_navier_stokes_2d/taylorcouette2d_carreau_gls.output
  applications_tests/gls_sharp_navier_stokes_3d/check_point.ib_particles
  applications_tests/gls_sharp_navier_stokes_3d/check_point.output
  applications_tests/gls_sharp_navier_stokes_3d/coupled_moving_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cone_deathstar.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cuthollowsphere.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_ellipsoid_rectangle.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_torus.output
  applications_tests/gls_sharp_navier_stokes_3d/ib_force.00.dat
  applications_tests/gls_sharp_navier_stokes_3d/moving_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/static_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/static_stokes.prm
  applications_tests/gls_sharp_navier_stokes_3d/steady_couette_sphere.output
  applications_tests/gls_sharp_navier_stokes_3d/steady_couette_sphere_poisson.output
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/sphere-carreau-with-sharp-interface.rst
  include/core/ib_particle.h
  include/core/utilities.h
  include/solvers/navier_stokes_base.h
  include/solvers/postprocessing_cfd.h
  source/core/utilities.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_cfd.cc
Labels: Reviewed and ready to merge

#517 Citation hyperlink
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/silo/silo.rst
  doc/source/examples/incompressible-flow/2d-backward-facing-step/2d-backward-facing-step.rst
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/2d-transient-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/nitsche_mixer_with_pbt_impeller.rst
  doc/source/examples/multiphysics/dam-break-VOF/dam-break-VOF.rst
  doc/source/examples/multiphysics/laser-meltpool/laser-meltpool.rst
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  doc/source/examples/multiphysics/rising-bubble-VOF/rising-bubble-VOF.rst
  doc/source/examples/multiphysics/stefan_problem/stefan_problem.rst
  doc/source/examples/resolved_cfd-dem/sedimentation-1-particle/sedimentation-1-particle.rst
  doc/source/parameters/cfd/laser_heat_source.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/resolved_cfd-dem/resolved_cfd-dem.rst
  doc/source/parameters/unresolved_cfd-dem/cfd_dem.rst
  doc/source/theory/theory.rst
Labels: documentation, Reviewed and ready to merge, Lethe Hackathon, rebased

#515 Stabilization theory guide
  doc/source/theory/fluid_dynamics/fem_formulation.rst
  doc/source/theory/fluid_dynamics/fluid_dynamics.rst
  doc/source/theory/fluid_dynamics/linear_solvers.rst
  doc/source/theory/fluid_dynamics/navier-stokes.rst
  doc/source/theory/fluid_dynamics/stabilization.rst
Labels: Lethe Hackathon, Ready for review, needs_one_more_review

#518 Output BC at first iteration only
  source/solvers/navier_stokes_base.cc
Labels: Reviewed and ready to merge, quick fix, Lethe Hackathon

#516 Fix tests vof pw
  applications_tests/gls_navier_stokes_2d/gls_free-surface_peeling.output
  applications_tests/gls_navier_stokes_2d/gls_free-surface_peeling.prm
  applications_tests/gls_navier_stokes_2d/gls_free-surface_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_free-surface_wetting-inverted.prm
  source/core/parameters.cc
  source/solvers/vof.cc
Labels: bug, Reviewed and ready to merge, Lethe Hackathon

#521 Refactor simple impeller example
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/images/PBT_tank_3D.svg
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/images/scheme_tank.png
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/images/scheme_tank.svg
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/nitsche_mixer_with_pbt_impeller.rst
  doc/source/parameters/cfd/nitsche.rst
  examples/incompressible_flow/3d_nitsche_mixer_with_pbt_impeller/mixer.prm
Labels: documentation, Reviewed and ready to merge, Lethe Hackathon

#523 Gmsh doc
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/2d-transient-around-ahmed-body.rst
  doc/source/index.rst
  doc/source/parameters/cfd/linear_solver_control.rst
  doc/source/tools/gmsh/gmsh.rst
  doc/source/tools/gmsh/images/attractor.png
  doc/source/tools/gmsh/images/geo.png
  doc/source/tools/gmsh/images/unstructured.png
  doc/source/tools/tools.rst
Labels: documentation, Reviewed and ready to merge, Lethe Hackathon

#519 Small rotating drum example
  doc/source/examples/dem/3d-small-scale-rotating-drum/3d-small-scale-rotating-drum.rst
  doc/source/examples/dem/dem.rst
  doc/source/examples/unresolved_cfd-dem/unresolved_cfd-dem.rst
  examples/dem/3d_small_scale_rotating_drum/packing_rotating_drum.prm
  examples/dem/3d_small_scale_rotating_drum/small_rotating_drum_dem.prm
Labels: Beginner's work, Reviewed and ready to merge, Lethe Hackathon, rebased

#527 Vof ht fix dissipation
  applications_tests/gls_navier_stokes_2d/gls_vof_heat-transfer_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_heat-transfer_hydrostat.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.output
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.prm
  doc/source/parameters/cfd/multiphysics.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  include/core/parameters_multiphysics.h
  include/solvers/heat_transfer_assemblers.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/vof.h
  source/core/parameters_multiphysics.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/heat_transfer_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
Labels: enhancement, Reviewed and ready to merge, rebased

#535 Implement time varying source term + Update doc
  doc/source/parameters/cfd/source_term.rst
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
Labels: documentation, quick fix, ready for review

#536 Saffman Lift + Re_p and relative_velocity in scratch_data
  applications_tests/cfd_dem_coupling_3d/dynamic_contact_search.output
  applications_tests/cfd_dem_coupling_3d/liquid_fluidized_bed.output
  applications_tests/cfd_dem_coupling_3d/particle_sedimentation.output
  applications_tests/cfd_dem_coupling_3d/restart_particle_sedimentation.output
  applications_tests/gls_vans_3d/pcm_packed_bed.output
  applications_tests/gls_vans_3d/spm_packed_bed.output
  doc/source/parameters/unresolved_cfd-dem/cfd_dem.rst
  include/fem-dem/parameters_cfd_dem.h
  include/fem-dem/vans_assemblers.h
  include/solvers/navier_stokes_scratch_data.h
  source/fem-dem/gls_vans.cc
  source/fem-dem/parameters_cfd_dem.cc
  source/fem-dem/vans_assemblers.cc
  source/solvers/navier_stokes_scratch_data.cc
Labels: enhancement, reviewed and ready to merge, rebased

#538 Sharp nonspheres movement tests
  applications_tests/gls_sharp_navier_stokes_2d/moving_rectangle.output
  applications_tests/gls_sharp_navier_stokes_2d/moving_rectangle.prm
  applications_tests/gls_sharp_navier_stokes_3d/spinning_cone.output
  applications_tests/gls_sharp_navier_stokes_3d/spinning_cone.prm
  source/core/parameters.cc
Labels: reviewed and ready to merge, rebased
