Repository chaos-polymtl/lethe, pull requests merged in 2022-01, with the labels that each got.

#343 Move DEM examples to documentation
  doc/source/examples/dem/dem.rst
  doc/source/examples/dem/packing-in-ball/images/packing_in_ball.jpeg
  doc/source/examples/dem/packing-in-ball/packing-in-ball.rst
  doc/source/examples/dem/packing-in-circle/images/packing_in_circle.png
  doc/source/examples/dem/packing-in-circle/packing-in-circle.rst
  doc/source/examples/dem/rotating-drum-with-post-processing/rotating-drum-with-post-processing.rst
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/rotation-of-box/rotation-of-box.rst
  doc/source/examples/dem/silo/silo.rst
  examples/dem/2d_packing_in_circle/packing_in_circle.prm
  examples/dem/3d_packing_in_ball/packing_in_ball.prm
  examples/dem/3d_rotating_drum/rotating_drum.prm
Labels: documentation

#346 Migrate taylor couette example
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/images/flow_patterns.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/images/geometry.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/images/lethe_analytical_taylor_couette_comparison.png
  examples/incompressible_flow/2d_lid_driven_cavity/post_process_Reynolds_400.py
  examples/incompressible_flow/2d_taylor-couette/post_process_taylor_couette.py
  examples/incompressible_flow/2d_taylor-couette/taylor-couette.prm
Labels: documentation

#348 Add the examples explicitly to ensure order
  doc/source/examples/dem/dem.rst
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/examples/multiphysics/multiphysics.rst
Labels: documentation

#349 Nitsche table restart
  include/core/nitsche.h
  source/solvers/gls_nitsche_navier_stokes.cc
Labels: bug

#354 Add Mesh Adaptation Control page and expand it
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/mesh_adaptation_control.rst
Labels: documentation

#355 Migrated the restart documentation
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/restart.rst
Labels: documentation, Reviewed and ready to merge

#358 Remove read me from all examples folders
  examples/README.md
  examples/cfd-dem/cylindrical_packed_bed/README
  examples/cfd-dem/square_fluidized_bed/README
  examples/dem/2d_packing_in_circle/README
  examples/dem/3d_grid_rotation_in_box/README
  examples/dem/3d_packing_in_ball/README
  examples/dem/3d_rotating_drum/README
  examples/dem/3d_rotating_drum_with_post_processing/README
  examples/dem/3d_silo/README
  examples/incompressible_flow/2d_flow_around_cylinder/README
  examples/incompressible_flow/2d_taylor-couette/README
  examples/incompressible_flow/3d_flow_around_sphere/README
  examples/incompressible_flow/3d_periodic_hills/README
  examples/incompressible_flow/3d_ribbon_mixer/README
  examples/incompressible_flow/3d_ribbon_mixer_cad_aware/README
  examples/incompressible_flow/3d_vessels/README
  examples/multiphysics/dam_break_VOF/README
  examples/multiphysics/warming_up_viscous_fluid/README
  examples/rpt/parameters_tuning/README
  examples/rpt/particle_cell_reconstruction/README
Labels: documentation, Reviewed and ready to merge

#356 Migrate parameter file + expand explanations
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/non-linear_solver_control.rst
Labels: documentation, Reviewed and ready to merge

#359 Multiphysics boundary conditions migration for HT and Tracer
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  doc/source/parameters/cfd/cfd.rst
Labels: documentation, Reviewed and ready to merge

#352 Creation of the nitsche taylor-couette example
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/background_mesh_taylor-couette.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/taylor_couette.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/taylor_couette_with_nitsche_mesh.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/taylor_couette_with_nitsche_velocity_adapt.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/examples/incompressible-flow/incompressible-flow.rst
Labels: documentation, Reviewed and ready to merge

#360 Documentation for dynamic flow control
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/dynamic_flow_control.rst
Labels: documentation, Reviewed and ready to merge

#366 Nitsche parameters fix
  doc/source/parameters/cfd/nitsche.rst
Labels: Beginner's work, documentation, Reviewed and ready to merge, quick fix

#368 Fix warnings when compiling documentation
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  doc/source/parameters/cfd/non-linear_solver_control.rst
Labels: documentation, quick fix

#367 Migrate and extend the periodic hills example
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/average_velocity.png
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/boundary_conditions.png
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/geometry_description.jpg
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/mesh.png
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/reynolds_normal_stress.png
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/images/reynolds_shear_stress.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/parameters/cfd/mesh.rst
  examples/incompressible_flow/3d_periodic_hills/periodic_hills.prm
Labels: documentation, Reviewed and ready to merge

#353 Cfd dem examples
  doc/source/examples/cfd-dem/cfd-dem.rst
  doc/source/examples/cfd-dem/cylindrical-packed-bed/cylindrical-packed-bed.rst
  doc/source/examples/cfd-dem/cylindrical-packed-bed/images/packed_bed.png
  doc/source/examples/cfd-dem/cylindrical-packed-bed/images/packed_bed_p.png
  doc/source/examples/cfd-dem/cylindrical-packed-bed/images/packed_bed_vel.png
Labels: documentation

#365 Migrate tracer simplex example
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/examples/multiphysics/tracer-through-cad-junction/images/paraview_tracer.png
  doc/source/examples/multiphysics/tracer-through-cad-junction/images/salome_geometry.png
  doc/source/examples/multiphysics/tracer-through-cad-junction/images/salome_menu.png
  doc/source/examples/multiphysics/tracer-through-cad-junction/images/salome_mesh_creation.png
  doc/source/examples/multiphysics/tracer-through-cad-junction/tracer-through-cad-junction.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  examples/multiphysics/tracer_through_cad_junction/Mesh_1.mesh
  examples/multiphysics/tracer_through_cad_junction/output/dummy
  examples/multiphysics/tracer_through_cad_junction/tracer_through_cad_junction.geo
  examples/multiphysics/tracer_through_cad_junction/tracer_through_cad_junction.hdf
  examples/multiphysics/tracer_through_cad_junction/tracer_through_cad_junction.msh
  examples/multiphysics/tracer_through_cad_junction/tracer_through_cad_junction.prm
Labels: documentation, Reviewed and ready to merge

#351 Migration of the 2D Flow around cylinder and 2D Flow around Ahmed bod…
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/final_mesh.png
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/geometry_bc.png
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/geometry_description.png
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/initial_mesh.png
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/pressure.png
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/images/velocity.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/2d-transient-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re288_speed_t05.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re288_speed_t4.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re28_speed_t05.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re28_speed_t4.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re720_mesh_t0.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re720_mesh_t005.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re720_mesh_t4.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re720_speed_t05.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/Re720_speed_t4.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/ahmed_bc.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/ahmed_geometry.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/ahmed_mesh.png
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/video_1_ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/video_2_ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-around-ahmed-body/images/video_3_ahmed.jfif
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible_flow/2d_ahmed_body/ahmed.prm
  examples/incompressible_flow/2d_flow_around_cylinder/cylinder_structured.geo
Labels: documentation, Reviewed and ready to merge

#369 Migrate flow around sphere example
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/adapt_with_mesh.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/adapt_without_mesh.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/example_4_setup.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/pressure_0.1.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/pressure_150.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_0.1.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_150.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_mesh_150.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible_flow/3d_flow_around_sphere/sphere_adapt.prm
Labels: documentation

#350 Migrate vof example
  doc/source/examples/multiphysics/dam-break-VOF/dam-break-VOF.rst
  doc/source/examples/multiphysics/dam-break-VOF/images/VOF_dam_break_configuration.png
  doc/source/examples/multiphysics/dam-break-VOF/images/refinement.png
  doc/source/examples/multiphysics/dam-break-VOF/images/time-series.png
  doc/source/examples/multiphysics/dam-break-VOF/images/xmax_t.png
  examples/multiphysics/dam_break_VOF/Dambreak_2d_lethe.py
  examples/multiphysics/dam_break_VOF/gls_VOF_dam-break_Martin_and_Moyce.prm
Labels: documentation, Reviewed and ready to merge

#362 Migrate linear solver control
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: documentation

#372 Very minor fix
  include/solvers/source_terms.h
Labels: maintenance, Reviewed and ready to merge, quick fix

#380 Fix bug for non-newtonian fluid
  applications_tests/gls_sharp_navier_stokes_2d/taylorcouette2d_carreau_gls.output
  source/solvers/gls_sharp_navier_stokes.cc
Labels: bug, quick fix

#374 Migrate interface sharpening documentation
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/interface_sharpening.rst
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: documentation, Reviewed and ready to merge

#382 Fix typo on Niagara cluster commands
  doc/source/installation/compute_canada.rst
Labels: documentation, quick fix

#378 Review Simulation Control and General pages
  doc/source/parameters/cfd/simulation_control.rst
  doc/source/parameters/parameters.rst
Labels: documentation
