Repository chaos-polymtl/lethe, pull requests merged in 2022-02, with the labels that each got.

#387 Nitsche fix calculate force
  applications_tests/gd_navier_stokes_2d/cylinder_carreau_gd.prm
  applications_tests/gd_navier_stokes_2d/taylorcouette_gd.prm
  applications_tests/gls_navier_stokes_2d/cylinder_gls.prm
  applications_tests/gls_navier_stokes_2d/rigid-body-rotation_gls.prm
  applications_tests/gls_navier_stokes_2d/taylorcouette_gls.prm
  applications_tests/gls_navier_stokes_3d/cylinder-rigid-body_gls.prm
  applications_tests/gls_nitsche_navier_stokes_22/noslip_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_two_solids_22.output
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_two_solids_22.prm
  applications_tests/gls_nitsche_navier_stokes_23/couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_23/taylor-couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_33/noslip33_simplex.prm
  applications_tests/gls_nitsche_navier_stokes_33/noslip_33.prm
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/parameters/cfd/force_and_torque.rst
  doc/source/parameters/cfd/nitsche.rst
  examples/incompressible_flow/2d_flow_around_cylinder/cylinder.prm
  examples/incompressible_flow/2d_nitsche_taylor-couette/adaptative_nitsche_taylor-couette.prm
  examples/incompressible_flow/2d_nitsche_taylor-couette/uniform_nitsche_taylor-couette.prm
  examples/incompressible_flow/2d_taylor-couette/taylor-couette.prm
  examples/incompressible_flow/3d_flow_around_sphere/sphere_0.1.prm
  examples/incompressible_flow/3d_flow_around_sphere/sphere_150.prm
  examples/incompressible_flow/3d_flow_around_sphere/sphere_adapt.prm
  examples/incompressible_flow/3d_ribbon_mixer/ribbon_gls.prm
  examples/incompressible_flow/3d_ribbon_mixer_cad_aware/ribbon_gls.prm
  include/core/nitsche.h
  include/solvers/gls_nitsche_navier_stokes.h
  source/core/parameters.cc
  source/solvers/gls_nitsche_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
Labels: enhancement

#389 Update images in Flow around sphere example
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/adapt_with_mesh.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/adapt_without_mesh.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/pressure_0.1.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/pressure_150.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_0.1.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_150.png
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/velocity_mesh_150.png
Labels: documentation, quick fix

#388 Migrate rheological models to Fluid class
  applications_tests/gd_navier_stokes_2d/apparent_viscosity_carreau_gd.prm
  applications_tests/gd_navier_stokes_2d/cylinder_carreau_gd.prm
  applications_tests/gd_navier_stokes_2d/mms2d_powerlaw_gd.prm
  applications_tests/gls_navier_stokes_2d/mms2d_carreau_1st-order_gls.prm
  applications_tests/gls_navier_stokes_2d/mms2d_carreau_2nd-order_gls.prm
  applications_tests/gls_sharp_navier_stokes_2d/taylorcouette2d_carreau_gls.prm
  doc/source/parameters/cfd/physical_properties.rst
  include/core/parameters.h
  source/core/parameters.cc
  source/core/rheological_model.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/gls_sharp_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
Labels: maintenance

#390 Add missing parameters in Multiphysics
  doc/source/parameters/cfd/interface_sharpening.rst
  doc/source/parameters/cfd/multiphysics.rst
Labels: documentation, Reviewed and ready to merge

#392 Fix vof conservation
  doc/source/parameters/cfd/multiphysics.rst
  include/core/parameters_multiphysics.h
  include/solvers/vof.h
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
Labels: quick fix

#395 Nitsche beta
  applications_tests/gls_nitsche_navier_stokes_22/impeller.prm
  applications_tests/gls_nitsche_navier_stokes_22/mixer_back_and_forth.prm
  applications_tests/gls_nitsche_navier_stokes_22/noslip_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_two_solids_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/taylor_couette_nitsche_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/two-bar-mixer-restart.prm
  applications_tests/gls_nitsche_navier_stokes_22/two-bar-mixer-start.prm
  applications_tests/gls_nitsche_navier_stokes_23/couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_23/taylor-couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_33/noslip33_simplex.prm
  applications_tests/gls_nitsche_navier_stokes_33/noslip_33.prm
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/taylor_couette.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/images/taylor_couette.svg
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/images/geometry.png
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/images/geometry.svg
  doc/source/parameters/cfd/nitsche.rst
  include/core/nitsche.h
  source/solvers/gls_nitsche_navier_stokes.cc
Labels: quick fix

#400 Clean VOF solver
  include/core/parameters_multiphysics.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof.h
  include/solvers/vof_assemblers.h
  include/solvers/vof_scratch_data.h
  source/core/parameters_multiphysics.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
  source/solvers/vof_scratch_data.cc
Labels: maintenance

#403 Add VOF auxiliary physics calculations
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/solvers/simulation_parameters.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
Labels: enhancement

#396 Vof peeling
  include/core/boundary_conditions.h
  include/core/parameters_multiphysics.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/navier_stokes_base.h
  include/solvers/simulation_parameters.h
  include/solvers/vof.h
  include/solvers/vof_scratch_data.h
  source/core/boundary_conditions.cc
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
  source/solvers/vof_scratch_data.cc
Labels: enhancement

#406 Fix a bug in the pfg and curvature assemblers
  source/solvers/vof.cc
Labels: bug
