Repository chaos-polymtl/lethe, pull requests merged in 2022-03, with the labels that each got.

#414 Fix ht vof
  applications_tests/gls_navier_stokes_2d/gls_free-surface_heat-transfer_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_free-surface_heat-transfer_hydrostat.prm
  include/core/multiphysics.h
  include/core/parameters.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/multiphysics_interface.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/vof.cc
  tests/solvers/multiphysics_interface_01.output
Labels: bug, quick fix

#411 Surface tension force
  applications_tests/gls_navier_stokes_2d/gls_static_bubble_surface_tension_force.output
  applications_tests/gls_navier_stokes_2d/gls_static_bubble_surface_tension_force.prm
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/solvers/multiphysics_interface.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/multiphysics_interface.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
Labels: enhancement

#420 Doc restart
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  doc/source/parameters/cfd/restart.rst
Labels: bug, documentation

#430 Add NonNewtonian assemblers to vof
  include/solvers/navier_stokes_vof_assemblers.h
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: enhancement, help wanted
