Repository chaos-polymtl/lethe, pull requests merged in 2022-10, with the labels that each got.

#603 Fix a bug in the definition of stabilization constant for VOF simulations
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting_mesh-adapt.output
  examples/multiphysics/dam-break/dam-break-Martin-and-Moyce.prm
  include/solvers/stabilization.h
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: reviewed and ready to merge

#592 Add rbf sharp
  applications_tests/gls_sharp_navier_stokes_3d/CMakeLists.txt
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_rbf.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_rbf.prm
  applications_tests/gls_sharp_navier_stokes_3d/rbf_test_shape.input
  doc/source/parameters/resolved-cfd-dem/resolved-cfd-dem.rst
  include/core/ib_particle.h
  include/core/parameters.h
  include/core/shape.h
  source/core/ib_particle.cc
  source/core/parameters.cc
  source/core/shape.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: reviewed and ready to merge

#604 Fix some issues with cfd-dem
  applications_tests/dem_3d/outlet_boundary.output
  applications_tests/dem_3d/outlet_boundary.prm
  include/dem/find_boundary_cells_information.h
  source/dem/find_boundary_cells_information.cc
  source/dem/find_cell_neighbors.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: reviewed and ready to merge

#609 Fix Saffman Lift 3d particle_number update
  source/fem-dem/vans_assemblers.cc
Labels: quick fix, ready for review

#606 Vof pre solve
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_heated-walls.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_heated-walls_multivar_adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_initial_refine.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.output
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting_mesh-adapt.output
  doc/source/parameters/cfd/multiphysics.rst
  include/fem-dem/gls_vans.h
  include/solvers/auxiliary_physics.h
  include/solvers/heat_transfer.h
  include/solvers/multiphysics_interface.h
  include/solvers/navier_stokes_base.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/gls_vans.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
  tests/solvers/restart_01.cc
Labels: reviewed and ready to merge

#612 Refactor the particle-particle broad search code in DEM
  include/dem/particle_particle_broad_search.h
  source/dem/dem.cc
  source/dem/find_cell_neighbors.cc
  source/dem/particle_particle_broad_search.cc
Labels: reviewed and ready to merge, refactor

#613 Refactor the localize contacts code in DEM
  include/dem/contact_type.h
  include/dem/data_containers.h
  include/dem/localize_contacts.h
  source/dem/CMakeLists.txt
  source/dem/localize_contacts.cc
Labels: reviewed and ready to merge, refactor

#616 Refactor the locate local particles code in DEM
  include/dem/contact_type.h
  include/dem/locate_local_particles.h
  include/dem/update_ghost_particle_particle_contact_container.h
  include/dem/update_local_particle_particle_contact_container.h
  include/dem/update_particle_container.h
  include/dem/update_particle_point_line_contact_container.h
  include/dem/update_particle_wall_contact_container.h
  source/dem/CMakeLists.txt
  source/dem/locate_local_particles.cc
  source/dem/update_ghost_particle_particle_contact_container.cc
  source/dem/update_local_particle_particle_contact_container.cc
  source/dem/update_particle_container.cc
  source/dem/update_particle_point_line_contact_container.cc
  source/dem/update_particle_wall_contact_container.cc
Labels: reviewed and ready to merge, refactor

#618 Fix void fraction calculation mode in examples
  examples/unresolved-cfd-dem/cylindrical-packed-bed/flow-in-bed.prm
  examples/unresolved-cfd-dem/cylindrical-packed-bed/output_dem/dummy
  examples/unresolved-cfd-dem/cylindrical-packed-bed/packing-in-cylinder.prm
  examples/unresolved-cfd-dem/square-fluidized-bed/fluidized-bed.prm
Labels: quick fix, ready for review

#615 Add custom cylinder meshes
  applications_tests/gls_navier_stokes_3d/poiseuille3d_balanced_grid.output
  applications_tests/gls_navier_stokes_3d/poiseuille3d_balanced_grid.prm
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/parameters/cfd/images/cylindrical_meshes.png
  doc/source/parameters/cfd/mesh.rst
  include/core/parameters.h
  source/core/grids.cc
  source/core/parameters.cc
Labels: enhancement, reviewed and ready to merge

#617 Add rectangular hopper example for DEM
  contrib/postprocessing/Lethe_pyvista_tools.py
  doc/source/examples/dem/dem.rst
  doc/source/examples/dem/rectangular-hopper/images/figure_hopper.png
  doc/source/examples/dem/rectangular-hopper/images/packed_hopper_2d.png
  doc/source/examples/dem/rectangular-hopper/images/packed_hopper_3d.png
  doc/source/examples/dem/rectangular-hopper/images/simulation_end.png
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  examples/dem/3d-rectangular-hopper/hopper.prm
  examples/dem/3d-rectangular-hopper/hopper90.geo
  examples/dem/3d-rectangular-hopper/hopper90.msh
  examples/dem/3d-rectangular-hopper/hopper_post_processing.py
  examples/dem/3d-rectangular-hopper/output/placeholder
  examples/dem/3d-rectangular-hopper/paper_data.csv
Labels: documentation, reviewed and ready to merge

#625 Add post-processing capabilities when using log output with DEM
  applications_tests/cfd_dem_coupling_3d/dynamic_contact_search.output
  applications_tests/cfd_dem_coupling_3d/liquid_fluidized_bed.output
  applications_tests/cfd_dem_coupling_3d/particle_sedimentation.output
  applications_tests/cfd_dem_coupling_3d/restart_particle_sedimentation.output
  applications_tests/dem_3d/insert_list_3d.output
  applications_tests/dem_3d/insert_periodic_boundary_gmsh.output
  applications_tests/dem_3d/outlet_boundary.output
  applications_tests/dem_3d/periodic_boundary_box.output
  applications_tests/dem_3d/periodic_boundary_load_balancing.mpirun=2.output
  applications_tests/dem_3d/periodic_multiple_boundaries.output
  include/core/simulation_control.h
  include/core/utilities.h
  include/dem/dem.h
  include/dem/post_processing.h
  source/dem/dem.cc
  source/dem/post_processing.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: enhancement
