Repository chaos-polymtl/lethe, pull requests merged in 2022-11, with the labels that each got.

#628 Add parameter to impose initial conditions to DEM particles + fix Magnus force parameter
  applications_tests/dem_3d/initial_value_insertion.output
  applications_tests/dem_3d/initial_value_insertion.prm
  doc/source/parameters/dem/insertion_info.rst
  include/core/parameters_lagrangian.h
  source/core/parameters_lagrangian.cc
  source/dem/insertion.cc
  source/fem-dem/parameters_cfd_dem.cc
Labels: enhancement, quick fix, ready for review

#634 Copy grids to DEM
  include/dem/read_mesh.h
  source/dem/read_mesh.cc
Labels: quick fix, ready for review, needs one more review

#637 Change steady-bdf to steady_bdf in documentation
  doc/source/parameters/cfd/simulation_control.rst
Labels: documentation, quick fix

#632 Fix dem hopper example
  applications_tests/dem_2d/circle_restart.prm
  applications_tests/dem_2d/circle_restart_generator.prm
  applications_tests/dem_2d/circle_with_floating_walls.prm
  applications_tests/dem_2d/rotating_in_circle.prm
  applications_tests/dem_2d/two_types_packing_in_circle.prm
  applications_tests/dem_3d/box_grid_slide.prm
  applications_tests/dem_3d/floating_mesh.prm
  applications_tests/dem_3d/insert_periodic_boundary_gmsh.prm
  applications_tests/dem_3d/packing_in_ball_dynamic_contact.prm
  applications_tests/dem_3d/packing_in_ball_dynamic_load_balance.prm
  applications_tests/dem_3d/packing_in_box.prm
  applications_tests/dem_3d/packing_in_cylinder.prm
  applications_tests/dem_3d/periodic_boundary_box.prm
  applications_tests/dem_3d/periodic_boundary_load_balancing.prm
  applications_tests/dem_3d/periodic_multiple_boundaries.prm
  doc/source/examples/dem/3d-small-scale-rotating-drum/3d-small-scale-rotating-drum.rst
  doc/source/examples/dem/granular-mixer/granular-mixer.rst
  doc/source/examples/dem/packing-in-ball/packing-in-ball.rst
  doc/source/examples/dem/packing-in-circle/packing-in-circle.rst
  doc/source/examples/dem/rectangular-hopper/images/figure_hopper.png
  doc/source/examples/dem/rectangular-hopper/images/packed_hopper_2d.png
  doc/source/examples/dem/rectangular-hopper/images/packed_hopper_3d.png
  doc/source/examples/dem/rectangular-hopper/images/simulation_end.png
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/silo/silo.rst
  examples/dem/2d-packing-in-circle/packing-in-circle.prm
  examples/dem/3d-granular-mixer/granular-mixer.prm
  examples/dem/3d-packing-in-ball/packing-in-ball.prm
  examples/dem/3d-rectangular-hopper/hopper.prm
  examples/dem/3d-rectangular-hopper/hopper90.geo
  examples/dem/3d-rectangular-hopper/hopper90.msh
  examples/dem/3d-rectangular-hopper/hopper_structured.geo
  examples/dem/3d-rectangular-hopper/hopper_structured.msh
  examples/dem/3d-rotating-drum-with-post-processing/rotating-drum-with-post-processing.prm
  examples/dem/3d-rotating-drum/rotating-drum.prm
  examples/dem/3d-small-scale-rotating-drum/packing-rotating-drum.prm
  examples/dem/3d-small-scale-rotating-drum/small-rotating-drum-dem.prm
Labels: reviewed and ready to merge, quick fix

#633 Add DEM container manager
  include/dem/dem.h
  include/dem/dem_container_manager.h
  include/dem/particle_particle_broad_search.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_particle_fine_search.h
  include/dem/particle_particle_linear_force.h
  include/dem/particle_particle_nonlinear_force.h
  include/dem/update_fine_search_candidates.h
  include/dem/update_local_particle_containers.h
  include/fem-dem/cfd_dem_coupling.h
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/dem_container_manager.cc
  source/dem/particle_particle_broad_search.cc
  source/dem/particle_particle_fine_search.cc
  source/dem/particle_particle_linear_force.cc
  source/dem/particle_particle_nonlinear_force.cc
  source/dem/update_fine_search_candidates.cc
  source/dem/update_local_particle_containers.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/find_contact_pairs.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_particle_fine_search.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: reviewed and ready to merge, refactor

#641 L2 projection nodes output
  doc/source/parameters/cfd/post_processing.rst
  examples/resolved-cfd-dem/sphere-carreau-with-sharp-interface/sphere-carreau-with-sharp-interface.prm
  include/core/parameters.h
  include/solvers/navier_stokes_base.h
  include/solvers/post_processors_smoothing.h
  source/core/parameters.cc
  source/solvers/CMakeLists.txt
  source/solvers/navier_stokes_base.cc
  source/solvers/post_processors_smoothing.cc
Labels: enhancement, reviewed and ready to merge, Lethe Hackathon

#640 Output single grid DEM
  doc/source/examples/dem/rotating-drum-with-post-processing/rotating-drum-with-post-processing.rst
  doc/source/examples/dem/silo/silo.rst
  doc/source/parameters/dem/dem.rst
  doc/source/parameters/dem/post-processing.rst
  examples/dem/3d-rotating-drum-with-post-processing/rotating-drum-with-post-processing.prm
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/lagrangian_post_processing.h
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/lagrangian_post_processing.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: documentation, ready for review, needs one more review, refactor

#646 correct pvd handler for ib_particle
  applications_tests/gls_sharp_navier_stokes_3d/CMakeLists.txt
  applications_tests/gls_sharp_navier_stokes_3d/check_point.ib_particles.pvdhandler
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: bug, enhancement, maintenance

#643 Correct contact bugs sharp
  applications_tests/gls_sharp_navier_stokes_2d/flow_around_multiple_objects.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_lubrication_test.output
  include/fem-dem/gls_sharp_navier_stokes.h
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: bug, maintenance
