Repository chaos-polymtl/lethe, pull requests merged in 2022-08, with the labels that each got.

#544 use the contact search radius
  source/fem-dem/ib_particles_dem.cc
Labels: reviewed and ready to merge

#548 Corrected 2 bug that were affecting the convergence in large case
  applications_tests/gls_sharp_navier_stokes_2d/couette2d_gls_poisson.output
  applications_tests/gls_sharp_navier_stokes_2d/flow_around_multiple_objects.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cuthollowsphere.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_torus.output
  applications_tests/gls_sharp_navier_stokes_3d/moving_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/moving_stokes.prm
  applications_tests/gls_sharp_navier_stokes_3d/pp_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/spinning_cone.output
  applications_tests/gls_sharp_navier_stokes_3d/static_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/static_stokes.prm
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: bug, maintenance, quick fix, ready for review

#550 Add invitation to cite deal.II when citing Lethe
  doc/source/referencing.rst
Labels: documentation

#547 Floating mesh documentation
  doc/source/parameters/dem/dem.rst
  doc/source/parameters/dem/floating_mesh.rst
  doc/source/parameters/dem/floating_wall.rst
Labels: documentation, reviewed and ready to merge

#534 Use average velocity field for multiphysics
  doc/source/parameters/cfd/multiphysics.rst
  include/core/parameters_multiphysics.h
  include/solvers/gd_navier_stokes.h
  include/solvers/gls_navier_stokes.h
  include/solvers/multiphysics_interface.h
  include/solvers/navier_stokes_base.h
  include/solvers/postprocessing_velocities.h
  source/core/parameters_multiphysics.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_velocities.cc
Labels: enhancement, Lethe Hackathon, ready for review

#546 Ribbon gls example
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/3d_mixer_using_single_rotating_frame.rst
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/images/Np-Re.png
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/images/eulerian_vs_langrangian_reference.jpg
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/images/geometry.svg
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/images/velocity_eulerian.png
  doc/source/examples/incompressible-flow/3d_mixer_using_single_rotating_frame/images/velocity_magnitude.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/installation/compute_canada.rst
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/velocity_source.rst
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/gather_torques.sh
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/launch_all_mixers.py
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/lethe_case_generator.py
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/plot_Np_vs_Re.py
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/ribbon_gls.prm
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/template/launch_mixer.sh
  examples/incompressible_flow/3d_ribbon_mixer_srf/Np_vs_Re/template/output/placeholder
  examples/incompressible_flow/3d_ribbon_mixer_srf/Re1/output/placeholder
  examples/incompressible_flow/3d_ribbon_mixer_srf/Re1/ribbon_gls_Re1.prm
  examples/incompressible_flow/3d_ribbon_mixer_srf/db_helical.step
  examples/incompressible_flow/3d_ribbon_mixer_srf/diff_step_mesh.geo
Labels: reviewed and ready to merge, rebased

#552 Enhancements vans
  doc/source/parameters/unresolved_cfd-dem/cfd_dem.rst
  include/fem-dem/gls_vans.h
  include/fem-dem/vans_assemblers.h
  source/fem-dem/gls_vans.cc
  source/fem-dem/vans_assemblers.cc
Labels: enhancement, rebased

#551 Add granular mixing example
  doc/source/examples/dem/dem.rst
  doc/source/examples/dem/granular-mixer/granular-mixer.rst
  examples/dem/3d_granular_mixer/granular_mixer.prm
  examples/dem/3d_granular_mixer/pitched_blade_impeller.msh
Labels: reviewed and ready to merge

#557 PBC in DEM - Periodic mapping & Particles displacement
  applications_tests/dem_3d/periodic_boundary_box.mpirun=2.output
  applications_tests/dem_3d/periodic_boundary_box.prm
  applications_tests/dem_3d/periodic_multiple_boundaries.output
  applications_tests/dem_3d/periodic_multiple_boundaries.prm
  include/core/manifolds.h
  include/core/parameters_lagrangian.h
  include/dem/boundary_cells_info_struct.h
  include/dem/dem.h
  include/dem/floating_grid.h
  include/dem/particle_particle_broad_search.h
  include/dem/periodic_boundaries_manipulator.h
  include/dem/read_mesh.h
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/find_boundary_cells_information.cc
  source/dem/floating_grid.cc
  source/dem/periodic_boundaries_manipulator.cc
  source/dem/read_mesh.cc
Labels: reviewed and ready to merge

#559 Fix contact bug
  applications/gls_sharp_navier_stokes_2d/gls_sharp_navier_stokes_2d.cc
  applications/gls_sharp_navier_stokes_3d/gls_sharp_navier_stokes_3d.cc
  applications_tests/gls_sharp_navier_stokes_2d/couette2d_gls.output
  applications_tests/gls_sharp_navier_stokes_2d/couette2d_gls_poisson.output
  applications_tests/gls_sharp_navier_stokes_2d/flow_around_multiple_objects.output
  applications_tests/gls_sharp_navier_stokes_2d/moving_rectangle.output
  applications_tests/gls_sharp_navier_stokes_2d/taylorcouette2d_carreau_gls.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cone_deathstar.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cuthollowsphere.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_ellipsoid_rectangle.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_torus.output
  applications_tests/gls_sharp_navier_stokes_3d/spinning_cone.output
  applications_tests/gls_sharp_navier_stokes_3d/static_stokes.output
  applications_tests/gls_sharp_navier_stokes_3d/steady_couette_sphere.output
  applications_tests/gls_sharp_navier_stokes_3d/steady_couette_sphere_poisson.output
  include/fem-dem/gls_sharp_navier_stokes.h
  include/fem-dem/ib_particles_dem.h
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/fem-dem/ib_particles_dem.cc
Labels: bug, maintenance, ready for review

#562 DEM theory
  doc/source/theory/dem/dem.rst
  doc/source/theory/dem/images/collision_particles.png
  doc/source/theory/theory.rst
  doc/source/theory/unresolved_cfd-dem/unresolved_cfd-dem.rst
Labels: documentation

#567 Modify printing order of particles for DEM tests
  applications_tests/dem_3d/periodic_boundary_box.output
  applications_tests/dem_3d/periodic_boundary_load_balancing.mpirun=2.output
  applications_tests/dem_3d/periodic_boundary_load_balancing.prm
  source/dem/visualization.cc
Labels: quick fix

#575 Add initial adaptive refinement
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  include/core/parameters.h
  include/solvers/navier_stokes_base.h
  source/core/parameters.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
Labels: enhancement, reviewed and ready to merge
