Repository chaos-polymtl/lethe, pull requests merged in 2022-09, with the labels that each got.

#566 Nitsche ib for heat
  applications/gd_navier_stokes_2d/gd_navier_stokes_2d.cc
  applications/gd_navier_stokes_3d/gd_navier_stokes_3d.cc
  applications/gls_navier_stokes_2d/gls_navier_stokes_2d.cc
  applications/gls_navier_stokes_3d/gls_navier_stokes_3d.cc
  applications/gls_nitsche_navier_stokes_22/gls_nitsche_navier_stokes_22.cc
  applications/gls_nitsche_navier_stokes_23/gls_nitsche_navier_stokes_23.cc
  applications/gls_nitsche_navier_stokes_33/gls_nitsche_navier_stokes_33.cc
  applications_tests/gls_nitsche_navier_stokes_22/impeller.prm
  applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_moving.output
  applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_moving.prm
  applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_static.output
  applications_tests/gls_nitsche_navier_stokes_22/nitsche_heating_static.prm
  applications_tests/gls_nitsche_navier_stokes_22/noslip_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/poiseuille_22.prm
  applications_tests/gls_nitsche_navier_stokes_22/taylor_couette_nitsche_22.prm
  applications_tests/gls_nitsche_navier_stokes_23/couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_23/taylor-couette_23.prm
  applications_tests/gls_nitsche_navier_stokes_33/noslip_33.prm
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/3d_nitsche_mixer_with_pbt_impeller/nitsche_mixer_with_pbt_impeller.rst
  doc/source/parameters/cfd/initial_conditions.rst
  doc/source/parameters/cfd/nitsche.rst
  doc/source/parameters/cfd/source_term.rst
  examples/incompressible_flow/3d_nitsche_mixer_with_pbt_impeller/mixer.prm
  include/core/exceptions.h
  include/core/solid_base.h
  include/core/solid_objects_parameters.h
  include/solvers/gd_navier_stokes.h
  include/solvers/gls_navier_stokes.h
  include/solvers/gls_nitsche_navier_stokes.h
  include/solvers/heat_transfer.h
  include/solvers/multiphysics_interface.h
  source/core/CMakeLists.txt
  source/core/parameters.cc
  source/core/solid_base.cc
  source/solvers/gls_nitsche_navier_stokes.cc
  source/solvers/heat_transfer.cc
Labels: enhancement, ready for review, rebased

#582 Doc win install
  doc/source/index.rst
  doc/source/installation/apple_arm.rst
  doc/source/installation/images/apple.png
  doc/source/installation/images/linux.png
  doc/source/installation/images/windows.png
  doc/source/installation/installation.rst
  doc/source/installation/regular_installation.rst
  doc/source/installation/windows_wsl.rst
  logo/logo_black2.png
Labels: documentation, reviewed and ready to merge

#585 Parameters for multivariable mesh adaptation
  applications_tests/gd_navier_stokes_2d/cylinder_carreau_gd.prm
  include/core/parameters.h
  include/solvers/auxiliary_physics.h
  include/solvers/heat_transfer.h
  include/solvers/multiphysics_interface.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
Labels: ready for review, rebased

#596 Added preprint to contributions and references
  doc/source/publications.rst
  doc/source/referencing.rst
Labels: documentation

#595 Update installation on WSL documentation
  doc/source/installation/windows_wsl.rst
Labels: documentation, reviewed and ready to merge, quick fix

#601 Small fix in the jacobian weak formulation and residual
  doc/source/theory/fluid_dynamics/fem_formulation.rst
Labels: documentation, quick fix

#600 Fix some issues with periodic boundary condition with cfd-dem
  applications_tests/dem_3d/CMakeLists.txt
  applications_tests/dem_3d/insert_periodic_boundary_gmsh.output
  applications_tests/dem_3d/insert_periodic_boundary_gmsh.prm
  applications_tests/dem_3d/periodic_gmsh_files/pipe.geo
  applications_tests/dem_3d/periodic_gmsh_files/pipe.msh
  include/dem/find_boundary_cells_information.h
  include/fem-dem/cfd_dem_coupling.h
  source/dem/find_boundary_cells_information.cc
  source/dem/periodic_boundaries_manipulator.cc
  source/dem/read_mesh.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: ready for review
