Repository chaos-polymtl/lethe, pull requests merged in 2022-06, with the labels that each got.

#493 Update rheological physical properties documentation
  doc/source/parameters/cfd/images/physical_properties_carreau.png
  doc/source/parameters/cfd/images/physical_properties_powerlaw.png
  doc/source/parameters/cfd/physical_properties.rst
  source/core/parameters.cc
Labels: documentation

#487 Sharp carreau lethe example
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/resolved_cfd-dem/resolved_cfd-dem.rst
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/carreau.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/pressure.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/sharp_carreau_case.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/shear_rate.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/velocity.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/images/viscosity.png
  doc/source/examples/resolved_cfd-dem/sphere-carreau-with-sharp-interface/sphere-carreau-with-sharp-interface.rst
  examples/resolved_cfd-dem/sphere_carreau_with_sharp_interface/sphere_carreau_with_sharp_interface.prm
Labels: documentation, Reviewed and ready to merge

#491 Add laser beam direction to laser heat source term
  applications_tests/gls_navier_stokes_2d/heat_transfer_laser.prm
  doc/source/examples/multiphysics/laser-melting/laser-melting.rst
  doc/source/parameters/cfd/laser_heat_source.rst
  examples/multiphysics/laser_melting/laser_melting.prm
  include/core/parameters.h
  source/core/parameters.cc
  source/solvers/heat_transfer_assemblers.cc
Labels: enhancement

#492 Add none BC to heat_transfer
  doc/source/examples/multiphysics/warming-up-a-viscous-fluid/warming-up-a-viscous-fluid.rst
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  examples/multiphysics/warming_up_viscous_fluid/warming_up_viscous_fluid.prm
  include/core/boundary_conditions.h
  tests/solvers/restart_01.cc
Labels: documentation

#503 Add two recent preprints to the documentation
  doc/source/publications.rst
Labels: documentation

#510 Fix vof ht
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_heated-walls.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_heated-walls.prm
  include/solvers/heat_transfer_scratch_data.h
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_scratch_data.cc
  source/solvers/navier_stokes_scratch_data.cc
Labels: quick fix
