Repository chaos-polymtl/lethe, pull requests merged in 2023-09, with the labels that each got.

#861 Small addition in linear solver parameters documentation
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: documentation, quick fix, ready for review

#862 Fix dynamic viscosity output
  source/solvers/navier_stokes_base.cc
Labels: quick fix, ready for review

#829 Reduce memory rbf
  applications_tests/gls_sharp_navier_stokes/cavatappi_composite_test.prm
  applications_tests/gls_sharp_navier_stokes/check_point.prm
  applications_tests/gls_sharp_navier_stokes/coupled_moving_stokes.prm
  applications_tests/gls_sharp_navier_stokes/flow_around_cone_deathstar.prm
  applications_tests/gls_sharp_navier_stokes/flow_around_cuthollowsphere.prm
  applications_tests/gls_sharp_navier_stokes/flow_around_ellipsoid_rectangle.prm
  applications_tests/gls_sharp_navier_stokes/flow_around_rbf.prm
  applications_tests/gls_sharp_navier_stokes/flow_around_torus.prm
  applications_tests/gls_sharp_navier_stokes/load_particles_from_file_test.prm
  applications_tests/gls_sharp_navier_stokes/moving_ib_gls.prm
  applications_tests/gls_sharp_navier_stokes/moving_ib_gls_poisson.prm
  applications_tests/gls_sharp_navier_stokes/moving_rectangle.prm
  applications_tests/gls_sharp_navier_stokes/moving_stokes_2d.prm
  applications_tests/gls_sharp_navier_stokes/opencascade/static_stokes_step.prm
  applications_tests/gls_sharp_navier_stokes/rbf_sphere_mms.prm
  applications_tests/gls_sharp_navier_stokes/rbf_sphere_mms_adaptive.prm
  applications_tests/gls_sharp_navier_stokes/sphere_power_law_ramp.prm
  applications_tests/gls_sharp_navier_stokes/spinning_cone.prm
  applications_tests/gls_sharp_navier_stokes/spooky_composite_test.prm
  applications_tests/gls_sharp_navier_stokes/static_stokes.prm
  doc/source/parameters/sharp-immersed-boundary-solver/sharp-immersed-boundary-solver.rst
  include/core/ib_particle.h
  include/core/parameters.h
  include/core/shape.h
  source/core/ib_particle.cc
  source/core/parameters.cc
  source/core/shape.cc
  source/core/shape_parsing.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: ready for review

#865 Enhance post-processing module performance
  .gitignore
  contrib/postprocessing/README.md
  contrib/postprocessing/lethe_pyvista_tools.py
  contrib/postprocessing/lethe_pyvista_tools/__init__.py
  contrib/postprocessing/lethe_pyvista_tools/_get_cylindrical_coords.py
  contrib/postprocessing/lethe_pyvista_tools/_get_df.py
  contrib/postprocessing/lethe_pyvista_tools/_get_nearest_neighbors.py
  contrib/postprocessing/lethe_pyvista_tools/_mixing_index_doucet.py
  contrib/postprocessing/lethe_pyvista_tools/_mixing_index_nearest_neighbors.py
  contrib/postprocessing/lethe_pyvista_tools/_modify_array.py
  contrib/postprocessing/lethe_pyvista_tools/_sort_by_array.py
  contrib/postprocessing/lethe_pyvista_tools/_write_df_to_vtu.py
  contrib/postprocessing/lethe_pyvista_tools/parallel_run.py
  contrib/postprocessing/requirements.txt
  contrib/postprocessing/setup.py
  doc/source/examples/dem/bouncing-particle/bouncing-particle.rst
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/small-scale-rotating-drum-post-processing.rst
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/sloshing-in-rectangular-tank/sloshing-in-rectangular-tank.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.rst
  doc/source/theory/fluid_dynamics/stabilization.rst
  doc/source/tools/postprocessing/postprocessing.rst
  doc/source/tools/tools.rst
  examples/dem/3d-bouncing-particle/bouncing_particle_post_processing.py
  examples/dem/3d-rectangular-hopper/hopper_post_processing.py
  examples/dem/3d-small-scale-rotating-drum-postprocessing/3d-example_small_rotating_drum.py
  examples/multiphysics/air-bubble-compression/air-bubble-compression-postprocessing.py
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_postprocessing.py
  examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell-postprocessing.py
Labels: reviewed and ready to merge, refactor, Post-processing

#870 Check if file exist when reading dim
  source/core/utilities.cc
Labels: reviewed and ready to merge

#871 Remove unused AdditionalData object in the AMG preconditioner
  source/solvers/gls_navier_stokes.cc
Labels: reviewed and ready to merge, quick fix

#874 Reupdate all incompressible flow examples
  doc/source/examples/incompressible-flow/2d-naca0012-low-reynolds/2d-naca0012-low-reynolds.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/2d-transient-flow-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re28-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re28-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re288-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re288-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-mesh-t0.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-mesh-t005.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-mesh-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/ahmed-bc.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/ahmed-geometry.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/ahmed-mesh.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-1-ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-2-ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-3-ahmed.jfif
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/tools/gmsh/gmsh.rst
  examples/incompressible-flow/2d-backward-facing-step/Reynolds100-600/2D-backward-facing-step-steady.prm
  examples/incompressible-flow/2d-backward-facing-step/Reynolds700-1000/2D-backward-facing-step-steadybdf.prm
  examples/incompressible-flow/2d-lid-driven-cavity/Reynolds_7500/cavity.prm
  examples/incompressible-flow/2d-naca0012-low-reynolds/naca.prm
  examples/incompressible-flow/2d-nitsche-taylor-couette/adaptative-nitsche-taylor-couette.prm
  examples/incompressible-flow/2d-nitsche-taylor-couette/uniform-nitsche-taylor-couette.prm
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body-simplex/Ahmed-Body-20-2D.geo
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body-simplex/ahmed.prm
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body/Ahmed-Body-20-2D.geo
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body/ahmed.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-0.1.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-150.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-adapt.prm
  examples/incompressible-flow/3d-ribbon-mixer-srf/Np_vs_Re/ribbon-gls.prm
  examples/incompressible-flow/3d-ribbon-mixer-srf/Re1/ribbon-gls-Re1.prm
Labels: ready for review

#880 Create preconditioner sections in linear solver documentation
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: documentation, quick fix

#883 Replace 'adaptative' by 'adaptive' in interface sharpening methods
  applications_tests/lethe-fluid/interface_sharpening_blurred_circle_adaptive_mass_conservation.prm
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  include/core/parameters_multiphysics.h
  include/solvers/simulation_parameters.h
  include/solvers/vof.h
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
Labels: maintenance, reviewed and ready to merge, quick fix

#879 Free angle ch
  applications_tests/lethe-fluid/cahn_hilliard_navier_stokes_coupling.output
  applications_tests/lethe-fluid/cahn_hilliard_navier_stokes_coupling.prm
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/cfd/post_processing.rst
  examples/multiphysics/rising-bubble/rising-bubble.prm
  include/core/boundary_conditions.h
  include/core/mobility_cahn_hilliard_model.h
  include/core/parameters.h
  include/solvers/cahn_hilliard.h
  include/solvers/cahn_hilliard_assemblers.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/physical_properties_manager.h
  source/core/CMakeLists.txt
  source/core/mobility_cahn_hilliard_model.cc
  source/core/parameters.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/cahn_hilliard_assemblers.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_cahn_hilliard_assemblers.cc
  source/solvers/physical_properties_manager.cc
  source/solvers/vof.cc
  tests/core/mobility_cahn_hilliard_constant.cc
  tests/core/mobility_cahn_hilliard_constant.output
  tests/core/mobility_cahn_hilliard_quartic.cc
  tests/core/mobility_cahn_hilliard_quartic.output
Labels: ready for review

#887 Update multiphysics examples
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/dam-break/images/dam-break-initial-configuration.svg
  doc/source/examples/multiphysics/dam-break/images/xmax-t.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/adaptive_mass.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/constant_mass.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/rayleigh-taylor-instability-initial-state.svg
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/smoothedInitialCondition.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/spike_and_bubble_evolution_He_et_al_comparison.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/images/spike_and_bubble_evolution_ref_max_10_ref_min_8.png
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/sloshing-in-rectangular-tank/sloshing-in-rectangular-tank.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/images/figure-water-injection-in-a-closed-cell-density.svg
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/images/figure-water-injection-in-a-closed-cell-pressure.svg
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/parameters/cfd/initial_conditions.rst
  examples/multiphysics/air-bubble-compression/air-bubble-compression.prm
  examples/multiphysics/cahn_hilliard/chns.prm
  examples/multiphysics/dam-break/dam-break-Martin-and-Moyce.prm
  examples/multiphysics/dam-break/xmax-t.png
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-constant-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor_postprocess.py
  examples/multiphysics/rising-bubble/rising-bubble.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0002/sloshing-in-rectangular-tank_Re0002.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0020/sloshing-in-rectangular-tank_Re0020.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0200/sloshing-in-rectangular-tank_Re0200.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_2000/sloshing-in-rectangular-tank_Re2000.prm
  examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.prm
  tests/dem/particle_point_contact.cc
Labels: maintenance, reviewed and ready to merge, rebased

#890 Fixing typos that I have found when testing stuff
  doc/source/examples/dem/oblique-wall-impact/oblique-wall-impact.rst
  doc/source/parameters/dem/model_parameters.rst
  examples/dem/3d-dam-break/granular-dam-break.prm
Labels: maintenance, documentation, quick fix, ready for review

#889 Dem particle wall tangential overlap
  applications_tests/lethe-fluid-particles/dynamic_contact_search.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.output
  applications_tests/lethe-fluid-sharp/coupled_moving_stokes.mpirun=2.output
  applications_tests/lethe-fluid-sharp/opencascade/static_stokes_step.output
  applications_tests/lethe-fluid-sharp/pw_rolling_test.output
  applications_tests/lethe-fluid-sharp/pw_rolling_test.prm
  applications_tests/lethe-fluid-sharp/rbf_sphere_mms_adaptive.output
  applications_tests/lethe-fluid-sharp/static_stokes.output
  applications_tests/lethe-fluid-sharp/taylorcouette2d_carreau_gls.output
  applications_tests/lethe-particles/ball_with_floating_walls.output
  applications_tests/lethe-particles/box_grid_rotation.output
  applications_tests/lethe-particles/box_grid_slide.output
  applications_tests/lethe-particles/circle_restart.output
  applications_tests/lethe-particles/circle_with_floating_walls.mpirun=1.output
  applications_tests/lethe-particles/floating_mesh.output
  applications_tests/lethe-particles/force_boundary_box.output
  applications_tests/lethe-particles/insert_list_3d_default_velocities.output
  applications_tests/lethe-particles/insert_plane_3d.mpirun=2.output
  applications_tests/lethe-particles/insert_plane_3d.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/mobility_status.output
  applications_tests/lethe-particles/packing_in_ball.mpirun=1.output
  applications_tests/lethe-particles/packing_in_ball.mpirun=2.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_contact.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/packing_in_box.mpirun=1.output
  applications_tests/lethe-particles/packing_in_box.mpirun=2.output
  applications_tests/lethe-particles/packing_in_cylinder.output
  applications_tests/lethe-particles/packing_in_square.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=2.output
  applications_tests/lethe-particles/rolling_on_plane.output
  applications_tests/lethe-particles/rolling_on_plane.prm
  applications_tests/lethe-particles/rotating_in_circle.output
  applications_tests/lethe-particles/sliding_restart.output
  applications_tests/lethe-particles/torque_boundary_box.output
  applications_tests/lethe-particles/two_types_packing_in_circle.output
  include/dem/particle_wall_contact_force.h
  source/dem/particle_wall_contact_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/ib_particles_dem.cc
Labels: bug, ready for review, refactor
