Repository chaos-polymtl/lethe, pull requests merged in 2023-04, with the labels that each got.

#732 Improve CFD-DEM workflow
  applications_tests/cfd_dem_coupling_3d/dynamic_contact_search.output
  applications_tests/cfd_dem_coupling_3d/dynamic_contact_search.prm
  applications_tests/cfd_dem_coupling_3d/liquid_fluidized_bed.output
  applications_tests/cfd_dem_coupling_3d/liquid_fluidized_bed.prm
  applications_tests/cfd_dem_coupling_3d/particle_sedimentation.output
  applications_tests/cfd_dem_coupling_3d/particle_sedimentation.prm
  applications_tests/cfd_dem_coupling_3d/restart_particle_sedimentation.output
  applications_tests/cfd_dem_coupling_3d/restart_particle_sedimentation.prm
  applications_tests/gls_vans_2d/case0_vans.output
  applications_tests/gls_vans_2d/case1_vans.output
  applications_tests/gls_vans_2d/case1_vans_weak.output
  applications_tests/gls_vans_2d/case2_vans.output
  applications_tests/gls_vans_2d/case3_vans.output
  applications_tests/gls_vans_3d/beetstra_packed_bed.output
  applications_tests/gls_vans_3d/beetstra_packed_bed.prm
  applications_tests/gls_vans_3d/dallavalle_packed_bed.output
  applications_tests/gls_vans_3d/dallavalle_packed_bed.prm
  applications_tests/gls_vans_3d/difelice_packed_bed.output
  applications_tests/gls_vans_3d/difelice_packed_bed.prm
  applications_tests/gls_vans_3d/gidaspow_packed_bed.output
  applications_tests/gls_vans_3d/gidaspow_packed_bed.prm
  applications_tests/gls_vans_3d/kochhill_packed_bed.output
  applications_tests/gls_vans_3d/kochhill_packed_bed.prm
  applications_tests/gls_vans_3d/pcm_packed_bed.output
  applications_tests/gls_vans_3d/pcm_packed_bed.prm
  applications_tests/gls_vans_3d/qcm_packed_bed.output
  applications_tests/gls_vans_3d/qcm_packed_bed.prm
  applications_tests/gls_vans_3d/rong_packed_bed.output
  applications_tests/gls_vans_3d/rong_packed_bed.prm
  applications_tests/gls_vans_3d/spm_packed_bed.output
  applications_tests/gls_vans_3d/spm_packed_bed.prm
  doc/source/examples/unresolved-cfd-dem/cylindrical-packed-bed/cylindrical-packed-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.rst
  doc/source/parameters/unresolved-cfd-dem/cfd-dem.rst
  examples/unresolved-cfd-dem/cylindrical-packed-bed/flow-in-bed.prm
  examples/unresolved-cfd-dem/cylindrical-packed-bed/packing-in-cylinder.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/dem-packing-in-fluidized-bed.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-bed/dem-packing-in-spouted-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.prm
  include/core/utilities.h
  include/fem-dem/cfd_dem_coupling.h
  include/fem-dem/gls_vans.h
  include/fem-dem/parameters_cfd_dem.h
  include/solvers/multiphysics_interface.h
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/gls_vans.cc
  source/fem-dem/parameters_cfd_dem.cc
Labels: ready for review, needs one more review

#731 Composite with cell guess
  applications_tests/gls_sharp_navier_stokes_3d/cavatappi_composite_test.output
  applications_tests/gls_sharp_navier_stokes_3d/spooky_composite_test.output
  include/core/shape.h
  include/fem-dem/gls_sharp_navier_stokes.h
  include/solvers/postprocessors.h
  source/core/shape.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  tests/core/shape_composites.cc
  tests/core/shape_composites.output
Labels: ready for review

#740 Add missing contributors to doc
  doc/source/index.rst
Labels: documentation

#737 Bound cell void fraction at 1 for drag model calculation
  source/fem-dem/vans_assemblers.cc
Labels: bug, ready for review

#739 Fix opencacade solid shape
  include/core/shape.h
Labels: bug

#745 Enable Lagrangian post-processing PVD restart
  include/dem/read_checkpoint.h
  include/dem/write_checkpoint.h
  source/dem/dem.cc
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: quick fix, ready for review
