Repository chaos-polymtl/lethe, pull requests merged in 2023-08, with the labels that each got.

#831 Sloshing example update postprocess script
  doc/source/examples/multiphysics/sloshing-in-rectangular-tank/images/initial_state.svg
  doc/source/examples/multiphysics/sloshing-in-rectangular-tank/sloshing-in-rectangular-tank.rst
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_postprocessing.py
Labels: documentation, quick fix, needs one more review

#820 Matrix-free Navier-Stokes prototype
  prototypes/CMakeLists.txt
  prototypes/matrix_free_navier_stokes/CMakeLists.txt
  prototypes/matrix_free_navier_stokes/matrix_free_navier_stokes.cc
  prototypes/matrix_free_navier_stokes/parameters.prm
Labels: reviewed and ready to merge

#830 Add isothermal compressible NSVOF assemblers
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/gls_navier_stokes_2d/gls_vof_1_isothermal_compressible_fluid.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/gls_navier_stokes_2d/gls_vof_2_isothermal_compressible_fluids.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_dirichlet_boundary_condition.output
  applications_tests/gls_navier_stokes_2d/gls_vof_heat-transfer_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_initial_refine.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_static_droplet_surface_tension_force_with_tanh_filter.output
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting_mesh-adapt.output
  doc/source/parameters/cfd/physical_properties.rst
  include/core/density_model.h
  include/solvers/isothermal_compressible_navier_stokes_vof_assembler.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/postprocessors.h
  include/solvers/vof.h
  include/solvers/vof_scratch_data.h
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/CMakeLists.txt
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/isothermal_compressible_navier_stokes_vof_assembler.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
  source/solvers/vof_scratch_data.cc
  tests/solvers/restart_01.cc
Labels: reviewed and ready to merge, rebased

#839 Deprecate SDIRK time integrators
  applications_tests/gls_navier_stokes/taylor-green-vortex_gls_sdirk2.mpirun=2.output
  applications_tests/gls_navier_stokes/taylor-green-vortex_gls_sdirk2.prm
  applications_tests/gls_navier_stokes/taylor-green-vortex_gls_sdirk3.mpirun=2.output
  applications_tests/gls_navier_stokes/taylor-green-vortex_gls_sdirk3.prm
  doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst
  doc/source/examples/sharp-immersed-boundary-solver/sedimentation-1-particle/sedimentation-1-particle.rst
  doc/source/parameters/cfd/simulation_control.rst
  include/core/parameters.h
  include/core/sdirk.h
  include/core/time_integration_utilities.h
  include/solvers/cahn_hilliard.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/heat_transfer.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/navier_stokes_assemblers.h
  include/solvers/navier_stokes_base.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/tracer.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof.h
  include/solvers/vof_scratch_data.h
  source/core/CMakeLists.txt
  source/core/parameters.cc
  source/core/simulation_control.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/fem-dem/gls_vans.cc
  source/fem-dem/vans_assemblers.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/cahn_hilliard_scratch_data.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/gls_nitsche_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_scratch_data.cc
  source/solvers/isothermal_compressible_navier_stokes_assembler.cc
  source/solvers/isothermal_compressible_navier_stokes_vof_assembler.cc
  source/solvers/mf_gls_navier_stokes.cc
  source/solvers/navier_stokes_assemblers.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/navier_stokes_cahn_hilliard_assemblers.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/tracer.cc
  source/solvers/tracer_scratch_data.cc
  source/solvers/vof.cc
  source/solvers/vof_scratch_data.cc
  tests/core/simulation_control_05.cc
  tests/core/simulation_control_05.output
Labels: reviewed and ready to merge

#841 Update references in doc
  doc/source/contributing.rst
  doc/source/examples/dem/granular-dam-break/granular-dam-break.rst
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/silo/silo.rst
  doc/source/examples/multiphysics/3d-dam-break/3d-dam-break.rst
  doc/source/examples/multiphysics/concentric-heat-exchanger/concentric-heat-exchanger.rst
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/laser-meltpool/laser-meltpool.rst
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/examples/multiphysics/stefan-problem/stefan-problem.rst
  doc/source/examples/rpt/particle-fem-reconstruction/particle-fem-reconstruction.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/theory/dem/dem.rst
  doc/source/theory/fluid_dynamics/linear_solvers.rst
  doc/source/theory/multiphysics/vof.rst
  doc/source/theory/theory.rst
  doc/source/theory/unresolved_cfd-dem/unresolved_cfd-dem.rst
Labels: maintenance, documentation, reviewed and ready to merge, rebased

#835 Parameter to disable extrapolation in sharp IB solver
  doc/source/parameters/sharp-immersed-boundary-solver/sharp-immersed-boundary-solver.rst
  include/core/parameters.h
  source/core/parameters.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: ready for review

#847 Find contact detection step interval
  applications_tests/dem/initial_value_insertion.prm
  doc/source/parameters/dem/model_parameters.rst
  include/dem/find_contact_detection_step.h
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic.prm
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic_load_balancing.prm
  performance_analyses/dem/short_packing_10k_particles/time_case.sh
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/find_contact_detection_step.cc
Labels: reviewed and ready to merge

#849 Add timer per physics
  include/solvers/cahn_hilliard.h
  include/solvers/heat_transfer.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/solvers/cahn_hilliard.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: reviewed and ready to merge

#852 Remove redundant set function expression
  include/core/boundary_conditions.h
  include/core/solid_objects_parameters.h
  include/solvers/initial_conditions.h
  include/solvers/source_terms.h
  source/core/parameters.cc
  source/fem-dem/parameters_cfd_dem.cc
  source/solvers/analytical_solutions.cc
Labels: maintenance, ready for review

#845 Liquid-solid fluidized bed example
  doc/source/examples/dem/rotation-of-box/rotation-of-box.rst
  doc/source/examples/unresolved-cfd-dem/boycott-effect/boycott-effect.rst
  doc/source/examples/unresolved-cfd-dem/cylindrical-packed-bed/cylindrical-packed-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.rst
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/images/experimental_setup.png
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/images/mesh_cross_sec.png
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/images/pressure_time.gif
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
  examples/unresolved-cfd-dem/boycott-effect/boycott-effect.prm
  examples/unresolved-cfd-dem/boycott-effect/particle-generator.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/dem-packing-in-lsfb.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/lsfb_postprocessing.py
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/output/dummy-file
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/output_dem/dummy-file
Labels: documentation, reviewed and ready to merge

#855 Fix pvd files to match modified vtu
  contrib/postprocessing/lethe_pyvista_tools.py
Labels: quick fix, WIP, Post-processing

#854 Refactor surface tension gradient parameter
  applications_tests/gls_navier_stokes/gls_droplet_marangoni_effect.prm
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/core/surface_tension_model.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/physical_properties_manager.h
  include/solvers/simulation_parameters.h
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/core/surface_tension_model.cc
  source/solvers/multiphysics_interface.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/physical_properties_manager.cc
  tests/core/surface_tension_linear.cc
  tests/core/surface_tension_linear.output
Labels: ready for review, refactor

#858 Add reference state temperature to linear surface tension model
  applications_tests/gls_navier_stokes/gls_droplet_marangoni_effect.prm
  doc/source/parameters/cfd/physical_properties.rst
  include/core/parameters.h
  include/core/surface_tension_model.h
  source/core/parameters.cc
  tests/core/surface_tension_linear.cc
  tests/core/surface_tension_linear.output
Labels: reviewed and ready to merge

#859 Correct typo in static bubble prm file
  examples/multiphysics/static-bubble/static-bubble.prm
Labels: quick fix, ready for review
