Repository chaos-polymtl/lethe, pull requests merged in 2023-07, with the labels that each got.

#787 Update periodic hopper example
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  examples/dem/3d-rectangular-hopper/hopper_post_processing.py
Labels: quick fix, ready for review

#788 Augment the maximum number of solid object to 10
  include/core/solid_objects_parameters.h
Labels: quick fix, ready for review

#789 Typo mistake in the bouncing particle example
  doc/source/theory/dem/dem.rst
Labels: quick fix, ready for review

#799 Disable DG prototypes
  prototypes/CMakeLists.txt
Labels: quick fix, Lethe Hackathon 2023

#804 Fix links in example diagrams in documentation
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/examples/rpt/rpt.rst
  doc/source/examples/sharp-immersed-boundary-solver/sharp-immersed-boundary-solver.rst
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
Labels: documentation, quick fix, Lethe Hackathon 2023

#797 Clear the tangential overlap after load balancing in DEM
  applications_tests/dem_3d/load_balancing_mobility_status.mpirun=2.output
  applications_tests/dem_3d/load_balancing_solid_object.mpirun=2.output
  include/dem/dem_container_manager.h
  include/dem/update_local_particle_containers.h
  source/dem/dem.cc
  source/dem/dem_container_manager.cc
  source/dem/update_local_particle_containers.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: reviewed and ready to merge, quick fix, Lethe Hackathon 2023

#806 Fix parameter files after models subsection in DEM
  doc/source/parameters/dem/model_parameters.rst
  examples/dem/2d-packing-in-circle/packing-in-circle.prm
  examples/dem/3d-bouncing-particle/bouncing_particle_original.prm
  examples/dem/3d-dam-break/granular-dam-break-H-40cm.prm
  examples/dem/3d-dam-break/granular-dam-break.prm
  examples/dem/3d-granular-mixer/granular-mixer.prm
  examples/dem/3d-grid-rotation-in-box/grid-rotation-box.prm
  examples/dem/3d-packing-in-ball/packing-in-ball.prm
  examples/dem/3d-rectangular-hopper/hopper.prm
  examples/unresolved-cfd-dem/boycott-effect/boycott-effect.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  performance_analyses/dem/packing_10k_particles/packing_10k_particles.prm
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic.prm
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic_load_balancing.prm
Labels: quick fix, Lethe Hackathon 2023, ready for review

#805 Refactor the contact manager in DEM
  include/dem/dem.h
  include/dem/dem_contact_manager.h
  include/dem/find_boundary_cells_information.h
  include/dem/find_contact_detection_step.h
  include/dem/particle_particle_broad_search.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_particle_fine_search.h
  include/dem/particle_wall_broad_search.h
  include/dem/periodic_boundaries_manipulator.h
  include/fem-dem/cfd_dem_coupling.h
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/dem_contact_manager.cc
  source/dem/particle_particle_broad_search.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_particle_fine_search.cc
  source/dem/particle_wall_broad_search.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/find_contact_pairs.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_particle_fine_search.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Lethe Hackathon 2023, ready for review, refactor

#798 Initial position and rotation for solid object
  doc/source/parameters/dem/floating_mesh.rst
  include/core/parameters.h
  include/core/serial_solid.h
  include/core/solid_base.h
  source/core/grids.cc
  source/core/parameters.cc
  source/core/serial_solid.cc
  source/core/solid_base.cc
  tests/core/serial_solid_intersection_01.cc
  tests/core/solid_base_22.cc
  tests/core/solid_base_23.cc
  tests/core/solid_base_33.cc
  tests/core/solid_base_33_moving_particles.cc
  tests/core/solid_base_33_moving_triangulation.cc
Labels: enhancement, Lethe Hackathon 2023, ready for review

#801 Mesh controler
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  include/core/mesh_controller.h
  include/core/parameters.h
  include/solvers/navier_stokes_base.h
  source/core/CMakeLists.txt
  source/core/mesh_controller.cc
  source/core/parameters.cc
  source/solvers/navier_stokes_base.cc
  tests/core/mesh_controller_test.cc
  tests/core/mesh_controller_test.output
Labels: enhancement, Lethe Hackathon 2023, ready for review

#793 Cahn-Hilliard documentation
  doc/source/parameters/cfd/analytical_solution.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  doc/source/parameters/cfd/cahn_hilliard.rst
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/fem.rst
  doc/source/parameters/cfd/initial_conditions.rst
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  doc/source/parameters/cfd/multiphysics.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/cfd/post_processing.rst
  doc/source/parameters/cfd/source_term.rst
Labels: Lethe Hackathon 2023

#807 Reuse velocity solution
  applications_tests/gls_navier_stokes_2d/CMakeLists.txt
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart.output
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart.prm
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.averagevelocities
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.pvdhandler
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.simulationcontrol
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.triangulation
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.triangulation.info
  applications_tests/gls_navier_stokes_2d/cavity_ht_average_velocity_restart_files/restart.triangulation_fixed.data
  doc/source/parameters/cfd/multiphysics.rst
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Lethe Hackathon 2023

#812 Make usage of Ankerl map more widespread
  include/dem/data_containers.h
  source/dem/particle_particle_fine_search.cc
  tests/dem/find_full_cell_neighbors.cc
  tests/dem/find_full_cell_neighbors.output
  tests/dem/normal_force.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
  tests/dem/particle_wall_contact_pairs.cc
  tests/dem/particle_wall_fine_search.cc
  tests/dem/post_collision_velocity.cc
Labels: Lethe Hackathon 2023

#784 Superquadric shapes
  doc/source/parameters/sharp-immersed-boundary-solver/sharp-immersed-boundary-solver.rst
  include/core/shape.h
  source/core/parameters.cc
  source/core/shape.cc
  source/core/shape_parsing.cc
  tests/core/shape_primitives.cc
  tests/core/shape_primitives.output
Labels: Lethe Hackathon 2023

#813 Add VOF theory guide
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  doc/source/theory/multiphysics/images/vof.png
  doc/source/theory/multiphysics/multiphysics.rst
  doc/source/theory/multiphysics/vof.rst
  doc/source/theory/theory.rst
Labels: documentation, reviewed and ready to merge, Lethe Hackathon 2023

#817 Dem solid objet and ghost cell contact search
  source/dem/dem.cc
  source/dem/particle_wall_broad_search.cc
Labels: quick fix, ready for review

#796 Matrix-free Stokes prototypes
  prototypes/CMakeLists.txt
  prototypes/matrix_free_stokes/CMakeLists.txt
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
  prototypes/matrix_free_stokes/parameters.prm
Labels: reviewed and ready to merge

#818 Add material interaction class and surface tension model
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.prm
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.prm
  applications_tests/gls_navier_stokes_2d/gls_vof_static_droplet_surface_tension_force_with_tanh_filter.prm
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/rising-bubble/rising-bubble.prm
  examples/multiphysics/static-bubble/static-bubble.prm
  include/core/interface_property_model.h
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/core/surface_tension_model.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/physical_properties_manager.h
  include/solvers/simulation_parameters.h
  source/core/CMakeLists.txt
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/core/surface_tension_model.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/physical_properties_manager.cc
  tests/core/surface_tension_constant.cc
  tests/core/surface_tension_constant.output
  tests/solvers/physical_properties_manager_01.cc
  tests/solvers/physical_properties_manager_02.cc
  tests/solvers/physical_properties_manager_02.output
  tests/solvers/physical_properties_manager_03.cc
  tests/solvers/physical_properties_manager_03.output
  tests/solvers/restart_01.cc
Labels: reviewed and ready to merge, rebased

#821 Minor fixes to MG algorithms in Stokes prototypes
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
Labels: quick fix

#815 Isothermal compressible NS assembler
  applications_tests/gls_navier_stokes_2d/mms2d_isothermal_compressible_ns_gls.output
  applications_tests/gls_navier_stokes_2d/mms2d_isothermal_compressible_ns_gls.prm
  applications_tests/gls_navier_stokes_3d/mms3d_isothermal_compressible_ns_gls.output
  applications_tests/gls_navier_stokes_3d/mms3d_isothermal_compressible_ns_gls.prm
  doc/source/contributing.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/theory/fluid_dynamics/fem_formulation.rst
  doc/source/theory/fluid_dynamics/navier-stokes.rst
  doc/source/theory/fluid_dynamics/stabilization.rst
  doc/source/theory/multiphysics/vof.rst
  include/core/density_model.h
  include/solvers/isothermal_compressible_navier_stokes_assembler.h
  include/solvers/navier_stokes_assemblers.h
  include/solvers/navier_stokes_scratch_data.h
  source/solvers/CMakeLists.txt
  source/solvers/gls_navier_stokes.cc
  source/solvers/isothermal_compressible_navier_stokes_assembler.cc
  source/solvers/navier_stokes_assemblers.cc
  source/solvers/navier_stokes_scratch_data.cc
  tests/solvers/physical_properties_manager_03.cc
  tests/solvers/restart_01.cc
Labels: reviewed and ready to merge, rebased

#810 Add example fem reconstruction
  doc/source/examples/rpt/particle-fem-reconstruction/images/position_reconstruction_result.png
  doc/source/examples/rpt/particle-fem-reconstruction/images/syst-from-above.png
  doc/source/examples/rpt/particle-fem-reconstruction/particle-fem-reconstruction.rst
  doc/source/examples/rpt/rpt.rst
Labels: beginner's work, documentation, Lethe Hackathon 2023

#823 Fix link of example
  doc/source/examples/rpt/rpt.rst
Labels: documentation, quick fix
