Repository chaos-polymtl/lethe, pull requests merged in 2023-03, with the labels that each got.

#711 Add phase filter to the 2d dam-break VOF example
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/dam-break/images/time-series.png
  doc/source/examples/multiphysics/dam-break/images/xmax-t.png
  examples/multiphysics/dam-break/dam-break-2d.py
  examples/multiphysics/dam-break/dam-break-Martin-and-Moyce.prm
Labels: Lethe Hackathon 2023

#704 Mixing index postprocessing
  contrib/postprocessing/example.py
  contrib/postprocessing/lethe_pyvista_tools.py
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/images/mixing_indices_comparison.png
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/images/paraview_window_zoom_nnm.png
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/small-scale-rotating-drum-post-processing.rst
  doc/source/examples/incompressible-flow/2d-backward-facing-step/2d-backward-facing-step.rst
  examples/dem/small-scale-rotating-drum-postprocessing/example_small_rotating_drum.py
Labels: reviewed and ready to merge, Lethe Hackathon 2023, rebased

#719 Add check to ensure there is no Nan gradient for spheres
  source/core/shape.cc
Labels: ready for review

#720 Add disabling contacts of particles with negligible motion
  applications_tests/dem_3d/load_balancing_mobility_status.mpirun=2.output
  applications_tests/dem_3d/load_balancing_mobility_status.prm
  applications_tests/dem_3d/mobility_status.output
  applications_tests/dem_3d/mobility_status.prm
  doc/source/parameters/dem/model_parameters.rst
  include/core/parameters.h
  include/core/parameters_lagrangian.h
  include/dem/data_containers.h
  include/dem/dem.h
  include/dem/dem_container_manager.h
  include/dem/disable_contacts.h
  include/dem/explicit_euler_integrator.h
  include/dem/gear3_integrator.h
  include/dem/integrator.h
  include/dem/lagrangian_post_processing.h
  include/dem/particle_particle_broad_search.h
  include/dem/particle_point_line_broad_search.h
  include/dem/particle_wall_broad_search.h
  include/dem/velocity_verlet_integrator.h
  include/dem/visualization.h
  include/fem-dem/cfd_dem_coupling.h
  source/core/parameters.cc
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/dem_container_manager.cc
  source/dem/disable_contacts.cc
  source/dem/explicit_euler_integrator.cc
  source/dem/gear3_integrator.cc
  source/dem/insertion.cc
  source/dem/lagrangian_post_processing.cc
  source/dem/particle_particle_broad_search.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_point_line_broad_search.cc
  source/dem/particle_wall_broad_search.cc
  source/dem/velocity_verlet_integrator.cc
  source/dem/visualization.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: enhancement, ready for review
