Repository chaos-polymtl/lethe, pull requests merged in 2023-02, with the labels that each got.

#688 Add DEM direction parameters for insertion of particles
  applications_tests/dem_3d/insert_z-x-y.output
  applications_tests/dem_3d/insert_z-x-y.prm
  doc/source/parameters/dem/insertion_info.rst
  include/core/parameters_lagrangian.h
  include/dem/insertion.h
  source/core/parameters_lagrangian.cc
  source/dem/insertion.cc
  source/dem/non_uniform_insertion.cc
  source/dem/uniform_insertion.cc
  tests/dem/insertion_non_uniform.cc
  tests/dem/insertion_uniform.cc
  tests/dem/insertion_uniform.output
Labels: enhancement

#689 Implement VOF phase fraction filter
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.output
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.prm
  doc/source/parameters/cfd/volume_of_fluid.rst
  include/core/parameters_multiphysics.h
  include/solvers/vof.h
  include/solvers/vof_filter.h
  source/core/parameters_multiphysics.cc
  source/solvers/CMakeLists.txt
  source/solvers/vof.cc
  source/solvers/vof_filter.cc
Labels: reviewed and ready to merge

#690 Vof improve surface tension
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.prm
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.output
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.prm
  doc/source/examples/multiphysics/rising-bubble/images/bubble-rise-velocity.png
  doc/source/examples/multiphysics/rising-bubble/images/ymean-t.png
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/rising-bubble/rising-bubble.prm
  include/core/parameters_multiphysics.h
  include/solvers/vof.h
  source/core/parameters_multiphysics.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
Labels: reviewed and ready to merge

#692 Update documentation
  doc/source/installation/digital_alliance.rst
Labels: documentation

#694 Implement VOF phase fraction filter - physical properties calculation
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.output
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/navier_stokes_scratch_data.h
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_scratch_data.cc
  source/solvers/navier_stokes_scratch_data.cc
Labels: ready for review

#700 Vof improve initial condition
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.output
  applications_tests/gls_navier_stokes_2d/gls_vof_heat-transfer_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_heated-walls.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.output
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.prm
  doc/source/parameters/cfd/initial_conditions.rst
  include/solvers/initial_conditions.h
  include/solvers/vof.h
  source/solvers/gls_navier_stokes.cc
  source/solvers/vof.cc
Labels: ready for review

#696 Improve rising bubble
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_static_droplet_surface_tension_force.output
  applications_tests/gls_navier_stokes_2d/gls_vof_heat-transfer_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_initial_refine.output
  applications_tests/gls_navier_stokes_2d/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting_mesh-adapt.output
  doc/source/examples/multiphysics/rising-bubble/images/bubble-rise-velocity.png
  doc/source/examples/multiphysics/rising-bubble/images/bubble.png
  doc/source/examples/multiphysics/rising-bubble/images/ymean-t.png
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/parameters/cfd/post_processing.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/rising-bubble/rising-bubble.prm
  examples/multiphysics/rising-bubble/rising-bubble.py
  include/core/parameters.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof.cc
Labels: ready for review

#686 Add writting and array modifying features to Lethe_pyvista_tools
  contrib/postprocessing/Lethe_pyvista_tools.py
  contrib/postprocessing/README.md
  contrib/postprocessing/example.py
  contrib/postprocessing/lethe_pyvista_tools.py
  doc/source/examples/dem/dem.rst
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/images/paraview_window.png
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/images/paraview_window_zoom.png
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/images/pyvista_window.png
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/small-scale-rotating-drum-post-processing.rst
  examples/dem/3d-rectangular-hopper/hopper_post_processing.py
  examples/dem/3d-rotating-drum-post-processing/rotating-drum-with-post-processing.prm
  examples/dem/small-scale-rotating-drum-postprocessing/example_small_rotating_drum.py
Labels: enhancement, documentation, reviewed and ready to merge, rebased

#709 Add the Mixing-ANN paper to the publications
  doc/source/publications.rst
Labels: documentation
