Repository chaos-polymtl/lethe, pull requests merged in 2023-06, with the labels that each got.

#763 Fix QCM for particles with PBC
  applications_tests/cfd_dem_coupling_3d/CMakeLists.txt
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm.output
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm.prm
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.particles
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.pvdhandler
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.simulationcontrol
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.triangulation
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.triangulation.info
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.triangulation_fixed.data
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/dem.triangulation_variable.data
  applications_tests/cfd_dem_coupling_3d/periodic_particles_qcm_files/particles_list.prm
  applications_tests/gls_vans_3d/beetstra_packed_bed.prm
  applications_tests/gls_vans_3d/dallavalle_packed_bed.prm
  applications_tests/gls_vans_3d/difelice_packed_bed.prm
  applications_tests/gls_vans_3d/gidaspow_packed_bed.prm
  applications_tests/gls_vans_3d/kochhill_packed_bed.prm
  applications_tests/gls_vans_3d/pcm_packed_bed.prm
  applications_tests/gls_vans_3d/qcm_packed_bed.prm
  applications_tests/gls_vans_3d/rong_packed_bed.prm
  applications_tests/gls_vans_3d/spm_packed_bed.prm
  applications_tests/periodic_boundary_collisions.output
  doc/source/theory/unresolved_cfd-dem/unresolved_cfd-dem.rst
  include/core/lethe_grid_tools.h
  include/dem/periodic_boundaries_manipulator.h
  include/fem-dem/gls_vans.h
  source/core/lethe_grid_tools.cc
  source/dem/dem.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/gls_vans.cc
  source/fem-dem/parameters_cfd_dem.cc
Labels: bug, reviewed and ready to merge

#773 Use box refinement in GLS and GD Navier-Stokes solvers
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
Labels: ready for review

#775 Extrapolate ib refinement
  doc/source/parameters/sharp-immersed-boundary-solver/sharp-immersed-boundary-solver.rst
  include/core/parameters.h
  include/fem-dem/gls_sharp_navier_stokes.h
  source/core/parameters.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
Labels: bug, enhancement

#776 Fix Rayleigh critical time step equation
  applications_tests/dem_2d/circle_restart.output
  applications_tests/dem_2d/circle_with_floating_walls.mpirun=1.output
  applications_tests/dem_2d/insert_list_2d.mpirun=2.output
  applications_tests/dem_2d/insert_list_2d.output
  applications_tests/dem_2d/packing_in_circle.mpirun=1.output
  applications_tests/dem_2d/packing_in_circle.mpirun=2.output
  applications_tests/dem_2d/packing_in_square.mpirun=1.output
  applications_tests/dem_2d/packing_in_square.mpirun=2.output
  applications_tests/dem_2d/rotating_in_circle.output
  applications_tests/dem_2d/two_types_packing_in_circle.output
  applications_tests/dem_3d/ball_with_floating_walls.output
  applications_tests/dem_3d/box_grid_rotation.output
  applications_tests/dem_3d/box_grid_slide.output
  applications_tests/dem_3d/floating_mesh.output
  applications_tests/dem_3d/force_boundary_box.output
  applications_tests/dem_3d/initial_value_insertion.output
  applications_tests/dem_3d/insert_list_3d.output
  applications_tests/dem_3d/insert_periodic_boundary_gmsh.output
  applications_tests/dem_3d/insert_z-x-y.output
  applications_tests/dem_3d/load_balancing_mobility_status.mpirun=2.output
  applications_tests/dem_3d/load_balancing_solid_object.mpirun=2.output
  applications_tests/dem_3d/mobility_status.output
  applications_tests/dem_3d/moving_float.output
  applications_tests/dem_3d/outlet_boundary.output
  applications_tests/dem_3d/packing_in_ball.mpirun=1.output
  applications_tests/dem_3d/packing_in_ball.mpirun=2.output
  applications_tests/dem_3d/packing_in_ball_dynamic_contact.output
  applications_tests/dem_3d/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/dem_3d/packing_in_box.mpirun=1.output
  applications_tests/dem_3d/packing_in_box.mpirun=2.output
  applications_tests/dem_3d/packing_in_cylinder.output
  applications_tests/dem_3d/periodic_boundary_box.output
  applications_tests/dem_3d/periodic_boundary_collisions.mpirun=1.output
  applications_tests/dem_3d/periodic_boundary_collisions.mpirun=2.output
  applications_tests/dem_3d/periodic_boundary_load_balancing.mpirun=2.output
  applications_tests/dem_3d/sliding_in_box.output
  applications_tests/dem_3d/sliding_restart.output
  applications_tests/dem_3d/torque_boundary_box.output
  source/dem/input_parameter_inspection.cc
Labels: quick fix, ready for review

#782 Reduce RAM on post-processing with lethe_pyvista_tools
  contrib/postprocessing/example.py
  contrib/postprocessing/lethe_pyvista_tools.py
  doc/source/examples/dem/small-scale-rotating-drum-post-processing/small-scale-rotating-drum-post-processing.rst
  examples/dem/3d-bouncing-particle/bouncing_particle_post_processing.py
  examples/dem/3d-rectangular-hopper/hopper_post_processing.py
  examples/dem/small-scale-rotating-drum-postprocessing/example_small_rotating_drum.py
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_post_processing.py
Labels: reviewed and ready to merge

#779 Add the example and the corresponding rst file
  doc/source/examples/sharp-immersed-boundary-solver/resolved-cfd-dem.rst
  doc/source/examples/sharp-immersed-boundary-solver/sedimentation-64-particles/sedimentation-64-particles.rst
  examples/sharp-immersed-boundary-solver/sedimentation-64-particles/particles.input
  examples/sharp-immersed-boundary-solver/sedimentation-64-particles/sedimentation-64-particles.prm
Labels: documentation

#786 Fix issue when particles cross PBC
  source/dem/dem.cc
  source/dem/find_contact_detection_step.cc
Labels: quick fix, ready for review
