Repository chaos-polymtl/lethe, pull requests merged in 2023-05, with the labels that each got.

#742 Vof add static bubble example
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/static-bubble/images/L2Error.png
  doc/source/examples/multiphysics/static-bubble/images/mesh-convergence-study-order.png
  doc/source/examples/multiphysics/static-bubble/images/mesh-convergence-study-time.png
  doc/source/examples/multiphysics/static-bubble/images/static-bubble-t0p0.png
  doc/source/examples/multiphysics/static-bubble/images/static-bubble-t0p1.png
  doc/source/examples/multiphysics/static-bubble/images/static-bubble-t1p5.png
  doc/source/examples/multiphysics/static-bubble/images/static-bubble-t3p0.png
  doc/source/examples/multiphysics/static-bubble/images/static-bubble.png
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/examples/multiphysics/vof.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/static-bubble/postprocess.gnu
  examples/multiphysics/static-bubble/static-bubble.prm
Labels: reviewed and ready to merge

#747 Fix singular cells bug and pressure scaling
  applications_tests/gls_sharp_navier_stokes_3d/almost_blocked_channels.output
  applications_tests/gls_sharp_navier_stokes_3d/almost_blocked_channels.prm
  applications_tests/gls_sharp_navier_stokes_3d/cavatappi_composite_test.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cone_deathstar.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_cuthollowsphere.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_ellipsoid_rectangle.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_rbf.output
  applications_tests/gls_sharp_navier_stokes_3d/flow_around_torus.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pp_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_contact_test.output
  applications_tests/gls_sharp_navier_stokes_3d/pw_lubrication_test.output
  applications_tests/gls_sharp_navier_stokes_3d/rbf_sphere_mms_adaptive.output
  applications_tests/gls_sharp_navier_stokes_3d/sphere_mms_pressure_scaling.output
  applications_tests/gls_sharp_navier_stokes_3d/sphere_mms_pressure_scaling.prm
  applications_tests/gls_sharp_navier_stokes_3d/tube_shape_test.output
  doc/source/parameters/cfd/stabilization.rst
  include/core/parameters.h
  include/core/physics_solver.h
  include/fem-dem/gls_sharp_navier_stokes.h
  include/solvers/auxiliary_physics.h
  include/solvers/navier_stokes_base.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/physical_properties_manager.h
  source/core/parameters.cc
  source/core/shape.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/fem-dem/gls_vans.cc
  source/fem-dem/vans_assemblers.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_assemblers.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/physical_properties_manager.cc
  source/solvers/tracer_scratch_data.cc
  tests/solvers/flow_control_01.cc
Labels: reviewed and ready to merge

#754 Add clang-format instructions in doc
  .gitignore
  doc/source/contributing.rst
Labels: documentation, quick fix

#752 Matrix-free advection-diffusion prototype
  prototypes/CMakeLists.txt
  prototypes/matrix_based_advection_diffusion/CMakeLists.txt
  prototypes/matrix_based_advection_diffusion/matrix_based_advection_diffusion.cc
  prototypes/matrix_based_advection_diffusion/parameters.prm
  prototypes/matrix_free_advection_diffusion/CMakeLists.txt
  prototypes/matrix_free_advection_diffusion/matrix_free_advection_diffusion.cc
  prototypes/matrix_free_advection_diffusion/parameters.prm
Labels: reviewed and ready to merge

#753 Vof update 3D dam break with obstacle example
  doc/source/examples/multiphysics/3d-dam-break/3d-dam-break.rst
  doc/source/examples/multiphysics/3d-dam-break/images/H1_to_H4_evolution.png
  examples/multiphysics/3d-dam-break/3d-dam-break.prm
Labels: ready for review

#760 Correct stabilization for VOF
  applications_tests/gls_navier_stokes_2d/gls_droplet_marangoni_effect.output
  applications_tests/gls_navier_stokes_2d/gls_vof_ht_adapt-dissipation.output
  applications_tests/gls_navier_stokes_2d/gls_vof_peeling.output
  applications_tests/gls_navier_stokes_2d/gls_vof_tanh_filter.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting-inverted.output
  applications_tests/gls_navier_stokes_2d/gls_vof_wetting_mesh-adapt.output
  include/core/inexact_newton_non_linear_solver.h
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/vof_assemblers.cc
Labels: ready for review

#759 Using cache with composite shapes
  applications_tests/gls_sharp_navier_stokes_3d/cavatappi_composite_test.output
  include/core/shape.h
  source/core/parameters.cc
  source/core/shape.cc
  tests/core/shape_composites.output
Labels: ready for review
