Repository chaos-polymtl/lethe, pull requests merged in 2023-12, with the labels that each got.

#941 Dem refactor distribution
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/dem_solver_parameters.h
  include/dem/distributions.h
  include/dem/find_maximum_particle_size.h
  include/dem/input_parameter_inspection.h
  include/dem/insertion.h
  include/dem/list_insertion.h
  include/dem/plane_insertion.h
  include/dem/volume_insertion.h
  include/fem-dem/cfd_dem_coupling.h
  include/fem-dem/ib_particles_dem.h
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/distributions.cc
  source/dem/find_maximum_particle_size.cc
  source/dem/input_parameter_inspection.cc
  source/dem/insertion.cc
  source/dem/list_insertion.cc
  source/dem/plane_insertion.cc
  source/dem/volume_insertion.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/insertion_plane.cc
  tests/dem/insertion_volume_1.cc
  tests/dem/insertion_volume_2.cc
Labels: reviewed and ready to merge, refactor

#949 [WIP] Add doxygen documentation
  .github/workflows/doc-github-pages.yml
  CMakeLists.txt
  doc/aggregate/index.html
  doc/doxygen/CMakeLists.txt
  doc/doxygen/DoxygenLayout.xml
  doc/doxygen/doxygen-config-file
  doc/doxygen/logo.png
  doc/doxygen/stylesheet.css
Labels: Lethe Hackathon - Fall 2023

#950 Update readme and doc
  README.md
Labels: Lethe Hackathon - Fall 2023

#944 Add composite example
  doc/source/examples/sharp-immersed-boundary/geometry-definition.rst
  doc/source/examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/images/inclined-impeller_flow_1_sec.png
  doc/source/examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/images/inclined_impeller.png
  doc/source/examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/inclined-3d-composite-mixer-with-pbt-impeller.rst
  doc/source/examples/sharp-immersed-boundary/incompressible-flow.rst
  doc/source/examples/sharp-immersed-boundary/sharp-immersed-boundary.rst
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/both_wing.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/full_plane.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/left_wing.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/plane_with_engine.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/plane_without_engine.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/images/wings_and_fuselage.png
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/simple-plane-model-from-composite.rst
  doc/source/parameters/sharp-immersed-boundary/sharp-immersed-boundary.rst
  examples/sharp-immersed-boundary/incline-3d-composite-mixer-with-pbt-impeller/angle_calculator.py
  examples/sharp-immersed-boundary/incline-3d-composite-mixer-with-pbt-impeller/impeller.composite
  examples/sharp-immersed-boundary/incline-3d-composite-mixer-with-pbt-impeller/mixer.prm
  examples/sharp-immersed-boundary/simple-plane-model-from-composite/plane.composite
  examples/sharp-immersed-boundary/simple-plane-model-from-composite/plane.prm
  source/core/shape_parsing.cc
Labels: documentation

#951 Documentation clean up for doxygen
  include/core/boundary_conditions.h
  include/core/density_model.h
  include/core/dimensionality.h
  include/core/interface_property_model.h
  include/core/mobility_cahn_hilliard_model.h
  include/core/newton_non_linear_solver.h
  include/core/periodic_hills_grid.h
  include/core/physical_property_model.h
  include/core/rheological_model.h
  include/core/shape.h
  include/core/specific_heat_model.h
  include/core/surface_tension_model.h
  include/core/thermal_conductivity_model.h
  include/core/thermal_expansion_model.h
  include/core/tracer_diffusivity_model.h
  include/fem-dem/vans_assemblers.h
  include/solvers/cahn_hilliard_assemblers.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/copy_data.h
  include/solvers/flow_control.h
  include/solvers/heat_transfer_assemblers.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/isothermal_compressible_navier_stokes_assembler.h
  include/solvers/isothermal_compressible_navier_stokes_vof_assembler.h
  include/solvers/navier_stokes_assemblers.h
  include/solvers/navier_stokes_cahn_hilliard_assemblers.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/physical_properties_manager.h
  include/solvers/postprocessing_velocities.h
  include/solvers/tracer_assemblers.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof_assemblers.h
  include/solvers/vof_filter.h
  include/solvers/vof_scratch_data.h
Labels: Lethe Hackathon - Fall 2023

#955 Doxygen main page diagram
  doc/doxygen/doxygen-config-file
  doc/doxygen/main.h
Labels: documentation, Lethe Hackathon - Fall 2023, ready for review

#937 Add evaporative heat and momentum fluxes
  applications_tests/lethe-fluid/evaporation_plane_constant_mass_flux.output
  applications_tests/lethe-fluid/evaporation_plane_constant_mass_flux.prm
  applications_tests/lethe-fluid/evaporation_plane_temperature_dependent_mass_flux.output
  applications_tests/lethe-fluid/evaporation_plane_temperature_dependent_mass_flux.prm
  applications_tests/lethe-fluid/evaporation_static_droplet_constant_mass_flux.output
  applications_tests/lethe-fluid/evaporation_static_droplet_constant_mass_flux.prm
  include/core/evaporation_model.h
  include/core/parameters.h
  include/solvers/heat_transfer_assemblers.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/simulation_parameters.h
  source/core/CMakeLists.txt
  source/core/evaporation_model.cc
  source/core/parameters.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: reviewed and ready to merge

#952 Parameter file tester for examples and CI step
  .github/workflows/main_parameter_files.yml
  README.md
  applications/CMakeLists.txt
  applications/lethe-parameter-check/CMakeLists.txt
  applications/lethe-parameter-check/lethe_parameter_check.cc
  contrib/utilities/check_parameter_files_in_examples.sh
  examples/dem/3d-bouncing-particle/bouncing_particle_case_generator.py
  examples/dem/3d-bouncing-particle/bouncing_particle_original.tpl
  examples/dem/3d-oblique-wall-impact/oblique_wall_impact_case_generator.py
  examples/dem/3d-oblique-wall-impact/oblique_wall_impact_template.tpl
  examples/incompressible-flow/3d-ribbon-mixer-srf/Np_vs_Re/lethe_case_generator.py
  examples/incompressible-flow/3d-ribbon-mixer-srf/Np_vs_Re/ribbon-gls.tpl
  examples/multiphysics/3d-dam-break/3d-dam-break.prm
  examples/multiphysics/cahn_hilliard/chns.prm
  examples/multiphysics/capillary-wave/capillary-wave-time-step-sensitivity.sh
  examples/multiphysics/capillary-wave/capillary-wave.tpl
  examples/multiphysics/dam-break/dam-break-Martin-and-Moyce.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-constant-sharpening.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0002/sloshing-in-rectangular-tank_Re0002.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0020/sloshing-in-rectangular-tank_Re0020.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_0200/sloshing-in-rectangular-tank_Re0200.prm
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_2000/sloshing-in-rectangular-tank_Re2000.prm
  examples/sharp-immersed-boundary/incline-3d-composite-mixer-with-pbt-impeller/mixer.prm
  examples/sharp-immersed-boundary/simple-plane-model-from-composite/plane.prm
  examples/unresolved-cfd-dem/boycott-effect/boycott-effect.prm
  examples/unresolved-cfd-dem/boycott-effect/particle-generator.prm
  examples/unresolved-cfd-dem/cylindrical-packed-bed/packing-in-cylinder-generator.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/dem-packing-in-fluidized-bed-generator.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-bed/dem-packing-in-spouted-bed-generator.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/dem-packing-in-lsfb-generator.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.prm
Labels: reviewed and ready to merge, Lethe Hackathon - Fall 2023

#958 Fix documentation hyperlinks
  .github/workflows/doc-github-pages.yml
  README.md
  doc/aggregate/index.html
  doc/doxygen/main.h
  doc/source/examples/dem/dem.rst
  doc/source/examples/incompressible-flow/2d-backward-facing-step/2d-backward-facing-step.rst
  doc/source/examples/incompressible-flow/2d-naca0012-low-reynolds/2d-naca0012-low-reynolds.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/2d-transient-flow-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/laser-heating/laser-heating.rst
  doc/source/examples/multiphysics/laser-melt-pool/laser-melt-pool.rst
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/examples/rpt/rpt.rst
  doc/source/examples/sharp-immersed-boundary/sharp-immersed-boundary.rst
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  doc/source/parameters/cfd/multiphysics.rst
  doc/source/parameters/dem/floating_mesh.rst
  doc/source/parameters/dem/mesh.rst
  doc/source/parameters/dem/simulation_control.rst
  doc/source/theory/unresolved_cfd-dem/unresolved_cfd-dem.rst
Labels: documentation, Lethe Hackathon - Fall 2023

#953 Add heat flux postprocessor
  include/solvers/heat_transfer.h
  include/solvers/postprocessors.h
  source/solvers/heat_transfer.cc
Labels: enhancement, Lethe Hackathon - Fall 2023

#959 Add checkpoint to DEM solid objects
  CHANGELOG.md
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/moving_receptacle_files/moving_receptacle.prm
  applications_tests/lethe-particles/moving_receptacle_files/restart.particles
  applications_tests/lethe-particles/moving_receptacle_files/restart.pvdhandler
  applications_tests/lethe-particles/moving_receptacle_files/restart.simulationcontrol
  applications_tests/lethe-particles/moving_receptacle_files/restart.solid_object.00.displacement
  applications_tests/lethe-particles/moving_receptacle_files/restart.solid_object.00.dof
  applications_tests/lethe-particles/moving_receptacle_files/restart.solid_object.00.pvdhandler
  applications_tests/lethe-particles/moving_receptacle_files/restart.triangulation
  applications_tests/lethe-particles/moving_receptacle_files/restart.triangulation.info
  applications_tests/lethe-particles/moving_receptacle_files/restart.triangulation_fixed.data
  applications_tests/lethe-particles/moving_receptacle_files/restart.triangulation_variable.data
  applications_tests/lethe-particles/moving_receptacle_files/square.geo
  applications_tests/lethe-particles/moving_receptacle_files/square.msh
  applications_tests/lethe-particles/restart_moving_receptacle.output
  applications_tests/lethe-particles/restart_moving_receptacle.prm
  include/core/serial_solid.h
  include/dem/read_checkpoint.h
  include/dem/write_checkpoint.h
  source/core/serial_solid.cc
  source/dem/dem.cc
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
Labels: reviewed and ready to merge, Lethe Hackathon - Fall 2023

#963 Installation instructions linux
  doc/source/index.rst
  doc/source/installation/regular_installation.rst
Labels: Lethe Hackathon - Fall 2023

#954 Dem histogram distribution
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  include/core/parameters.h
  include/core/parameters_lagrangian.h
  include/dem/distributions.h
  source/core/parameters.cc
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/distributions.cc
Labels: enhancement, beginner's work, documentation, reviewed and ready to merge, Lethe Hackathon - Fall 2023

#964 Checkpointing the insertion object.
  CHANGELOG.md
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/circle_restart.output
  applications_tests/lethe-particles/circle_restart.prm
  applications_tests/lethe-particles/circle_restart_files/circle_restart.insertion_object
  applications_tests/lethe-particles/circle_restart_files/circle_restart.triangulation
  applications_tests/lethe-particles/circle_restart_files/circle_restart.triangulation.info
  applications_tests/lethe-particles/circle_restart_files/circle_restart.triangulation_variable.data
  applications_tests/lethe-particles/moving_receptacle_files/restart.insertion_object
  applications_tests/lethe-particles/restart_moving_receptacle.prm
  applications_tests/lethe-particles/sliding_restart.prm
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart.insertion_object
  include/dem/insertion.h
  include/dem/list_insertion.h
  include/dem/plane_insertion.h
  include/dem/read_checkpoint.h
  include/dem/volume_insertion.h
  include/dem/write_checkpoint.h
  source/dem/dem.cc
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
Labels: enhancement, reviewed and ready to merge, Lethe Hackathon - Fall 2023

#968 Add lpbf example
  examples/multiphysics/laser-powder-bed-fusion/benchmark.prm
  include/core/evaporation_model.h
  include/core/parameters.h
  source/core/parameters.cc
Labels: reviewed and ready to merge

#972 Quick fix
  tests/dem/distribution_custom.cc
  tests/dem/distribution_normal.cc
  tests/dem/insertion_plane.cc
  tests/dem/insertion_volume_1.cc
  tests/dem/insertion_volume_2.cc
Labels: quick fix

#973 Fix volume fraction and seed in parallel to prevent artificial structure
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
Labels: quick fix, ready for review
