Repository chaos-polymtl/lethe, pull requests merged in 2023-10, with the labels that each got.

#900 Add matrix-free Navier-Stokes SUPG/PSPG transient operator
  applications_tests/lethe-fluid-matrix-free/tgv_fe1_ilu.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/tgv_fe1_ilu.prm
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: reviewed and ready to merge

#904 Surface tension model for phase change
  applications_tests/lethe-fluid/liquid_thermocapillary_droplet.output
  applications_tests/lethe-fluid/liquid_thermocapillary_droplet.prm
  applications_tests/lethe-fluid/solid_thermocapillary_droplet.output
  applications_tests/lethe-fluid/solid_thermocapillary_droplet.prm
  doc/source/parameters/cfd/physical_properties.rst
  include/core/parameters.h
  include/core/phase_change.h
  include/core/surface_tension_model.h
  include/solvers/simulation_parameters.h
  source/core/parameters.cc
  source/core/surface_tension_model.cc
  source/core/utilities.cc
Labels: ready for review

#905 Update installation with apt
  doc/source/installation/regular_installation.rst
  doc/source/installation/windows_wsl.rst
Labels: documentation, ready for review, needs one more review

#906 Add viscous and ramp initial conditions for MF
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  include/solvers/physical_properties_manager.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/physical_properties_manager.cc
Labels: reviewed and ready to merge

#907 Add ILU preconditioner for MG coarse grid solvers
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.prm
  doc/source/parameters/cfd/linear_solver_control.rst
  include/core/parameters.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
Labels: ready for review

#908 Constraints in Multigrid preconditioners
  CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.with_dealii.geq.9.6.output
  doc/source/installation/regular_installation.rst
  source/solvers/mf_navier_stokes.cc
Labels: ready for review

#911 Greater number of solid objects + Case generator for LPBF + Post processing for LPBF
  include/core/solid_objects_parameters.h
Labels: quick fix, ready for review, Post-processing

#914 Improve output of multigrid information
  doc/source/parameters/cfd/linear_solver_control.rst
  include/solvers/mf_navier_stokes.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
Labels: ready for review

#917 Use compute element size function in MF operators
  source/solvers/mf_navier_stokes_operators.cc
Labels: reviewed and ready to merge
