Repository chaos-polymtl/lethe, pull requests merged in 2023-11, with the labels that each got.

#920 Dem rotating boundary parsing
  CHANGELOG.md
  applications_tests/lethe-particles/perpendicular_rotation_to_wall.prm
  applications_tests/lethe-particles/pp_jkr_equilibrium.prm
  applications_tests/lethe-particles/pw_jkr_equilibrium.prm
  applications_tests/lethe-particles/rotating_in_ball.prm
  applications_tests/lethe-particles/rotating_in_circle.prm
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/small-scale-rotating-drum/small-scale-rotating-drum.rst
  doc/source/parameters/dem/boundary_conditions.rst
  examples/dem/3d-bouncing-particle/bouncing_particle_original.prm
  examples/dem/3d-rotating-drum-post-processing/rotating-drum-with-post-processing.prm
  examples/dem/3d-rotating-drum/load-rotating-drum.prm
  examples/dem/3d-rotating-drum/rotating-drum.prm
  examples/dem/3d-small-scale-rotating-drum/small-rotating-drum-dem.prm
  performance_analyses/dem/short_packing_10k_particles/time_case.sh
  source/core/parameters_lagrangian.cc
  source/dem/particle_wall_contact_force.cc
Labels: enhancement, reviewed and ready to merge, quick fix

#921 Core: entry string to tensor function
  include/core/parameters.h
  source/core/parameters.cc
  source/core/parameters_lagrangian.cc
Labels: maintenance, ready for review, refactor

#922 add new reference for high order moving IB
  doc/source/publications.rst
  doc/source/referencing.rst
Labels: documentation

#925 Guide on how to visualize huge data files in Paraview
  doc/source/tools/postprocessing/postprocessing_paraview.rst
  doc/source/tools/postprocessing/postprocessing_pyvista.rst
  doc/source/tools/tools.rst
Labels: ready for review

#929 Update residual to stop steady bdf in lethe-fluid-matrix-free
  source/solvers/mf_navier_stokes.cc
Labels: bug, reviewed and ready to merge, quick fix

#927 Capillary wave example
  doc/source/examples/multiphysics/capillary-wave/capillary-wave.rst
  doc/source/examples/multiphysics/capillary-wave/images/TSM_comparison_figure.png
  doc/source/examples/multiphysics/capillary-wave/images/TSM_comparison_figure_ref-6.png
  doc/source/examples/multiphysics/capillary-wave/images/figure-TSM-0_95.png
  doc/source/examples/multiphysics/capillary-wave/images/initial-state.svg
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/examples/multiphysics/static-bubble/images/mesh-convergence-study-order.png
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/examples/multiphysics/vof.rst
  doc/source/examples/sharp-immersed-boundary/sharp-immersed-boundary.rst
  examples/multiphysics/capillary-wave/capillary-wave-TSM-0_95.prm
  examples/multiphysics/capillary-wave/capillary-wave-calculation.py
  examples/multiphysics/capillary-wave/capillary-wave-combined.py
  examples/multiphysics/capillary-wave/capillary-wave-postprocess.py
  examples/multiphysics/capillary-wave/capillary-wave-prosperetti-solution.py
  examples/multiphysics/capillary-wave/capillary-wave-time-step-sensitivity-postprocess.sh
  examples/multiphysics/capillary-wave/capillary-wave-time-step-sensitivity.sh
  examples/multiphysics/capillary-wave/capillary-wave.prm
  examples/multiphysics/capillary-wave/capillaryWaveData_rho_1_nu_5e-6_prosperetti.csv
Labels: documentation, reviewed and ready to merge, rebased

#931 Fixing a stability problem with the JKR model
  include/dem/particle_particle_contact_force.h
  source/dem/particle_wall_jkr_force.cc
Labels: quick fix, ready for review

#930 Dem insertion distribution object
  include/dem/distributions.h
  include/dem/insertion.h
  include/dem/plane_insertion.h
  include/dem/volume_insertion.h
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/distributions.cc
  source/dem/insertion.cc
  source/dem/list_insertion.cc
  source/dem/plane_insertion.cc
  source/dem/volume_insertion.cc
  tests/dem/insertion_volume_1.cc
  tests/dem/insertion_volume_1.output
  tests/dem/insertion_volume_2.cc
  tests/dem/insertion_volume_2.output
Labels: ready for review, refactor

#933 Dem fixing plane insertion distribution
  CHANGELOG.md
  include/dem/insertion.h
  include/dem/plane_insertion.h
  source/dem/insertion.cc
  source/dem/list_insertion.cc
  source/dem/plane_insertion.cc
  source/dem/volume_insertion.cc
  tests/dem/insertion_plane.cc
Labels: reviewed and ready to merge, quick fix

#934 Fixed executable name in ribbon example
  examples/incompressible-flow/3d-ribbon-mixer-srf/Np_vs_Re/template/launch-mixer.sh
Labels: reviewed and ready to merge

#935 Minor fix to doc
  doc/source/parameters/cfd/timer.rst
Labels: documentation, quick fix

#940 Remove avg dia + fix documentation
  CHANGELOG.md
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  source/core/parameters_lagrangian.cc
Labels: reviewed and ready to merge

#938 Checkpoint missing tables
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/cavity_ht_average_velocity_restart_files/temperature_statistics.checkpoint
  applications_tests/lethe-fluid/mms-transient-conduction-restart_files/L2Error_FD.checkpoint
  applications_tests/lethe-fluid/mms-transient-conduction-restart_files/L2Error_HT.checkpoint
  applications_tests/lethe-fluid/mms-transient-conduction-restart_files/restart.triangulation_fixed.data
  applications_tests/lethe-fluid/mms-transient-conduction-restart_gls.output
  applications_tests/lethe-fluid/mms-transient-conduction-restart_gls.prm
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1.output
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1.prm
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1/L2Error_FD.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1/enstrophy.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1/kinetic_energy.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart_gls_bdf1/restart.triangulation_fixed.data
  doc/source/parameters/cfd/restart.rst
  include/core/utilities.h
  source/solvers/cahn_hilliard.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: maintenance, reviewed and ready to merge, rebased

#943 Fix compilation of prototypes
  prototypes/chorin_navier_stokes/chorin_navier_stokes.cc
  prototypes/direct_gls_navier_stokes/boundaryconditions.h
  prototypes/direct_gls_navier_stokes/exactsolutions.h
  prototypes/direct_gls_navier_stokes/forcingfunctions.h
  prototypes/direct_steady_navier_stokes/boundaryconditions.h
  prototypes/direct_steady_navier_stokes/exactsolutions.h
  prototypes/direct_steady_navier_stokes/forcingfunctions.h
Labels: maintenance, quick fix
