Repository chaos-polymtl/lethe, pull requests merged in 2024-01, with the labels that each got.

#976 Documentation errors and small change to the custom distribution
  doc/source/parameters/dem/insertion_info.rst
  source/dem/distributions.cc
Labels: quick fix

#985 Update index page mobile format
  README.md
  doc/aggregate/index.html
  doc/aggregate/style.css
  doc/source/index.rst
Labels: documentation, reviewed and ready to merge, quick fix

#986 Dem output solid object option
  doc/source/parameters/dem/floating_mesh.rst
  doc/source/parameters/dem/simulation_control.rst
  include/core/serial_solid.h
  include/core/solid_objects_parameters.h
  source/core/serial_solid.cc
Labels: reviewed and ready to merge, quick fix

#988 Fix heat flux postprocessor material_id processing
  include/solvers/postprocessors.h
  source/solvers/heat_transfer.cc
Labels: quick fix, ready for review, Post-processing

#989 Quick fix
  contrib/postprocessing/lethe_pyvista_tools/__init__.py
  contrib/postprocessing/lethe_pyvista_tools/_write_df_to_vtu.py
Labels: reviewed and ready to merge, quick fix

#993 Automate padding string length
  contrib/postprocessing/lethe_pyvista_tools/__init__.py
  contrib/postprocessing/lethe_pyvista_tools/_write_df_to_vtu.py
Labels: quick fix, needs one more review, Post-processing

#990 Add darcy penalization in vof
  applications_tests/lethe-fluid/vof_phase_change_darcy.output
  applications_tests/lethe-fluid/vof_phase_change_darcy.prm
  doc/source/parameters/cfd/laser_heat_source.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/parameters/cfd/velocity_source.rst
  include/solvers/navier_stokes_assemblers.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/physical_properties_manager.h
  source/core/parameters.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/physical_properties_manager.cc
Labels: enhancement, reviewed and ready to merge

#994 Add temperature extrapolation
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/vof_scratch_data.h
  source/fem-dem/gls_vans.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
Labels: reviewed and ready to merge, ready for review

#997 Add uniform laser distribution for 1D lpbf problems
  applications_tests/lethe-fluid/evaporation_static_droplet_constant_mass_flux.output
  applications_tests/lethe-fluid/heat_transfer_vof_interface_gaussian_laser.output
  applications_tests/lethe-fluid/heat_transfer_vof_interface_gaussian_laser.prm
  applications_tests/lethe-fluid/heat_transfer_vof_interface_uniform_laser.output
  applications_tests/lethe-fluid/heat_transfer_vof_interface_uniform_laser.prm
  doc/source/parameters/cfd/laser_heat_source.rst
  examples/multiphysics/laser-powder-bed-fusion/benchmark.prm
  include/core/evaporation_model.h
  include/core/parameters.h
  include/solvers/heat_transfer_assemblers.h
  include/solvers/simulation_parameters.h
  source/core/parameters.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: reviewed and ready to merge

#999 Add scaling factor for 2D gaussian laser model
  applications_tests/lethe-fluid/heat_transfer_vof_interface_gaussian_laser.output
  doc/source/parameters/cfd/laser_heat_source.rst
  source/core/parameters.cc
  source/solvers/heat_transfer_assemblers.cc
Labels: reviewed and ready to merge

#998 Fix kelly estimator in parallel for deal.II vectors
  applications_tests/lethe-fluid-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_structured.msh
  source/solvers/navier_stokes_base.cc
Labels: reviewed and ready to merge

#1008 Remove hanging node constraints call for LSMG
  source/solvers/mf_navier_stokes.cc
Labels: bug, reviewed and ready to merge, quick fix

#1007 Fix read checkpoint for the matrix-free application
  applications_tests/lethe-fluid-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.prm
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/L2Error_FD.checkpoint
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/enstrophy.checkpoint
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/kinetic_energy.checkpoint
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/restart.pvdhandler
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/restart.simulationcontrol
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/restart.triangulation
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/restart.triangulation.info
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1/restart.triangulation_fixed.data
  source/solvers/navier_stokes_base.cc
Labels: bug, reviewed and ready to merge
