Repository chaos-polymtl/lethe, pull requests merged in 2024-02, with the labels that each got.

#1000 Neumann BC for heat
  CHANGELOG.md
  applications_tests/lethe-fluid/ggls-stab_gls.prm
  applications_tests/lethe-fluid/heat_transfer_heat-flux.output
  applications_tests/lethe-fluid/heat_transfer_heat-flux.prm
  applications_tests/lethe-fluid/heat_transfer_laser.prm
  applications_tests/lethe-fluid/heat_transfer_radiation.prm
  applications_tests/lethe-fluid/heat_transfer_vof_interface_gaussian_laser.prm
  applications_tests/lethe-fluid/mms-conv-bc_gls.prm
  applications_tests/lethe-fluid/time_dependent_boundaries_heat_transfer.prm
  doc/source/examples/multiphysics/laser-heating/laser-heating.rst
  doc/source/examples/multiphysics/laser-melt-pool/laser-melt-pool.rst
  doc/source/examples/multiphysics/warming-up-a-viscous-fluid/warming-up-a-viscous-fluid.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  examples/multiphysics/laser-heating/laser-heating.prm
  examples/multiphysics/laser-melt-pool/laser-melt-pool.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra25k.prm
  examples/multiphysics/warming-up-viscous-fluid/warming-up-viscous-fluid.prm
  include/core/boundary_conditions.h
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
Labels: Enhancement, Reviewed and ready to merge, Rebased

#1012 Quick fix on the documentation
  doc/source/installation/regular_installation.rst
Labels: Maintenance, Quick fix, Ready for review

#1015 Add doxygen build files to .gitignore
  .gitignore
Labels: Quick fix, doxygen Hackathon

#1016 Documentation mobility model, cahn-hilliard filtering
  include/core/mobility_cahn_hilliard_model.h
  include/solvers/cahn_hilliard_filter.h
Labels: Reviewed and waiting for changes, doxygen Hackathon

#1018 Upgrade documentation for dem contact manager
  include/dem/dem_contact_manager.h
  source/dem/find_cell_neighbors.cc
Labels: doxygen Hackathon

#1019 Upgrade documentation for the matrix-free classes
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes_operators.cc
Labels: doxygen Hackathon

#1020 Update comments in bdf.h
  include/core/bdf.h
Labels: doxygen Hackathon

#1023 Remove brief description
  doc/doxygen/doxygen-config-file
Labels: Quick fix, doxygen Hackathon

#1024 Change title of doxygen main page
  doc/doxygen/doxygen-config-file
Labels: Quick fix, doxygen Hackathon

#1027 Update comments in density_model.h
  include/core/density_model.h
Labels: doxygen Hackathon

#1026 Upgrade doxygen doc for all nonlinear solvers
  include/core/inexact_newton_non_linear_solver.h
  include/core/kinsol_newton_non_linear_solver.h
  include/core/newton_non_linear_solver.h
  include/core/non_linear_solver.h
Labels: doxygen Hackathon

#1025 Doxygen ib stencil
  include/core/ib_stencil.h
  source/core/ib_stencil.cc
Labels: doxygen Hackathon

#1022 Update documentation for the postprocessing of averaging velocities and Reynolds stresses
  include/solvers/postprocessing_velocities.h
Labels: Reviewed and ready to merge, doxygen Hackathon

#1029 Update comments in vof_filter.h
  include/solvers/vof_filter.h
Labels: Reviewed and waiting for changes, doxygen Hackathon

#1021 Doxygen ib particles
  include/core/ib_particle.h
Labels: Reviewed and waiting for changes, doxygen Hackathon

#1032 Update comments in postprocessor.h
  include/solvers/postprocessors.h
Labels: Ready for review, doxygen Hackathon

#1031 Modify surface tension formulation
  applications_tests/lethe-fluid/gls_vof_static_droplet_surface_tension_force_with_tanh_filter.output
  examples/multiphysics/laser-powder-bed-fusion/benchmark.prm
  examples/multiphysics/thermocapillary-droplet/thermocapillary-droplet.prm
  include/solvers/navier_stokes_scratch_data.h
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: Reviewed and ready to merge

#1035 Quick fix to doxygen comments in postprocessor.h
  include/solvers/postprocessors.h
Labels: Quick fix

#1033 Add time step limit for adaptive time stepping scheme
  doc/source/parameters/cfd/simulation_control.rst
  include/core/parameters.h
  include/core/simulation_control.h
  source/core/parameters.cc
  source/core/simulation_control.cc
  tests/core/simulation_control_03.cc
  tests/solvers/average_velocities_02.cc
  tests/solvers/reynolds_stress_02.cc
Labels: Reviewed and ready to merge

#1036 Add taylor-green matrix-free and matrix-based example
  doc/aggregate/index.html
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/images/dissipation_comparison_Q2_32.png
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/images/dissipation_comparison_Q3_128.png
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/images/dissipation_comparison_Q3_32.png
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/images/dissipation_comparison_Q3_64.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible-flow/3d-taylor-green-vortex/calculate_dissipation_rate.py
  examples/incompressible-flow/3d-taylor-green-vortex/plot_dissipation_rate.py
  examples/incompressible-flow/3d-taylor-green-vortex/plot_reference.py
  examples/incompressible-flow/3d-taylor-green-vortex/reference/jacobs_rateE_256.dat
  examples/incompressible-flow/3d-taylor-green-vortex/reference/jacobs_rateK_256.dat
  examples/incompressible-flow/3d-taylor-green-vortex/reference/wang_2013.dat
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-based.prm
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-free.prm
Labels: Ready for review, Example

#1034 Doxygen doc update for heat_transfer.h
  include/solvers/heat_transfer.h
Labels: Beginner's work, Reviewed and ready to merge, doxygen Hackathon

#1039 Update VOF mass conservation output
  applications_tests/lethe-fluid/cavity_ht_average_velocity_restart.prm
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.prm
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.prm
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.prm
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.prm
  applications_tests/lethe-fluid/gls_vof_ht_heated-walls_heat-flux.prm
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.prm
  applications_tests/lethe-fluid/heat_transfer_vof_interface_gaussian_laser.prm
  applications_tests/lethe-fluid/interface_sharpening_blurred_circle_adaptive_mass_conservation.prm
  applications_tests/lethe-fluid/liquid_thermocapillary_droplet.output
  applications_tests/lethe-fluid/liquid_thermocapillary_droplet.prm
  applications_tests/lethe-fluid/solid_thermocapillary_droplet.output
  applications_tests/lethe-fluid/solid_thermocapillary_droplet.prm
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/parameters/cfd/post_processing.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-constant-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor_postprocess.py
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/solvers/simulation_parameters.h
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge

#1038 Temperature-dependant solid domain constraints
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.prm
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/constrain_solid_domain.rst
  doc/source/parameters/cfd/physical_properties.rst
  doc/source/theory/fluid_dynamics/navier-stokes.rst
  examples/multiphysics/melting-cavity/melting-cavity.py
  include/core/multiphysics.h
  include/core/parameters.h
  include/core/physical_property_model.h
  include/solvers/auxiliary_physics.h
  include/solvers/cahn_hilliard.h
  include/solvers/gls_navier_stokes.h
  include/solvers/heat_transfer.h
  include/solvers/multiphysics_interface.h
  include/solvers/navier_stokes_base.h
  include/solvers/simulation_parameters.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/fem-dem/gls_vans.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/vof.cc
Labels: Enhancement, Reviewed and ready to merge

#1042 Fix documentation of enstrophy/Kin eng calculation
  doc/source/parameters/cfd/post_processing.rst
Labels: Quick fix, Ready for review
