Repository chaos-polymtl/lethe, pull requests merged in 2024-03, with the labels that each got.

#1046 Added timer for the write vtu and load balancing in the dem
  examples/dem/3d-bunny-drill/bunny-drill-loading.prm
  source/dem/dem.cc
Labels: Enhancement, Reviewed and ready to merge, Quick fix

#1051 Add compressibility to heat transfer
  applications_tests/lethe-fluid/heat_transfer_vof_weakly_compressible_flow.output
  applications_tests/lethe-fluid/heat_transfer_vof_weakly_compressible_flow.prm
  applications_tests/lethe-fluid/heat_transfer_weakly_compressible_flow.output
  applications_tests/lethe-fluid/heat_transfer_weakly_compressible_flow.prm
  include/solvers/heat_transfer_scratch_data.h
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_scratch_data.cc
Labels: Reviewed and ready to merge, Quick fix

#1052 Minor fixes in prm files of matrix-free application tests
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.prm
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.prm
Labels: Quick fix

#1057 Update changelog
  CHANGELOG.md
Labels: Ready for review

#1056 Initial refinement at boundaries
  CHANGELOG.md
  applications_tests/lethe-fluid/taylorcouette_boundary_ref.output
  applications_tests/lethe-fluid/taylorcouette_boundary_ref.prm
  doc/source/parameters/cfd/mesh.rst
  include/core/grids.h
  include/core/parameters.h
  source/core/grids.cc
  source/core/parameters.cc
  source/core/parameters_lagrangian.cc
Labels: Reviewed and ready to merge

#1053 Unify SUPG/PSPG and GLS matrix-free operators
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1055 Remove expansion term from recoil pressure
  CHANGELOG.md
  include/core/evaporation_model.h
Labels: Reviewed and ready to merge

#1059 Update lpbf benchmark example prm
  examples/multiphysics/laser-powder-bed-fusion/1D/benchmark.prm
  examples/multiphysics/laser-powder-bed-fusion/2D/benchmark.prm
  examples/multiphysics/laser-powder-bed-fusion/3D/benchmark.prm
Labels: Ready for review

#1060 Add new lethe logos
  README.md
  doc/source/index.rst
  logo/lethe-logo-white-without-bkgd.png
  logo/lethe-logo-with-bkgd.png
  logo/lethe-logo-without-bkgd.png
  logo/lethe-round-logo-white-without-bkgd.png
  logo/lethe-round-logo-with-bkgd.png
  logo/lethe-round-logo-without-bkgd.png
  logo/logo_black.png
  logo/logo_black2.png
Labels: Rebased

#1061 Add stasis constraint in melting cavity example
  CHANGELOG.md
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  doc/source/parameters/cfd/constrain_stasis.rst
  examples/multiphysics/melting-cavity/melting-cavity-stasis-constraint.prm
Labels: Reviewed and ready to merge, Example

#1063 Remove global vector type from prototypes
  prototypes/matrix_based_advection_diffusion/matrix_based_advection_diffusion.cc
  prototypes/matrix_based_non_linear_poisson/matrix_based_non_linear_poisson.cc
Labels: Quick fix, Ready for review

#1062 Fix vof mass monitoring print
  CHANGELOG.md
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.prm
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  include/core/utilities.h
  source/core/utilities.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge, Rebased

#1065 Add fields check to physical property models
  CHANGELOG.md
  include/core/density_model.h
  include/core/evaporation_model.h
  include/core/mobility_cahn_hilliard_model.h
  include/core/parameters.h
  include/core/physical_property_model.h
  include/core/rheological_model.h
  include/core/specific_heat_model.h
  include/core/surface_tension_model.h
  include/core/thermal_conductivity_model.h
  include/core/thermal_expansion_model.h
  source/core/rheological_model.cc
Labels: Maintenance, Ready for review, Rebased

#1064 Use the eigenvalue estimation of PreconditionRelaxation
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.with_dealii.geq.9.6.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.prm
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.with_dealii.geq.9.6.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.with_dealii.geq.9.6.mpirun=2.output
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  doc/source/parameters/cfd/linear_solver_control.rst
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-free.prm
  include/core/parameters.h
  include/solvers/mf_navier_stokes.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge

#1068 Fix warning
  source/dem/particle_particle_fine_search.cc
Labels: Reviewed and ready to merge

#1067 Remove parameter qmapping_all
  applications_tests/lethe-fluid-block/mms2d-unstructured_gd.prm
  applications_tests/lethe-fluid-block/mms2d_gd.prm
  applications_tests/lethe-fluid-block/mms2d_powerlaw_gd.prm
  applications_tests/lethe-fluid-block/mms3d_gd.prm
  applications_tests/lethe-fluid-block/poiseuille3d_gd.prm
  applications_tests/lethe-fluid-block/taylorcouette_gd.prm
  applications_tests/lethe-fluid-block/taylorcouette_gd_dimensions.prm
  applications_tests/lethe-fluid/cylinder-rigid-body_gls.prm
  applications_tests/lethe-fluid/mms2d_carreau_1st-order_gls.prm
  applications_tests/lethe-fluid/mms2d_carreau_2nd-order_gls.prm
  applications_tests/lethe-fluid/poiseuille3d-flow-control_gls_bdf1.prm
  applications_tests/lethe-fluid/poiseuille3d_balanced_grid.prm
  applications_tests/lethe-fluid/poiseuille3d_gls.prm
  applications_tests/lethe-fluid/rigid-body-rotation_gls.prm
  applications_tests/lethe-fluid/taylorcouette-unstructured_gls.prm
  applications_tests/lethe-fluid/taylorcouette_boundary_ref.prm
  applications_tests/lethe-fluid/taylorcouette_gls.prm
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
  doc/source/parameters/cfd/fem.rst
  examples/incompressible-flow/2d-taylor-couette/taylor-couette.prm
  examples/incompressible-flow/3d-ribbon-mixer-cad-aware/ribbon-gls.prm
  examples/incompressible-flow/3d-ribbon-mixer/ribbon-gls.prm
  include/core/parameters.h
  include/solvers/cahn_hilliard.h
  include/solvers/heat_transfer.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/core/parameters.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessors_smoothing.cc
Labels: Reviewed and ready to merge

#1069 Only store relevant values in edge_constrained_values
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1070 Consider constraints during ev estimation
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge

#1072 Make stasis constraint compatible with restart and adaptive mesh refi…
  CHANGELOG.md
  source/solvers/vof.cc
Labels: Quick fix, Ready for review

#1075 Update flow control parameters in periodic hills example
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
Labels: Documentation, Quick fix

#1071 Pointwise tutorial
  doc/source/tools/pointwise/images/assemble_domains.png
  doc/source/tools/pointwise/images/assemble_domains2.png
  doc/source/tools/pointwise/images/boundary_conditions.png
  doc/source/tools/pointwise/images/boundary_conditions2.png
  doc/source/tools/pointwise/images/connector_domain_block.png
  doc/source/tools/pointwise/images/connectors.png
  doc/source/tools/pointwise/images/connectors_dimension.png
  doc/source/tools/pointwise/images/entities.png
  doc/source/tools/pointwise/images/extrusion.png
  doc/source/tools/pointwise/images/filling1.png
  doc/source/tools/pointwise/images/filling2.png
  doc/source/tools/pointwise/images/filling3.png
  doc/source/tools/pointwise/images/final_mesh.png
  doc/source/tools/pointwise/images/final_mesh_3d.png
  doc/source/tools/pointwise/images/final_mesh_no_center.png
  doc/source/tools/pointwise/images/icon_assemble_blocks.png
  doc/source/tools/pointwise/images/icon_assemble_doms.png
  doc/source/tools/pointwise/images/icon_curve.png
  doc/source/tools/pointwise/images/icon_two_pt_curve.png
  doc/source/tools/pointwise/images/split.png
  doc/source/tools/pointwise/images/split_3d.png
  doc/source/tools/pointwise/images/toolbar_create.png
  doc/source/tools/pointwise/images/toolbar_grid.png
  doc/source/tools/pointwise/images/toolbar_mask.png
  doc/source/tools/pointwise/images/translation.png
  doc/source/tools/pointwise/images/two_point_curve.png
  doc/source/tools/pointwise/pointwise.rst
  doc/source/tools/tools.rst
Labels: Beginner's work, Documentation, Ready for review

#1073 Vof momentum monitoring
  CHANGELOG.md
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  doc/source/parameters/cfd/post_processing.rst
  include/solvers/vof.h
  source/core/parameters.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge

#1077 fix lid driven cavity postprocessing
  doc/source/first_simulation.rst
  examples/incompressible-flow/2d-lid-driven-cavity/post_process_Reynolds_400.py
Labels: Quick fix

#1078 Dem volume insertion initial velocities
  CHANGELOG.md
  applications_tests/lethe-particles/initial_value_insertion.prm
  doc/source/parameters/dem/insertion_info.rst
  include/core/parameters_lagrangian.h
  source/core/parameters_lagrangian.cc
  source/dem/insertion.cc
Labels: Quick fix, Ready for review

#1080 Dem volume insertion initial velocities
  include/core/parameters_lagrangian.h
  source/core/parameters_lagrangian.cc
  source/dem/insertion.cc
Labels: Quick fix, Ready for review

#1081 replace reduced pressure with kinematic pressure
  doc/source/theory/fluid_dynamics/navier-stokes.rst
Labels: Documentation, Quick fix

#1079 Dem insertion naming refactor
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/insertion_file.h
  include/dem/insertion_list.h
  include/dem/insertion_plane.h
  include/dem/insertion_volume.h
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/insertion_file.cc
  source/dem/insertion_list.cc
  source/dem/insertion_plane.cc
  source/dem/insertion_volume.cc
  tests/dem/distribution_custom.cc
  tests/dem/distribution_normal.cc
  tests/dem/insertion_plane.cc
  tests/dem/insertion_volume_1.cc
  tests/dem/insertion_volume_2.cc
Labels: Maintenance, Ready for review, Refactoring

#1082 Dem fixing tangential damping
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.mpirun=1.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.mpirun=1.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.mpirun=1.output
  applications_tests/lethe-particles/ball_with_floating_walls.output
  applications_tests/lethe-particles/box_grid_rotation.output
  applications_tests/lethe-particles/box_grid_slide.output
  applications_tests/lethe-particles/circle_restart.mpirun=1.output
  applications_tests/lethe-particles/circle_with_floating_walls.mpirun=1.output
  applications_tests/lethe-particles/floating_mesh.output
  applications_tests/lethe-particles/insert_list_3d_default_velocities.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/mobility_status.output
  applications_tests/lethe-particles/packing_in_ball.mpirun=1.output
  applications_tests/lethe-particles/packing_in_ball.mpirun=2.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_contact.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/packing_in_box.mpirun=1.output
  applications_tests/lethe-particles/packing_in_box.mpirun=2.output
  applications_tests/lethe-particles/packing_in_circle.mpirun=1.output
  applications_tests/lethe-particles/packing_in_circle.mpirun=2.output
  applications_tests/lethe-particles/packing_in_cylinder.output
  applications_tests/lethe-particles/packing_in_square.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=2.output
  applications_tests/lethe-particles/perpendicular_rotation_to_wall.output
  applications_tests/lethe-particles/restart_moving_receptacle.mpirun=1.output
  applications_tests/lethe-particles/rotating_in_circle.output
  applications_tests/lethe-particles/sliding_in_box.output
  applications_tests/lethe-particles/sliding_restart.mpirun=1.output
  applications_tests/lethe-particles/two_types_packing_in_circle.output
  source/dem/particle_wall_nonlinear_force.cc
Labels: Maintenance, Reviewed and ready to merge
