Repository chaos-polymtl/lethe, pull requests merged in 2024-07, with the labels that each got.

#1183 Update installation doc
  doc/source/installation/apple_arm.rst
  doc/source/installation/regular_installation.rst
  doc/source/installation/windows_wsl.rst
Labels: Documentation, WIP

#1184 Fix box refinement with restart
  CHANGELOG.md
  applications_tests/lethe-fluid/2d-benchmark.msh
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/generators/heat_transfer_vof_lpbf_benchmark_box_ref_generator.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/mass_conservation_information.checkpoint
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/restart.pvdhandler
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/restart.simulationcontrol
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/restart.triangulation
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/restart.triangulation.info
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/restart.triangulation_fixed.data
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref_restart_files/temperature_statistics.checkpoint
  include/solvers/navier_stokes_base.h
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
Labels: Quick fix, Ready for review

#1186 Refactor entry string to tensor functions
  CHANGELOG.md
  include/core/manifolds.h
  include/core/parameters.h
  include/core/utilities.h
  source/core/manifolds.cc
  source/core/parameters.cc
  source/core/parameters_lagrangian.cc
  source/core/utilities.cc
Labels: Ready for review, Refactoring

#1189 fix multiphysics examples diagram
  doc/source/examples/multiphysics/multiphysics.rst
Labels: Documentation, Quick fix

#1187 Improve timer output for the fluid applications
  CHANGELOG.md
  doc/source/parameters/cfd/timer.rst
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/mf_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
Labels: Enhancement, Ready for review

#1192 Nitsche checkpoint particles
  CHANGELOG.md
  applications/lethe-fluid-nitsche/nitsche_navier_stokes.cc
  applications_tests/lethe-fluid-nitsche/CMakeLists.txt
  applications_tests/lethe-fluid-nitsche/generators/two-bar-mixer-start.prm
  applications_tests/lethe-fluid-nitsche/two-bar-mixer-restart.prm
  applications_tests/lethe-fluid-nitsche/two-bar-mixer-restart/restart_solid_00.particles
  applications_tests/lethe-fluid-nitsche/two-bar-mixer-restart/restart_solid_00.triangulation
  applications_tests/lethe-fluid-nitsche/two-bar-mixer-restart/restart_solid_01.particles
  applications_tests/lethe-fluid-nitsche/two-bar-mixer-restart/restart_solid_01.triangulation
  source/core/solid_base.cc
  source/solvers/gls_nitsche_navier_stokes.cc
Labels: Bug, Ready for review

#1185 Tracer with Sharp IB
  CHANGELOG.md
  applications_tests/lethe-fluid-sharp/tracer_around_sphere.output
  applications_tests/lethe-fluid-sharp/tracer_around_sphere.prm
  doc/source/parameters/cfd/physical_properties.rst
  include/core/parameters.h
  include/core/physical_property_model.h
  include/core/tracer_diffusivity_model.h
  include/fem-dem/gls_sharp_navier_stokes.h
  include/solvers/multiphysics_interface.h
  include/solvers/physical_properties_manager.h
  include/solvers/tracer.h
  include/solvers/tracer_scratch_data.h
  source/core/parameters.cc
  source/core/tracer_diffusivity_model.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/multiphysics_interface.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/physical_properties_manager.cc
  source/solvers/tracer.cc
  source/solvers/tracer_scratch_data.cc
  tests/core/immersed_solid_diffusivity_tanh.cc
  tests/core/immersed_solid_diffusivity_tanh.output
Labels: Enhancement

#1196 Upgrade reference format in documentation (DEM, CFD-DEM unresolved and RPT)
  doc/source/contributing.rst
  doc/source/examples/dem/bouncing-particle/bouncing-particle.rst
  doc/source/examples/dem/granular-dam-break/granular-dam-break.rst
  doc/source/examples/dem/granular-mixer/granular-mixer.rst
  doc/source/examples/dem/oblique-wall-impact/oblique-wall-impact.rst
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/silo/silo.rst
  doc/source/examples/rpt/particle-fem-reconstruction/particle-fem-reconstruction.rst
  doc/source/examples/rpt/photon-count-calculation-in-a-cylindrical-vessel/photon-count-calculation-in-a-cylindrical-vessel.rst
  doc/source/examples/rpt/tuning-parameters-with-nomad/tuning-parameters-with-nomad.rst
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.rst
Labels: Documentation, Refactoring

#1200 Upgrade reference format in documentation (continued)
  doc/source/examples/incompressible-flow/2d-backward-facing-step/2d-backward-facing-step.rst
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/2d-lid-driven-cavity-flow/lid-driven-cavity-flow.rst
  doc/source/examples/incompressible-flow/2d-naca0012-low-reynolds/2d-naca0012-low-reynolds.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow/2d-taylor-couette-flow.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/2d-transient-flow-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
  doc/source/examples/incompressible-flow/3d-mixer-using-single-rotating-frame/3d-mixer-using-single-rotating-frame.rst
  doc/source/examples/incompressible-flow/3d-nitsche-mixer-with-pbt-impeller/nitsche-mixer-with-pbt-impeller.rst
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
  doc/source/examples/multiphysics/3d-dam-break/3d-dam-break.rst
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/capillary-wave/capillary-wave.rst
  doc/source/examples/multiphysics/concentric-heat-exchanger/concentric-heat-exchanger.rst
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/laser-melt-pool/laser-melt-pool.rst
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  doc/source/examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-instability.rst
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/sloshing-in-rectangular-tank/sloshing-in-rectangular-tank.rst
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/examples/multiphysics/stefan-problem/stefan-problem.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/examples/sharp-immersed-boundary/3d-rbf-static-mixer/3d-rbf-static-mixer.rst
  doc/source/examples/sharp-immersed-boundary/sedimentation-1-particle/sedimentation-1-particle.rst
  doc/source/examples/sharp-immersed-boundary/sedimentation-64-particles/sedimentation-64-particles.rst
  doc/source/parameters/cfd/dynamic_flow_control.rst
  doc/source/parameters/cfd/laser_heat_source.rst
  doc/source/parameters/rpt/detector_parameters.rst
  doc/source/parameters/rpt/parameter_tuning.rst
  doc/source/parameters/rpt/rpt_parameters.rst
  doc/source/parameters/sharp-immersed-boundary/sharp-immersed-boundary.rst
  doc/source/theory/multiphase/cfd/cahn-hilliard.rst
  doc/source/theory/multiphase/cfd/vof.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  doc/source/theory/multiphase/cfd_dem/unresolved_cfd-dem.rst
Labels: Ready for review, Needs more reviewers, Refactoring

#1201 Fix the ASC application test for CFD-DEM
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.mpirun=1.output
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.prm
Labels: Maintenance, Quick fix, Ready for review

#1203 Fix the critical rayleigh time step calculation in cfd-dem
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.mpirun=1.output
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.mpirun=1.output
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.mpirun=1.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.mpirun=1.output
  applications_tests/lethe-fluid-particles/restart-gas-solid-fluidized-bed.mpirun=2.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.mpirun=1.output
  source/fem-dem/cfd_dem_coupling.cc
Labels: Bug, Quick fix, Ready for review

#1202 Rearrange the insertion documentation for DEM
  doc/source/parameters/dem/insertion_info.rst
  source/core/parameters_lagrangian.cc
  source/dem/insertion_volume.cc
Labels: Documentation, Ready for review

#1205 Force the contact search at the last DEM iteration of the CFD iteration in unresolved CFD-DEM
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.mpirun=1.output
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.mpirun=1.output
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.mpirun=1.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm_opposite_flow.mpirun=2.output
  applications_tests/lethe-fluid-particles/restart-gas-solid-fluidized-bed.mpirun=2.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/spouted_bed_load_balancing.mpirun=2.output
  include/fem-dem/cfd_dem_coupling.h
Labels: Quick fix, Ready for review

#1207 Regenerate clean application test outputs in DEM and CFD-DEM
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.mpirun=1.output
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.mpirun=1.output
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.mpirun=1.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.mpirun=1.output
  applications_tests/lethe-fluid-particles/periodic_particles_qcm_opposite_flow.mpirun=2.output
  applications_tests/lethe-fluid-particles/restart-gas-solid-fluidized-bed.mpirun=2.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/spouted_bed_load_balancing.mpirun=2.output
  applications_tests/lethe-fluid-particles/spouted_bed_load_balancing.prm
  applications_tests/lethe-particles/ball_with_floating_walls.output
  applications_tests/lethe-particles/box_grid_rotation.output
  applications_tests/lethe-particles/box_grid_slide.output
  applications_tests/lethe-particles/circle_restart.mpirun=1.output
  applications_tests/lethe-particles/circle_with_floating_walls.mpirun=1.output
  applications_tests/lethe-particles/insert_list_3d_default_velocities.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/mobility_status.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/packing_in_box.mpirun=1.output
  applications_tests/lethe-particles/packing_in_cylinder.output
  applications_tests/lethe-particles/packing_in_square.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=1.output
  applications_tests/lethe-particles/perpendicular_rotation_to_wall.output
  applications_tests/lethe-particles/pp_dmt_equilibrium.output
  applications_tests/lethe-particles/pp_jkr_equilibrium.output
  applications_tests/lethe-particles/pw_dmt_equilibrium.output
  applications_tests/lethe-particles/pw_jkr_equilibrium.output
  applications_tests/lethe-particles/restart_file_insertion.mpirun=1.output
  applications_tests/lethe-particles/restart_moving_receptacle.mpirun=1.disabled
  applications_tests/lethe-particles/rotating_in_circle.output
  applications_tests/lethe-particles/sliding_restart.mpirun=1.output
  applications_tests/lethe-particles/solid_surface.output
  applications_tests/lethe-particles/two_types_packing_in_circle.output
  source/fem-dem/cfd_dem_coupling.cc
Labels: Quick fix, Ready for review

#1206 Introduce the DEM action manager
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/restart-gas-solid-fluidized-bed.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  include/dem/adaptive_sparse_contacts.h
  include/dem/dem.h
  include/dem/dem_action_manager.h
  include/dem/dem_contact_manager.h
  include/dem/find_contact_detection_step.h
  include/dem/grid_motion.h
  include/dem/integrator.h
  include/dem/load_balancing.h
  include/dem/periodic_boundaries_manipulator.h
  include/dem/uniform_insertion.h
  include/dem/update_local_particle_containers.h
  include/fem-dem/cfd_dem_coupling.h
  performance_analyses/dem/short_packing_10k_particles/benchmark_simulation_time_load_balancing.dat
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic.prm
  performance_analyses/dem/short_packing_10k_particles/packing_10kparticles_dynamic_load_balancing.prm
  source/dem/CMakeLists.txt
  source/dem/adaptive_sparse_contacts.cc
  source/dem/dem.cc
  source/dem/dem_action_manager.cc
  source/dem/dem_contact_manager.cc
  source/dem/explicit_euler_integrator.cc
  source/dem/find_boundary_cells_information.cc
  source/dem/find_contact_detection_step.cc
  source/dem/gear3_integrator.cc
  source/dem/grid_motion.cc
  source/dem/input_parameter_inspection.cc
  source/dem/load_balancing.cc
  source/dem/particle_wall_contact_force.cc
  source/dem/periodic_boundaries_manipulator.cc
  source/dem/read_checkpoint.cc
  source/dem/update_local_particle_containers.cc
  source/dem/velocity_verlet_integrator.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/find_contact_pairs.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_particle_fine_search.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Enhancement, Reviewed and ready to merge, Refactoring

#1209 Add different variants of p-multgrid
  CHANGELOG.md
  doc/source/parameters/cfd/linear_solver_control.rst
  include/core/parameters.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge

#1210 Add ASM as preconditioner of smoother
  include/core/parameters.h
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1216 Fix the Coulomb's criterion in linear, Hertz, and Hertz-Mindlin with limit force in DEM
  CHANGELOG.md
  applications_tests/lethe-particles/ball_with_floating_walls.output
  applications_tests/lethe-particles/box_grid_rotation.output
  applications_tests/lethe-particles/circle_restart.mpirun=1.output
  applications_tests/lethe-particles/circle_with_floating_walls.mpirun=1.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_contact.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/two_types_packing_in_circle.output
  include/dem/particle_particle_contact_force.h
Labels: Bug, Reviewed and ready to merge, Quick fix
