Repository chaos-polymtl/lethe, pull requests merged in 2024-05, with the labels that each got.

#1107 Dem fixing tangential overlap
  applications_tests/lethe-particles/ball_with_floating_walls.output
  applications_tests/lethe-particles/box_grid_rotation.output
  applications_tests/lethe-particles/box_grid_slide.output
  applications_tests/lethe-particles/circle_restart.mpirun=1.output
  applications_tests/lethe-particles/circle_with_floating_walls.mpirun=1.output
  applications_tests/lethe-particles/floating_mesh.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/mobility_status.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/packing_in_box.mpirun=1.output
  applications_tests/lethe-particles/packing_in_box.mpirun=2.output
  applications_tests/lethe-particles/packing_in_cylinder.output
  applications_tests/lethe-particles/packing_in_square.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=1.output
  applications_tests/lethe-particles/periodic_boundary_collisions.mpirun=2.output
  applications_tests/lethe-particles/restart_moving_receptacle.mpirun=1with_dealii.geq.9.6.output
  applications_tests/lethe-particles/rotating_in_circle.output
  applications_tests/lethe-particles/sliding_restart.mpirun=1.output
  applications_tests/lethe-particles/two_types_packing_in_circle.output
  include/dem/particle_particle_contact_force.h
  tests/dem/two_particles_multiple_contacts_parallel.mpirun=2.output
Labels: Reviewed and ready to merge

#1109 Fix viscosity initial conditions for matrix-free
  include/solvers/mf_navier_stokes.h
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge

#1111 Fix NavierStokesOperatorBase::get_system_matrix()
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1112 Add timers for GMG vmult
  include/solvers/mf_navier_stokes.h
  source/solvers/mf_navier_stokes.cc
Labels: Ready for review

#1108 Update update-golden for the serial output
  applications_tests/lethe-particles/restart_moving_receptacle.with_dealii.geq.9.6.mpirun=1.output
  contrib/utilities/update-golden.tl
Labels: Quick fix, Ready for review

#1114 Added runtime errors when reading files.
  source/core/utilities.cc
Labels: Reviewed and ready to merge, Quick fix

#1116 Add timers for matrix-free operators
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1119 Remove duplicated code in GMG preconditioner
  source/solvers/mf_navier_stokes.cc
Labels: Ready for review

#1121 Add more coarse-grid solvers for GMG
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.prm
  applications_tests/lethe-fluid-matrix-free/taylor_couette_2d_local_ref.prm
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.prm
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  doc/source/parameters/cfd/linear_solver_control.rst
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-free.prm
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
  include/core/parameters.h
  include/solvers/mf_navier_stokes.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge

#1101 Create a example of gas-solid-spouted-cylinder-bed
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/gas-solid-spouted-cylinder-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/images/ID.png
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/images/geometry.png
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/images/mesh.png
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/images/pressure_drop.png
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/dem-packing-in-spouted-cylinder-bed-generator.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/gas-solid-spouted-cylinder-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/output/dummy-file
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/output_dem/dummy-file
Labels: Beginner's work, Documentation, Ready for review, Example

#1118 Improve CFD-DEM assemblers performance
  applications_tests/lethe-fluid-vans/case0_vans_A.output
  applications_tests/lethe-fluid-vans/case0_vans_A.prm
  applications_tests/lethe-fluid-vans/case0_vans_B.output
  applications_tests/lethe-fluid-vans/case0_vans_B.prm
  applications_tests/lethe-fluid-vans/case1_vans_A.output
  applications_tests/lethe-fluid-vans/case1_vans_A.prm
  applications_tests/lethe-fluid-vans/case1_vans_B.output
  applications_tests/lethe-fluid-vans/case1_vans_B.prm
  applications_tests/lethe-fluid-vans/case2_vans_A.output
  applications_tests/lethe-fluid-vans/case2_vans_A.prm
  applications_tests/lethe-fluid-vans/case2_vans_B.output
  applications_tests/lethe-fluid-vans/case2_vans_B.prm
  source/fem-dem/vans_assemblers.cc
Labels: Reviewed and ready to merge

#1125 Allow to use FE_Q_iso_Q1 elements for the MG coarse level
  doc/source/parameters/cfd/linear_solver_control.rst
  include/core/parameters.h
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1124 Allow to disable Navier-Stokes source term in MF
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/poiseuille3d_flow_control.prm
  applications_tests/lethe-fluid-matrix-free/taylor_couette_2d_local_ref.prm
  applications_tests/lethe-fluid-matrix-free/tgv_fe1_ilu.prm
  applications_tests/lethe-fluid-matrix-free/tgv_fe1_ilu_gls.prm
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.prm
  doc/source/parameters/cfd/source_term.rst
  include/solvers/mf_navier_stokes_operators.h
  include/solvers/source_terms.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1127 Add functionality to disable hessians in matrix-free
  doc/source/parameters/cfd/linear_solver_control.rst
  include/core/parameters.h
  include/solvers/mf_navier_stokes_operators.h
  source/core/parameters.cc
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Ready for review

#1134 Fix viscous initial condition for transient problems in MF
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge, Quick fix, Hackathon

#1133 Improve spouted bed example
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/gas-solid-spouted-cylinder-bed.rst
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/dem-packing-in-spouted-cylinder-bed-generator.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-cylinder-bed/gas-solid-spouted-cylinder-bed.prm
Labels: Reviewed and ready to merge, Hackathon

#1123 Quick fix in update fine search candidate for map accessors
  include/ankerl/unordered_dense.h
  include/dem/particle_particle_broad_search.h
  include/dem/particle_particle_fine_search.h
  include/dem/particle_wall_broad_search.h
  include/dem/update_local_particle_containers.h
  source/dem/particle_particle_broad_search.cc
  source/dem/particle_particle_fine_search.cc
  source/dem/particle_wall_broad_search.cc
  source/dem/update_fine_search_candidates.cc
  source/dem/update_local_particle_containers.cc
Labels: Bug, Reviewed and ready to merge

#1136 Solid objects did not trigger a contact detection step when they were moved
  applications_tests/lethe-particles/moving_float.mpirun=1.output
  source/dem/dem.cc
Labels: Bug, Reviewed and ready to merge, Hackathon

#1128 Robin/Neumann BC parameters were not space dependent
  applications_tests/lethe-fluid/non-uniform_heat_flux_bc.output
  applications_tests/lethe-fluid/non-uniform_heat_flux_bc.prm
  applications_tests/lethe-fluid/non-uniform_transient_heat_flux_bc.output
  applications_tests/lethe-fluid/non-uniform_transient_heat_flux_bc.prm
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
Labels: Enhancement, Reviewed and ready to merge, Rebased

#1138 Reorganization of theory
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/parameters/cfd/linear_solver_control.rst
  doc/source/parameters/cfd/stabilization.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  doc/source/parameters/dem/model_parameters.rst
  doc/source/parameters/unresolved-cfd-dem/cfd-dem.rst
  doc/source/theory/multiphase/cfd/cahn-hilliard.rst
  doc/source/theory/multiphase/cfd/cfd.rst
  doc/source/theory/multiphase/cfd/images/vof.png
  doc/source/theory/multiphase/cfd/vof.rst
  doc/source/theory/multiphase/cfd_dem/cfd_dem.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  doc/source/theory/multiphase/cfd_dem/images/collision_particles.png
  doc/source/theory/multiphase/cfd_dem/images/qcm.png
  doc/source/theory/multiphase/cfd_dem/images/schematic_unresolve_cfd-dem.png
  doc/source/theory/multiphase/cfd_dem/images/spm.png
  doc/source/theory/multiphase/cfd_dem/images/void_frac1.png
  doc/source/theory/multiphase/cfd_dem/images/void_frac2.png
  doc/source/theory/multiphase/cfd_dem/resolved_cfd-dem.rst
  doc/source/theory/multiphase/cfd_dem/unresolved_cfd-dem.rst
  doc/source/theory/multiphase/multiphase.rst
  doc/source/theory/multiphysics/electromagnetism/electromagnetism.rst
  doc/source/theory/multiphysics/electromagnetism/magnetohydrodynamics.rst
  doc/source/theory/multiphysics/electromagnetism/time_harmonic.rst
  doc/source/theory/multiphysics/fluid_dynamics/fem_formulation.rst
  doc/source/theory/multiphysics/fluid_dynamics/fluid_dynamics.rst
  doc/source/theory/multiphysics/fluid_dynamics/linear_solvers.rst
  doc/source/theory/multiphysics/fluid_dynamics/navier-stokes.rst
  doc/source/theory/multiphysics/fluid_dynamics/rheology.rst
  doc/source/theory/multiphysics/fluid_dynamics/stabilization.rst
  doc/source/theory/multiphysics/heat_transfer/heat_equation.rst
  doc/source/theory/multiphysics/heat_transfer/heat_transfer.rst
  doc/source/theory/multiphysics/multiphysics.rst
  doc/source/theory/multiphysics/passive_tracer/passive_tracer.rst
  doc/source/theory/multiphysics/passive_tracer/passive_tracer_equations.rst
  doc/source/theory/theory.rst
Labels: Documentation, Hackathon

#1140 Fix tracer precisions in file output
  source/solvers/tracer.cc
Labels: Quick fix

#1142 Quick fix on Robin boundary condition
  applications_tests/lethe-fluid/non-uniform_transient_heat_flux_bc.prm
  source/solvers/heat_transfer_assemblers.cc
Labels: Reviewed and ready to merge, Quick fix, Ready for review, Hackathon

#1139 One way coupling MF and heat transfer
  applications_tests/lethe-fluid-matrix-free/heat_transfer_high_pe_stab_gls.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/heat_transfer_high_pe_stab_gls.output
  applications_tests/lethe-fluid-matrix-free/heat_transfer_high_pe_stab_gls.prm
  include/solvers/mf_navier_stokes.h
  source/solvers/mf_navier_stokes.cc
Labels: Reviewed and ready to merge, Hackathon

#1146 Correct minor typos in documentation
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
  doc/source/parameters/cfd/post_processing.rst
Labels: Documentation, Reviewed and ready to merge, Hackathon

#1137 Deploy DEBUG CI on self-hosted runner
  .github/workflows/main_debug.yml
  .github/workflows/main_parameter_files.yml
  .github/workflows/main_release.yml
  .github/workflows/main_warnings.yml
  CMakeLists.txt
  applications_tests/lethe-fluid/CMakeLists.txt
Labels: Hackathon, CI

#1126 Modify viscosity in stabilization tau
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.prm
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.prm
  include/core/rheological_model.h
  include/solvers/navier_stokes_scratch_data.h
  source/core/rheological_model.cc
  source/solvers/isothermal_compressible_navier_stokes_assembler.cc
  source/solvers/isothermal_compressible_navier_stokes_vof_assembler.cc
  source/solvers/navier_stokes_assemblers.cc
  source/solvers/navier_stokes_cahn_hilliard_assemblers.cc
  source/solvers/navier_stokes_scratch_data.cc
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: Reviewed and ready to merge

#1151 Fix dynamic sparsity pattern multiphysics
  source/solvers/cahn_hilliard.cc
  source/solvers/heat_transfer.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Quick fix, Ready for review

#1150 Correct smoothing range MG parameter
  include/core/parameters.h
  source/core/parameters.cc
Labels: Reviewed and ready to merge, Quick fix

#1152 Increase core count to 4 for CI
  .github/workflows/main_parameter_files.yml
  .github/workflows/main_release.yml
  .github/workflows/main_warnings.yml
Labels: Needs more reviewers, CI

#1143 Adding a custom parsed function
  include/core/mu_parser_internal.h
  include/core/parsed_function_custom.h
  source/core/CMakeLists.txt
  source/core/mu_parser_internal.cc
  source/core/parameters.cc
  source/core/parsed_function_custom.cc
  tests/core/custom_parsed_functions.cc
  tests/core/custom_parsed_functions.output
Labels: Reviewed and ready to merge, Hackathon

#1141 Add DCDD shock capture stabilization term to heat transfer
  applications_tests/lethe-fluid/buoyant_flow_between_parallel_plates.output
  applications_tests/lethe-fluid/cavity_ht_average_velocity_restart.mpirun=1.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/phase_change_darcy.output
  applications_tests/lethe-fluid/phase_change_viscosity.output
  applications_tests/lethe-fluid/time_dependent_boundaries_heat_transfer.output
  applications_tests/lethe-fluid/vof_phase_change_darcy.output
  include/core/multiphysics.h
  include/solvers/heat_transfer.h
  include/solvers/heat_transfer_assemblers.h
  include/solvers/heat_transfer_scratch_data.h
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/vof_assemblers.cc
Labels: Reviewed and ready to merge, Rebased, Hackathon

#1154 Void fraction issue cfd dem
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/gls_vans.cc
Labels: Reviewed and ready to merge

#1155 Sort operation in DCDD implementation in VOF and Tracer
  include/solvers/tracer_assemblers.h
  include/solvers/vof_assemblers.h
  source/solvers/tracer_assemblers.cc
  source/solvers/vof_assemblers.cc
Labels: Reviewed and ready to merge, Quick fix

#1157 Post processing pressure power and viscous dissipation
  applications_tests/lethe-fluid/taylorcouette-unstructured_gls.mpirun=1.output
  applications_tests/lethe-fluid/taylorcouette-unstructured_gls.prm
  applications_tests/lethe-fluid/taylorcouette_gls.mpirun=2.output
  applications_tests/lethe-fluid/taylorcouette_gls.output
  applications_tests/lethe-fluid/taylorcouette_gls.prm
  doc/source/parameters/cfd/post_processing.rst
  include/core/parameters.h
  include/solvers/navier_stokes_base.h
  include/solvers/postprocessing_cfd.h
  source/core/parameters.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_cfd.cc
Labels: Ready for review, Post-processing

#1149 Add missing VOF term in the strong form of the residual
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/evaporation_static_droplet_constant_mass_flux.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.prm
  applications_tests/lethe-fluid/gls_static_droplet_surface_tension_force.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_heat-transfer_hydrostat.output
  applications_tests/lethe-fluid/gls_vof_ht_adapt-dissipation.output
  applications_tests/lethe-fluid/gls_vof_hydrostat.output
  applications_tests/lethe-fluid/gls_vof_hydrostat_initial_refine.output
  applications_tests/lethe-fluid/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/lethe-fluid/gls_vof_static_droplet_surface_tension_force_with_tanh_filter.output
  applications_tests/lethe-fluid/gls_vof_tanh_filter.output
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  source/solvers/navier_stokes_vof_assemblers.cc
Labels: Reviewed and ready to merge

#1161 Rayleigh plateau example
  doc/source/examples/multiphysics/3d-dam-break/3d-dam-break.rst
  doc/source/examples/multiphysics/rayleigh-plateau-instability/images/initial-state-without-gravity.svg
  doc/source/examples/multiphysics/rayleigh-plateau-instability/images/rayleigh-plateau_comparison_figure.png
  doc/source/examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-instability.rst
  doc/source/examples/multiphysics/vof.rst
  examples/multiphysics/rayleigh-plateau-instability/3D-delta0_30/rayleigh-plateau-J1-3D.prm
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10.tpl
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10_delta0_20/rayleigh-plateau-J1-We020-Oh0_10_delta0_20.prm
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-compare.py
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-launch.sh
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-postprocess.py
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-postprocess.sh
Labels: Documentation, Reviewed and ready to merge, Rebased

#1163 Add refinement at frequency tests
  applications_tests/lethe-fluid/refinement_at_frequency_off.output
  applications_tests/lethe-fluid/refinement_at_frequency_off.prm
  applications_tests/lethe-fluid/refinement_at_frequency_on.output
  applications_tests/lethe-fluid/refinement_at_frequency_on.prm
Labels: Reviewed and ready to merge
