Repository chaos-polymtl/lethe, pull requests merged in 2024-04, with the labels that each got.

#1086 Quick fix, OMP_NUM_THREADS = 1
  doc/source/installation/digital_alliance.rst
Labels: Documentation, Quick fix

#1083 Add the example on turbulent taylor-couette flow
  CHANGELOG.md
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q3.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q3.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/geometry.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/mesh.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible-flow/3d-turbulent-taylor-couette/references/enstrophy_wang_p3.tsv
  examples/incompressible-flow/3d-turbulent-taylor-couette/references/enstrophy_wang_p4.tsv
  examples/incompressible-flow/3d-turbulent-taylor-couette/references/enstrophy_wang_p5.tsv
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-postprocessing.py
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc_functions.py
Labels: Beginner's work, Documentation, Reviewed and ready to merge

#1076 Add information linear and non-linear solver outputs
  CHANGELOG.md
  applications_tests/lethe-fluid/heat_transfer_heat-flux.output
  applications_tests/lethe-fluid/heat_transfer_heat-flux.prm
  doc/source/parameters/cfd/linear_solver_control.rst
  include/core/inexact_newton_non_linear_solver.h
  include/core/newton_non_linear_solver.h
  include/core/physics_solver.h
  include/solvers/cahn_hilliard.h
  include/solvers/heat_transfer.h
  include/solvers/navier_stokes_base.h
  include/solvers/tracer.h
  include/solvers/vof.h
  source/solvers/cahn_hilliard.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/mf_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
  tests/core/inexact_newton_non_linear_solver_01.output
  tests/core/inexact_newton_non_linear_solver_02.output
  tests/core/newton_non_linear_solver_01.output
  tests/core/non_linear_test_system_01.h
  tests/core/vector_problem.cc
  tests/core/vector_problem.output
Labels: Reviewed and ready to merge

#1088 Explicitly set max num of threads
  applications/initial_conditions/initial_conditions.cc
  applications/lethe-fluid-block/gd_navier_stokes.cc
  applications/lethe-fluid-matrix-free/mf_navier_stokes.cc
  applications/lethe-fluid-nitsche/nitsche_navier_stokes.cc
  applications/lethe-fluid-particles/cfd_dem_coupling.cc
  applications/lethe-fluid-sharp/gls_sharp_navier_stokes.cc
  applications/lethe-fluid-vans/gls_vans.cc
  applications/lethe-fluid/gls_navier_stokes.cc
  applications/lethe-parameter-check/lethe_parameter_check.cc
  applications/lethe-particles/dem.cc
  applications/lethe-rpt-cell-reconstruction-3d/rpt_cell_reconstruction_3d.cc
  applications/lethe-rpt-fem-reconstruction-3d/rpt_fem_reconstruction_3d.cc
  applications/lethe-rpt-l2-projection-3d/rpt_l2_projection_3d.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/fem-dem/gls_vans.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/gls_nitsche_navier_stokes.cc
  source/solvers/mf_navier_stokes.cc
  tests/TEMPLATE
  tests/core/inexact_newton_non_linear_solver_01.cc
  tests/core/inexact_newton_non_linear_solver_02.cc
  tests/core/kinsol_newton_non_linear_solver_01.cc
  tests/core/lethe_grid_tool_mesh_cut_by_flat_2.cc
  tests/core/lethe_grid_tool_mesh_cut_by_flat_3.cc
  tests/core/newton_non_linear_solver_01.cc
  tests/core/serial_solid_intersection_01.cc
  tests/core/solid_base_22.cc
  tests/core/solid_base_23.cc
  tests/core/solid_base_33.cc
  tests/core/solid_base_33_moving_particles.cc
  tests/core/solid_base_33_moving_triangulation.cc
  tests/core/table_read.cc
  tests/dem/boundary_cells_and_faces.cc
  tests/dem/find_cell_neighbors.cc
  tests/dem/find_full_cell_neighbors.cc
  tests/dem/particle_point_contact.cc
  tests/dem/particle_wall_contact_pairs.cc
  tests/solvers/average_velocities_01.cc
  tests/solvers/average_velocities_02.cc
  tests/solvers/average_velocities_03.cc
  tests/solvers/multiphysics_interface_01.cc
  tests/solvers/restart_01.cc
  tests/solvers/reynolds_stress_01.cc
  tests/solvers/reynolds_stress_02.cc
  tests/solvers/reynolds_stress_03.cc
Labels: Reviewed and ready to merge

#1084 Update restart files, moving receptable
  applications_tests/lethe-particles/moving_receptacle_files/restart.solid_object.00.displacement
  applications_tests/lethe-particles/moving_receptacle_files/restart.solid_object.00.dof
  applications_tests/lethe-particles/moving_receptacle_files/restart.triangulation_variable.data
  applications_tests/lethe-particles/restart_moving_receptacle.mpirun=1with_dealii.geq.9.6.output
Labels: Reviewed and ready to merge

#1090 Support flow dynamic control for matrix-free
  applications_tests/lethe-fluid-matrix-free/poiseuille3d_flow_control.output
  applications_tests/lethe-fluid-matrix-free/poiseuille3d_flow_control.prm
  include/solvers/mf_navier_stokes.h
  include/solvers/mf_navier_stokes_operators.h
  source/solvers/mf_navier_stokes.cc
  source/solvers/mf_navier_stokes_operators.cc
Labels: Reviewed and ready to merge

#1094 Small corrections to doc
  doc/source/examples/multiphysics/capillary-wave/capillary-wave.rst
  doc/source/installation/digital_alliance.rst
  doc/source/tools/postprocessing/postprocessing_pyvista.rst
Labels: Quick fix

#1093 Fix restart transient with variable time step
  CHANGELOG.md
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive.mpirun=1.output
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive.prm
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/L2Error_FD.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/enstrophy.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/generator.prm
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/kinetic_energy.checkpoint
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/restart.pvdhandler
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/restart.simulationcontrol
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/restart.triangulation
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/restart.triangulation.info
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive/restart.triangulation_fixed.data
  source/core/simulation_control.cc
Labels: Bug

#1092 Flow rates postprocessing
  CHANGELOG.md
  source/solvers/navier_stokes_base.cc
Labels: Bug, Reviewed and ready to merge, Quick fix

#1100 Remove duplicated entries in GMG documentation
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: Documentation, Quick fix

#1099 Fix output of number of cells on levels for LSMG
  source/solvers/mf_navier_stokes.cc
Labels: Quick fix

#1098 Refactor DEM to remove function pointers
  applications_tests/lethe-particles/floating_mesh.output
  applications_tests/lethe-particles/floating_mesh.prm
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/periodic_boundary_load_balancing.mpirun=2.output
  include/dem/dem.h
  source/dem/dem.cc
Labels: Reviewed and ready to merge, Refactoring

#1102 Allow to reuse the preconditioner in the Newton solver
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=1.output
  doc/source/parameters/cfd/non-linear_solver_control.rst
  include/core/inexact_newton_non_linear_solver.h
  include/core/kinsol_newton_non_linear_solver.h
  include/core/newton_non_linear_solver.h
  include/core/parameters.h
  include/core/physics_solver.h
  include/fem-dem/gls_sharp_navier_stokes.h
  include/solvers/auxiliary_physics.h
  include/solvers/gd_navier_stokes.h
  include/solvers/gls_navier_stokes.h
  include/solvers/mf_navier_stokes.h
  source/core/parameters.cc
  source/fem-dem/gls_vans.cc
  source/solvers/gd_navier_stokes.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/gls_nitsche_navier_stokes.cc
  source/solvers/mf_navier_stokes.cc
  tests/core/non_linear_test_system_01.h
Labels: Ready for review

#1103 Correct DCDD stabilization in VOF
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.output
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_ht_adapt-dissipation.output
  applications_tests/lethe-fluid/gls_vof_hydrostat_initial_refine.output
  applications_tests/lethe-fluid/gls_vof_hydrostat_mesh-adapt.output
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_static_droplet_surface_tension_force_with_tanh_filter.output
  applications_tests/lethe-fluid/gls_vof_tanh_filter.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_vof_weakly_compressible_flow.output
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  doc/source/theory/multiphysics/vof.rst
  source/solvers/vof_assemblers.cc
Labels: Reviewed and ready to merge, Quick fix

#1105 Fixing the random output file
  contrib/preprocessing/extract-particles-properties-from-vtu.py
Labels: Reviewed and ready to merge, Quick fix
