Repository chaos-polymtl/lethe, pull requests merged in 2024-11, with the labels that each got.

#1339 Replace the norm by the scalar product with the normal vector
  CHANGELOG.md
  include/dem/force_chains_visualization.h
Labels: Quick fix, Ready for review

#1340 Improve cavity example
  doc/source/examples/incompressible-flow/2d-lid-driven-cavity-flow/lid-driven-cavity-flow.rst
  examples/incompressible-flow/2d-lid-driven-cavity/Reynolds_7500/cavity.prm
  examples/incompressible-flow/2d-lid-driven-cavity/Reynolds_7500/post_process_Reynolds_7500.py
Labels: Ready for review, Example, Next release

#1299 Add new sharp-edge example: Drag around a cylinder
  doc/source/examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/cylindrical-particle-drag-evaluation-with-sharp-interface.rst
  doc/source/examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/images/cylindrical-particle-drag-evaluation-with-sharp-interface-CD-Re-study.png
  doc/source/examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/images/cylindrical-particle-drag-evaluation-with-sharp-interface-case.png
  doc/source/examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/images/cylindrical-particle-drag-evaluation-with-sharp-interface-pressure.png
  doc/source/examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/images/cylindrical-particle-drag-evaluation-with-sharp-interface-velocity.png
  doc/source/examples/sharp-immersed-boundary/incompressible-flow.rst
  doc/source/examples/sharp-immersed-boundary/sharp-immersed-boundary.rst
  examples/sharp-immersed-boundary/cylindrical-particle-drag-evaluation-with-sharp-interface/cylindrical-particle-drag-evaluation-with-sharp-interface.prm
Labels: Documentation, Reviewed and ready to merge

#1337 Improve cylinder example
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  examples/incompressible-flow/2d-flow-around-cylinder/calculate_drag_coefficient.py
  examples/incompressible-flow/2d-flow-around-cylinder/cylinder-structured.geo
  examples/incompressible-flow/2d-flow-around-cylinder/cylinder.prm
Labels: Ready for review, Example, Next release

#1346 Update flow around sphere example
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/flow-around-sphere.rst
  doc/source/examples/incompressible-flow/3d-flow-around-sphere/images/example-4-setup.png
  examples/incompressible-flow/3d-flow-around-sphere/sphere-150.prm
Labels: Ready for review, Example, Next release

#1344 Simplify the linear solver for the taylor-couette
  examples/incompressible-flow/2d-taylor-couette/taylor-couette.prm
Labels: Ready for review, Next release

#1345 Improve taylor-couette Nitsche
  doc/source/examples/incompressible-flow/2d-taylor-couette-flow-nitsche/2d-taylor-couette-flow-nitsche.rst
  examples/incompressible-flow/2d-taylor-couette-nitsche/adaptive-taylor-couette-nitsche.prm
  examples/incompressible-flow/2d-taylor-couette-nitsche/uniform-taylor-couette-nitsche.prm
Labels: Ready for review, Next release

#1342 Force chains, add the arbitrary rule
  CHANGELOG.md
  include/dem/force_chains_visualization.h
  source/dem/dem.cc
  source/dem/force_chains_visualization.cc
Labels: Quick fix, WIP, Ready for review

#1341 Refactor output of paraview files and time step calculation
  CHANGELOG.md
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.mpirun=1.output
  applications_tests/lethe-fluid/taylor-green-vortex-restart-bdf1-adaptive.mpirun=1.output
  applications_tests/lethe-fluid/vof-velocity-extrapolation.output
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/parameters/cfd/simulation_control.rst
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra25k.prm
  include/core/parameters.h
  include/core/simulation_control.h
  source/core/parameters.cc
  source/core/simulation_control.cc
  source/solvers/navier_stokes_base.cc
  tests/core/simulation_control_01.cc
  tests/core/simulation_control_02.cc
  tests/core/simulation_control_03.cc
  tests/core/simulation_control_03.output
  tests/core/simulation_control_04.cc
  tests/core/simulation_control_05.cc
  tests/core/simulation_control_06.cc
  tests/core/simulation_control_06.output
  tests/core/specific_heat_phase_change_01.cc
  tests/solvers/average_velocities_01.cc
  tests/solvers/average_velocities_02.cc
  tests/solvers/average_velocities_02.output
  tests/solvers/average_velocities_03.cc
  tests/solvers/reynolds_stress_01.cc
  tests/solvers/reynolds_stress_02.cc
  tests/solvers/reynolds_stress_02.output
  tests/solvers/reynolds_stress_03.cc
Labels: Enhancement, Ready for review

#1349 Update periodic hills example
  doc/source/examples/incompressible-flow/3d-flow-over-periodic-hills/3d-flow-over-periodic-hills.rst
  examples/incompressible-flow/3d-periodic-hills/periodic-hills.prm
Labels: Ready for review, Example, Next release

#1351 Bouncing particle example
  doc/source/examples/dem/bouncing-particle/bouncing-particle.rst
  examples/dem/3d-bouncing-particle/bouncing_particle_case_generator.py
Labels: Quick fix, Ready for review, Example, Next release

#1350 Packing in circle example
  doc/source/examples/dem/packing-in-circle/packing-in-circle.rst
  examples/dem/2d-packing-in-circle/packing-in-circle.prm
Labels: Ready for review, Next release

#1354 Improve granular-dam-break
  doc/source/examples/dem/granular-dam-break/granular-dam-break.rst
  examples/dem/3d-dam-break/granular-dam-break-H-40cm.prm
  examples/dem/3d-dam-break/granular-dam-break.prm
Labels: Quick fix, Ready for review, Next release

#1353 Plane composite example: tested, fixed typos and formatting
  doc/source/examples/sharp-immersed-boundary/simple-plane-model-from-composite/simple-plane-model-from-composite.rst
  examples/sharp-immersed-boundary/simple-plane-model-from-composite/plane.composite
  examples/sharp-immersed-boundary/simple-plane-model-from-composite/plane.prm
Labels: Ready for review, Example, Next release

#1358 Fix typo and broken link
  doc/source/examples/dem/oblique-wall-impact/oblique-wall-impact.rst
Labels: Quick fix, Ready for review, Next release

#1348 Update transient flow around cylinder example
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-cylinder/2d-transient-flow-around-cylinder.rst
  examples/incompressible-flow/2d-transient-flow-around-cylinder/cylinder-structured.msh
  examples/incompressible-flow/2d-transient-flow-around-cylinder/cylinder.prm
Labels: Ready for review, Next release

#1357 Updated example: static mixer using RBF representation
  doc/source/examples/sharp-immersed-boundary/3d-rbf-static-mixer/3d-rbf-static-mixer.rst
  examples/sharp-immersed-boundary/3d-rbf-static-mixer/lethe_sharp_simulation/flow_in_long_mixer.prm
Labels: Ready for review, Example, Next release

#1363 Update TGV example in documentation
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-based.prm
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-free.prm
Labels: Ready for review, Example, Next release

#1359 Update: Silo example
  doc/source/examples/dem/silo/silo.rst
Labels: Quick fix, Ready for review, Next release

#1361 Review PBT impeller examples
  doc/source/examples/incompressible-flow/3d-nitsche-mixer-with-pbt-impeller/nitsche-mixer-with-pbt-impeller.rst
  doc/source/examples/sharp-immersed-boundary/3d-composite-mixer-with-pbt-impeller/3d-composite-mixer-with-pbt-impeller.rst
  doc/source/examples/sharp-immersed-boundary/3d-opencascade-mixer-with-pbt-impeller/3d-opencascade-mixer-with-pbt-impeller.rst
  doc/source/examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/inclined-3d-composite-mixer-with-pbt-impeller.rst
  examples/sharp-immersed-boundary/3d-composite-mixer-with-pbt-impeller/impeller.composite
  examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/mixer.prm
Labels: Ready for review, Example, Next release

#1364 Examples update for particle sedimentation and Rayleigh-Benard
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  doc/source/examples/sharp-immersed-boundary/sedimentation-1-particle/sedimentation-1-particle.rst
  doc/source/examples/sharp-immersed-boundary/sedimentation-64-particles/sedimentation-64-particles.rst
  doc/source/installation/regular_installation.rst
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra25k.prm
  examples/sharp-immersed-boundary/sedimentation-1-particle/sedimentation-1-particle.prm
  examples/sharp-immersed-boundary/sedimentation-64-particles/sedimentation-64-particles.prm
Labels: Question, Ready for review, Example, Next release

#1343 Fix bugs: changing time step after restart and tracer tanh model
  CHANGELOG.md
  include/core/simulation_control.h
  include/core/tracer_diffusivity_model.h
  include/solvers/multiphysics_interface.h
  include/solvers/tracer_scratch_data.h
  source/core/simulation_control.cc
  source/fem-dem/fluid_dynamics_sharp.cc
  source/solvers/multiphysics_interface.cc
  source/solvers/tracer.cc
Labels: Bug, Ready for review

#1366 Stefan example: Update documentation and simplify example
  doc/source/examples/multiphysics/stefan-problem/stefan-problem.rst
  examples/multiphysics/stefan-problem/stefan.prm
Labels: Documentation, Ready for review, Next release

#1365 Update Rayleigh-Plateau example
  doc/source/examples/multiphysics/rayleigh-plateau-instability/images/initial-state-without-gravity.svg
  doc/source/examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-instability.rst
  examples/multiphysics/rayleigh-plateau-instability/denner-et-al-2022-We020.csv
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10.tpl
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10_delta0_20/rayleigh-plateau-J1-We020-Oh0_10_delta0_20.prm
Labels: Reviewed and ready to merge, Next release

#1367 Fix specific heat model with bdf2
  CHANGELOG.md
  include/core/specific_heat_model.h
Labels: Quick fix, Ready for review

#1368 Dem examples
  doc/source/examples/dem/bunny-drill/bunny-drill.rst
  doc/source/examples/dem/granuheap/granuheap.rst
  examples/dem/3d-granuheap/granuheap.prm
  examples/dem/3d-granuheap/granuheap_multicase.prm
  examples/dem/3d-granuheap/im/dummy_file.txt
  examples/dem/3d-granuheap/post_processing_multicase.py
Labels: Documentation, Reviewed and ready to merge, Example

#1370 Examples update for gas-solid fluidized and spouted-bed
  doc/source/examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.rst
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-bed/gas-solid-spouted-bed.prm
Labels: Documentation, Ready for review, Example, Next release

#1372 Examples update for concentric-heat-exchanger and melting-cavity
  doc/source/examples/multiphysics/concentric-heat-exchanger/concentric-heat-exchanger.rst
  doc/source/examples/multiphysics/melting-cavity/images/comparison-melted-volume-fraction.png
  doc/source/examples/multiphysics/melting-cavity/images/melted-volume-fraction.png
  doc/source/examples/multiphysics/melting-cavity/images/xmax-t.png
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  examples/multiphysics/concentric-heat-exchanger/concentric-heat-exchanger.prm
  examples/multiphysics/concentric-heat-exchanger/plot_temperature_over_line.py
  examples/multiphysics/melting-cavity/compare-melting-cavity.py
  examples/multiphysics/melting-cavity/melting-cavity-darcy.prm
  examples/multiphysics/melting-cavity/melting-cavity-stasis-constraint.prm
  examples/multiphysics/melting-cavity/melting-cavity.prm
  examples/multiphysics/melting-cavity/melting-cavity.py
Labels: Ready for review, Rebased, Example, Next release

#1377 Minor corrections to turbulent taylor couette example
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
Labels: Ready for review, Example, Next release

#1380 Update and proofread bubble examples
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/static-bubble/images/mesh-convergence-study-order.png
  doc/source/examples/multiphysics/static-bubble/images/mesh-convergence-study-time.png
  doc/source/examples/multiphysics/static-bubble/static-bubble.rst
  examples/multiphysics/static-bubble/static-bubble.prm
Labels: Documentation, Ready for review

#1347 Dem particle weight
  CHANGELOG.md
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  doc/source/parameters/dem/model_parameters.rst
  source/core/parameters_lagrangian.cc
Labels: Reviewed and ready to merge, Quick fix

#1384 Ahmed body example renewal
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/2d-transient-flow-around-ahmed-body.rst
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re28-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re28-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re288-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re288-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-speed-t05.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/Re720-speed-t4.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/ahmed-mesh.png
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-1-ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-2-ahmed.jfif
  doc/source/examples/incompressible-flow/2d-transient-flow-around-ahmed-body/images/video-3-ahmed.jfif
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body-simplex/Ahmed-Body-20-2D.geo
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body-simplex/Ahmed-Body-20-2D.msh
  examples/incompressible-flow/2d-transient-flow-around-ahmed-body-simplex/ahmed.prm
Labels: Documentation, Reviewed and ready to merge, Rebased, Example

#1386 Test without void fraction bounding
  applications_tests/lethe-fluid-vans/beetstra_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/beetstra_packed_bed.prm
  applications_tests/lethe-fluid-vans/dallavalle_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/dallavalle_packed_bed.prm
  applications_tests/lethe-fluid-vans/difelice_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/difelice_packed_bed.prm
  applications_tests/lethe-fluid-vans/gidaspow_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/gidaspow_packed_bed.prm
  applications_tests/lethe-fluid-vans/kochhill_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/kochhill_packed_bed.prm
  applications_tests/lethe-fluid-vans/pcm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/pcm_packed_bed.prm
  applications_tests/lethe-fluid-vans/qcm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/qcm_packed_bed.prm
  applications_tests/lethe-fluid-vans/rong_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/rong_packed_bed.prm
  applications_tests/lethe-fluid-vans/spm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/spm_packed_bed.prm
Labels: Reviewed and ready to merge, Rebased, Refactoring

#1387 Plate discharge examples
  doc/source/examples/dem/plate-discharge/plate-discharge.rst
  examples/dem/3d-plate-discharge/plate-discharge_post-processing.py
Labels: Documentation, Reviewed and ready to merge, Quick fix

#1378 Update laser examples
  doc/source/examples/multiphysics/heat-transfer.rst
  doc/source/examples/multiphysics/laser-heating/images/geometry.png
  doc/source/examples/multiphysics/laser-heating/laser-heating.rst
  doc/source/examples/multiphysics/laser-melt-pool/images/laser-phasechange.png
  doc/source/examples/multiphysics/laser-melt-pool/laser-melt-pool.rst
  doc/source/examples/multiphysics/multiphysics.rst
  doc/source/examples/multiphysics/static-irradiation/images/new-benchmark.png
  doc/source/examples/multiphysics/static-irradiation/static-irradiation.rst
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
  examples/multiphysics/laser-heating/laser-heating.prm
  examples/multiphysics/laser-heating/output/dummy
  examples/multiphysics/laser-melt-pool/laser-melt-pool.prm
  examples/multiphysics/laser-melt-pool/output/dummy
  examples/multiphysics/laser-powder-bed-fusion/1D/benchmark.prm
  examples/multiphysics/laser-powder-bed-fusion/3D/benchmark.prm
  examples/multiphysics/laser-powder-bed-fusion/mesh/3d-benchmark.msh
  examples/multiphysics/static-irradiation/2D/static-irradiation.prm
  examples/multiphysics/static-irradiation/mesh/bare-plate-2D.msh
Labels: Documentation, Ready for review

#1385 Pneumatic conveying example renewal
  doc/source/examples/unresolved-cfd-dem/dense-pneumatic-conveying/dense-pneumatic-conveying.rst
Labels: Documentation, Ready for review, Rebased, Example

#1389 Update flow past a backward facing step example
  doc/source/examples/incompressible-flow/2d-backward-facing-step/2d-backward-facing-step.rst
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/0th-mesh.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/4th-mesh.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100-error-analysis.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100-mesh-refinement.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100-poiseuille.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100-zoom.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds1000-poiseuille.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds1000-zoom.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds1000.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds1000_profile.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/Reynolds100_profile.png
  doc/source/examples/incompressible-flow/2d-backward-facing-step/image/backward-facing-step-description.png
  examples/incompressible-flow/2d-backward-facing-step/Reynolds100/Reynolds100_steady.prm
  examples/incompressible-flow/2d-backward-facing-step/Reynolds1000/Reynolds1000_steadybdf.prm
  examples/incompressible-flow/2d-backward-facing-step/bisection.py
  examples/incompressible-flow/2d-backward-facing-step/reattachment_length.py
  examples/incompressible-flow/2d-backward-facing-step/velocity_distribution.py
Labels: Ready for review, Example, Next release

#1391 Rotating drum example
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  examples/dem/3d-rotating-drum/load-rotating-drum.prm
  examples/dem/3d-rotating-drum/rotating-drum.prm
Labels: Documentation, Quick fix, Ready for review, Example
