Repository chaos-polymtl/lethe, pull requests merged in 2024-09, with the labels that each got.

#1268 Make dcdd shock capture optional for heat transfer
  CHANGELOG.md
  applications_tests/lethe-fluid/cavity_ht_average_velocity_as_initial_condition.mpirun=1.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.output
  applications_tests/lethe-fluid/heat_transfer_ale_bar.output
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_phase_change_constrain_solid_domain_with_plane.output
  applications_tests/lethe-fluid/heat_transfer_stefan.output
  applications_tests/lethe-fluid/heat_transfer_stefan_bdf2.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/phase_change_darcy.output
  applications_tests/lethe-fluid/phase_change_viscosity.output
  applications_tests/lethe-fluid/time_dependent_boundaries_heat_transfer.output
  applications_tests/lethe-fluid/vof_phase_change_darcy.output
  doc/source/parameters/cfd/stabilization.rst
  include/core/parameters.h
  include/solvers/heat_transfer_assemblers.h
  source/core/parameters.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
Labels: Reviewed and ready to merge

#1276 Add parameter to rescale mesh once it has been read from input files
  applications_tests/lethe-fluid/taylorcouette_gls_scaled.output
  applications_tests/lethe-fluid/taylorcouette_gls_scaled.prm
  doc/source/parameters/cfd/mesh.rst
  include/core/parameters.h
  source/core/grids.cc
  source/core/parameters.cc
Labels: Enhancement, Ready for review

#1277 Added documentation for mesh parameters
  CHANGELOG.md
  doc/source/parameters/cfd/mesh.rst
Labels: Documentation, Ready for review

#1275 Function boundary conditions weakly imposed in the matrix-free solver
  applications_tests/lethe-fluid-matrix-free/couette_function_weak.output
  applications_tests/lethe-fluid-matrix-free/couette_function_weak.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms2d_fe2_weak.output
  applications_tests/lethe-fluid-matrix-free/mms2d_fe2_weak.prm
  include/solvers/fluid_dynamics_matrix_free_operators.h
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Enhancement, Reviewed and ready to merge

#1280 change upload artifact from v2 to v4
  .github/workflows/doc-github-pages.yml
Labels: Ready for review, CI

#1279 Modify cell diameter function
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/periodic_particles_qcm_opposite_flow.mpirun=2.output
  applications_tests/lethe-fluid-sharp/coupled_moving_stokes.mpirun=2.output
  applications_tests/lethe-fluid/taylorcouette-unstructured_gls.mpirun=1.output
  applications_tests/lethe-fluid/taylorcouette_boundary_ref.output
  applications_tests/lethe-fluid/taylorcouette_gls.mpirun=2.output
  applications_tests/lethe-fluid/taylorcouette_gls.output
  applications_tests/lethe-fluid/taylorcouette_gls_scaled.output
  include/core/utilities.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof.h
  include/solvers/vof_scratch_data.h
  source/fem-dem/fluid_dynamics_sharp.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
  source/solvers/postprocessing_cfd.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Bug, Reviewed and ready to merge, Rebased

#1285 Update name of SmartPointer class
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Quick fix, CI

#1274 Add new scaling parameters for the Cahn-Hilliard model
  CHANGELOG.md
  include/core/dimensionality.h
  include/core/parameters.h
  include/core/parameters_multiphysics.h
  include/solvers/simulation_parameters.h
  source/core/dimensionality.cc
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
Labels: Enhancement, Reviewed and ready to merge

#1286 Fix bdf extrapolation bug
  CHANGELOG.md
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.mpirun=1.output
  applications_tests/lethe-fluid/vof-velocity-extrapolation.output
  applications_tests/lethe-fluid/vof-velocity-extrapolation.prm
  include/core/bdf.h
  include/solvers/vof_scratch_data.h
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
Labels: Bug, Reviewed and ready to merge, Rebased

#1290 Minor corrections in boundary conditions documentation
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
  doc/source/theory/multiphysics/fluid_dynamics/fem_formulation.rst
Labels: Documentation, Quick fix

#1287 Add outlet boundary condition to the matrix free operator
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/cylinder_close_outlet.msh
  applications_tests/lethe-fluid-matrix-free/cylinder_outlet_bc.output
  applications_tests/lethe-fluid-matrix-free/cylinder_outlet_bc.prm
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/cylinder_close_outlet.msh
  applications_tests/lethe-fluid/cylinder_outlet_bc.output
  applications_tests/lethe-fluid/cylinder_outlet_bc.prm
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
  include/solvers/fluid_dynamics_matrix_free_operators.h
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Ready for review

#1295 Remove unused parameter in cylinder test
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid/cylinder_gls.prm
Labels: Quick fix, Ready for review

#1294 Correct update of solutions for multiphysics in matrix-free application
  CHANGELOG.md
  include/solvers/fluid_dynamics_block.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/navier_stokes_base.h
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/navier_stokes_base.cc
Labels: Reviewed and ready to merge
