Repository chaos-polymtl/lethe, pull requests merged in 2024-10, with the labels that each got.

#1300 Fix simulation restart when using averaging
  CHANGELOG.md
  include/solvers/postprocessing_velocities.h
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_velocities.cc
Labels: Bug

#1309 Add a checkbox in PR templates regarding the license in the header
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_documentation.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_example.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_new-feature.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_refactoring.md
Labels: Ready for review

#1310 Uniformize postprocess output precision
  CHANGELOG.md
  applications_tests/lethe-fluid-block/cylinder_carreau_gd.mpirun=1.output
  applications_tests/lethe-fluid-block/taylorcouette_gd.mpirun=2.output
  applications_tests/lethe-fluid-block/taylorcouette_gd.output
  applications_tests/lethe-fluid-block/taylorcouette_gd_dimensions.output
  applications_tests/lethe-fluid-matrix-free/couette_function_weak.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-nitsche/noslip33_simplex.mpirun=2.output
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.mpirun=1.output
  applications_tests/lethe-fluid-particles/dynamic_contact_search.mpirun=1.output
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.mpirun=1.output
  applications_tests/lethe-fluid-particles/particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.mpirun=1.output
  applications_tests/lethe-fluid-particles/spouted_bed_load_balancing.mpirun=2.output
  applications_tests/lethe-fluid-sharp/coupled_moving_stokes.mpirun=2.output
  applications_tests/lethe-fluid-sharp/moving_ib_gls.output
  applications_tests/lethe-fluid-sharp/moving_ib_gls_poisson.output
  applications_tests/lethe-fluid-sharp/moving_rectangle.output
  applications_tests/lethe-fluid-sharp/pp_lubrication_test.output
  applications_tests/lethe-fluid-sharp/pw_contact_test.output
  applications_tests/lethe-fluid-sharp/spinning_cone.output
  applications_tests/lethe-fluid-sharp/two_non_sphere_contact.output
  applications_tests/lethe-fluid-vans/beetstra_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/dallavalle_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/difelice_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/gidaspow_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/kochhill_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/pcm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/qcm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/rong_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid-vans/spm_packed_bed.mpirun=1.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect.output
  applications_tests/lethe-fluid/gls_droplet_marangoni_effect_without_dcdd_stabilization.output
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.mpirun=1.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain.output
  applications_tests/lethe-fluid/heat_transfer_vof_phase_change_constrain_solid_domain_with_plane.output
  applications_tests/lethe-fluid/taylorcouette_boundary_ref.output
  applications_tests/lethe-fluid/taylorcouette_gls.mpirun=2.output
  applications_tests/lethe-fluid/taylorcouette_gls.output
  applications_tests/lethe-fluid/taylorcouette_gls_scaled.output
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  applications_tests/lethe-fluid/vof-velocity-extrapolation.output
  source/core/simulation_control.cc
  source/core/utilities.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/fluid_dynamics_sharp.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/fluid_dynamics_nitsche.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Quick fix, Ready for review

#1311 Remove colorized cylinder shell parameter
  doc/source/parameters/cfd/mesh.rst
  include/core/parameters.h
  source/core/parameters.cc
Labels: Bug, Ready for review

#1313 Move boundary conditions of all fluid dynamics solvers to base class
  CHANGELOG.md
  include/solvers/fluid_dynamics_matrix_based.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/navier_stokes_base.h
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/navier_stokes_base.cc
Labels: Refactoring

#1314 Add matrix free preprint to publication list
  doc/source/publications.rst
Labels: Documentation, Ready for review

#1316 Dem fixing resize containers
  CHANGELOG.md
  applications_tests/lethe-particles/resize_containers.mpirun=2.out
  applications_tests/lethe-particles/resize_containers.prm
  source/dem/dem.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: Bug, Quick fix, Ready for review

#1315 Fixed DMT
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/moving_solid_surface_dmt.mpirun=1.output
  applications_tests/lethe-particles/moving_solid_surface_dmt.prm
  applications_tests/lethe-particles/moving_solid_surface_hmlo.mpirun=1.output
  applications_tests/lethe-particles/moving_solid_surface_hmlo.prm
  applications_tests/lethe-particles/moving_solid_surface_jkr.mpirun=1.output
  applications_tests/lethe-particles/moving_solid_surface_jkr.prm
  source/dem/particle_wall_dmt_force.cc
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_nonlinear_force.cc
Labels: Bug, Beginner's work, Quick fix, Ready for review

#1323 Add missing flag
  CHANGELOG.md
  source/solvers/tracer.cc
Labels: Reviewed and ready to merge

#1322 Change default coarse grid solver for the geometric multigrid
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/couette_function_weak.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_outlet_bc.prm
  applications_tests/lethe-fluid-matrix-free/heat_transfer_high_pe_stab_gls.prm
  applications_tests/lethe-fluid-matrix-free/mms2d_fe2_weak.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.prm
  applications_tests/lethe-fluid-matrix-free/taylor_couette_2d_local_ref.prm
  applications_tests/lethe-fluid-matrix-free/turbulent_taylor_couette_restart.prm
  doc/source/parameters/cfd/linear_solver_control.rst
  source/core/parameters.cc
Labels: Reviewed and ready to merge

#1319 Run MFNavierStokesPreconditionGMG in float
  CHANGELOG.md
  CMakeLists.txt
  include/solvers/fluid_dynamics_matrix_free.h
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Ready for review

#1317 Prevent refinement of the boundary when using kelly refinement
  applications_tests/lethe-fluid/fixed_boundary_mesh_for_kelly.output
  applications_tests/lethe-fluid/fixed_boundary_mesh_for_kelly.prm
  doc/source/parameters/cfd/mesh.rst
  doc/source/parameters/cfd/mesh_adaptation_control.rst
  include/core/parameters.h
  source/core/parameters.cc
  source/solvers/navier_stokes_base.cc
Labels: Enhancement, Reviewed and ready to merge

#1320 Add Discontinuous Galerkin capabilities to the Tracer auxiliary physics
  CHANGELOG.md
  applications_tests/lethe-fluid/dg_tracer_advection_tanh.output
  applications_tests/lethe-fluid/dg_tracer_advection_tanh.prm
  applications_tests/lethe-fluid/dg_tracer_circular_advection.mpirun=2.output
  applications_tests/lethe-fluid/dg_tracer_circular_advection.prm
  applications_tests/lethe-fluid/dg_tracer_circular_advection_adapt.output
  applications_tests/lethe-fluid/dg_tracer_circular_advection_adapt.prm
  applications_tests/lethe-fluid/dg_tracer_diffusion_mms_2d.output
  applications_tests/lethe-fluid/dg_tracer_diffusion_mms_2d.prm
  applications_tests/lethe-fluid/dg_tracer_diffusion_residual.output
  applications_tests/lethe-fluid/dg_tracer_diffusion_residual.prm
  applications_tests/lethe-fluid/dg_tracer_high_pe.output
  applications_tests/lethe-fluid/dg_tracer_high_pe.prm
  applications_tests/lethe-fluid/dg_tracer_pipe.output
  applications_tests/lethe-fluid/dg_tracer_pipe.prm
  applications_tests/lethe-fluid/dg_tracer_sharp_initial_conditions.output
  applications_tests/lethe-fluid/dg_tracer_sharp_initial_conditions.prm
  doc/source/parameters/cfd/fem.rst
  doc/source/parameters/cfd/stabilization.rst
  include/core/boundary_conditions.h
  include/core/multiphysics.h
  include/core/parameters.h
  include/core/utilities.h
  include/solvers/copy_data.h
  include/solvers/tracer.h
  include/solvers/tracer_assemblers.h
  include/solvers/tracer_scratch_data.h
  source/core/parameters.cc
  source/solvers/tracer.cc
  source/solvers/tracer_assemblers.cc
  source/solvers/tracer_scratch_data.cc
Labels: Enhancement, Ready for review

#1329 Use MGCoarseGridApplyOperator class in the multigrid preconditioners
  include/solvers/fluid_dynamics_matrix_free.h
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Quick fix, Ready for review

#1327 Double restart
  CHANGELOG.md
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/circle_restart_files/circle_restart.checkpoint_controller
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.insertion_object
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.particles
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.pvdhandler
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.simulationcontrol
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.triangulation
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.triangulation.info
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.triangulation_fixed.data
  applications_tests/lethe-particles/circle_restart_files/circle_restart_0.triangulation_variable.data
  applications_tests/lethe-particles/moving_receptacle_files/restart.checkpoint_controller
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.insertion_object
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.particles
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.pvdhandler
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.simulationcontrol
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.solid_object.00.displacement
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.solid_object.00.dof
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.solid_object.00.pvdhandler
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.triangulation
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.triangulation.info
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.triangulation_fixed.data
  applications_tests/lethe-particles/moving_receptacle_files/restart_0.triangulation_variable.data
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.checkpoint_controller
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.insertion_object
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.particles
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.pvdhandler
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.simulationcontrol
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.triangulation
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.triangulation.info
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.triangulation_fixed.data
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart_0.triangulation_variable.data
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart.checkpoint_controller
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.insertion_object
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.particles
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.pvdhandler
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.simulationcontrol
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.triangulation
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.triangulation.info
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.triangulation_fixed.data
  applications_tests/lethe-particles/sliding_restart_files/sliding_restart_0.triangulation_variable.data
  include/core/checkpoint_control.h
  include/dem/dem.h
  include/dem/read_checkpoint.h
  include/dem/write_checkpoint.h
  source/core/CMakeLists.txt
  source/dem/dem.cc
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
Labels: Good first issue, Reviewed and ready to merge
