Repository chaos-polymtl/lethe, pull requests merged in 2024-06, with the labels that each got.

#1166 Add Rayleigh-Plateau example to Multiphysics diagram
  doc/source/examples/multiphysics/multiphysics.rst
Labels: Documentation, Quick fix, Rebased

#1165 Update the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_bug-fix.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_documentation.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_example.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_new-feature.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_refactoring.md
  CONTRIBUTING.md
  doc/source/contributing.rst
Labels: Maintenance, Documentation, Ready for review

#1147 Create a postprocessing function for cfd-dem
  applications_tests/lethe-fluid-particles/CMakeLists.txt
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.mpirun=1.output
  applications_tests/lethe-fluid-particles/conserve_phase_volumes.prm
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.particles
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.pvdhandler
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.simulationcontrol
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.triangulation
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.triangulation.info
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.triangulation_fixed.data
  applications_tests/lethe-fluid-particles/conserve_phase_volumes_files/dem.triangulation_variable.data
  doc/source/parameters/cfd/post_processing.rst
  include/core/parameters.h
  include/fem-dem/cfd_dem_coupling.h
  include/fem-dem/postprocessing_cfd_dem.h
  source/core/parameters.cc
  source/fem-dem/CMakeLists.txt
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/postprocessing_cfd_dem.cc
Labels: Ready for review, Hackathon

#1164 Dem force chains
  applications_tests/lethe-particles/pp_jkr_equilibrium.prm
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/force_chains_visualization.h
  include/dem/set_particle_particle_contact_force_model.h
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/force_chains_visualization.cc
  source/dem/set_particle_particle_contact_force_model.cc
Labels: Reviewed and ready to merge, Rebased, Post-processing

#1156 Development of the multiphysics section of the documentation
  doc/source/theory/multiphase/cfd/cahn-hilliard.rst
  doc/source/theory/multiphase/cfd/images/tanh-solution.png
  doc/source/theory/multiphysics/electromagnetism/electromagnetism.rst
  doc/source/theory/multiphysics/electromagnetism/time_harmonic.rst
  doc/source/theory/multiphysics/electromagnetism/time_harmonic_weak_form.rst
  doc/source/theory/multiphysics/heat_transfer/heat_equation.rst
Labels: Documentation, Reviewed and ready to merge, Hackathon

#1167 Add cylinder manifold
  CHANGELOG.md
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/cylinder_manifold.mpirun=2.output
  applications_tests/lethe-fluid/cylinder_manifold.msh
  applications_tests/lethe-fluid/cylinder_manifold.prm
  applications_tests/lethe-fluid/taylorcouette-unstructured_gls.prm
  contrib/utilities/check_parameter_files_in_examples.sh
  doc/source/examples/incompressible-flow/2d-flow-around-cylinder/2d-flow-around-cylinder.rst
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/images/coarse_cylinder.png
  doc/source/parameters/cfd/images/fine_cylinder_manifold.png
  doc/source/parameters/cfd/manifolds.rst
  examples/incompressible-flow/2d-flow-around-cylinder/cylinder.prm
  examples/incompressible-flow/2d-transient-flow-around-cylinder/cylinder.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-0.1.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-150.prm
  examples/incompressible-flow/3d-flow-around-sphere/sphere-adapt.prm
  include/core/manifolds.h
  include/core/utilities.h
  source/core/manifolds.cc
  source/core/utilities.cc
Labels: Enhancement, Reviewed and ready to merge

#1170 Migrate include after ifdefs in core and solver h
  include/core/auxiliary_math_functions.h
  include/core/boundary_conditions.h
  include/core/dem_properties.h
  include/core/evaporation_model.h
  include/core/grids.h
  include/core/ib_particle.h
  include/core/ib_stencil.h
  include/core/inexact_newton_non_linear_solver.h
  include/core/kinsol_newton_non_linear_solver.h
  include/core/lethe_grid_tools.h
  include/core/manifolds.h
  include/core/mesh_controller.h
  include/core/parameters_multiphysics.h
  include/core/periodic_hills_grid.h
  include/core/phase_change.h
  include/core/physics_solver.h
  include/core/simulation_control.h
  include/core/solid_base.h
  include/core/solid_objects_parameters.h
  include/core/solutions_output.h
  include/core/tensors_and_points_dimension_manipulation.h
  include/core/utilities.h
  include/solvers/cahn_hilliard.h
  include/solvers/cahn_hilliard_assemblers.h
  include/solvers/cahn_hilliard_filter.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/copy_data.h
  include/solvers/flow_control.h
  include/solvers/gls_nitsche_navier_stokes.h
  include/solvers/initial_conditions.h
  include/solvers/isothermal_compressible_navier_stokes_assembler.h
  include/solvers/isothermal_compressible_navier_stokes_vof_assembler.h
  include/solvers/navier_stokes_assemblers.h
  include/solvers/navier_stokes_cahn_hilliard_assemblers.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/navier_stokes_vof_assemblers.h
  include/solvers/postprocessing_cfd.h
  include/solvers/postprocessing_velocities.h
  include/solvers/postprocessors.h
  include/solvers/postprocessors_smoothing.h
  include/solvers/simulation_parameters.h
  include/solvers/stabilization.h
  include/solvers/tracer.h
  include/solvers/tracer_assemblers.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof.h
  include/solvers/vof_assemblers.h
  include/solvers/vof_scratch_data.h
Labels: Refactoring

#1169 Dem volume solid objects
  CHANGELOG.md
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/load_balancing_solid_object.prm
  applications_tests/lethe-particles/moving_solid_surface.mpirun=1.output
  applications_tests/lethe-particles/moving_solid_surface.prm
  applications_tests/lethe-particles/moving_solid_surface_files/square.geo
  applications_tests/lethe-particles/moving_solid_surface_files/square.msh
  applications_tests/lethe-particles/restart_moving_receptacle.prm
  applications_tests/lethe-particles/solid_surface.output
  applications_tests/lethe-particles/solid_surface.prm
  doc/source/examples/dem/bunny-drill/bunny-drill.rst
  doc/source/examples/dem/granular-dam-break/granular-dam-break.rst
  doc/source/examples/dem/granular-mixer/granular-mixer.rst
  doc/source/parameters/dem/dem.rst
  doc/source/parameters/dem/floating_mesh.rst
  doc/source/parameters/dem/insertion_info.rst
  doc/source/parameters/dem/solid_objects.rst
  examples/dem/3d-bunny-drill/bunny-drill-loading.prm
  examples/dem/3d-bunny-drill/bunny-drill.prm
  examples/dem/3d-dam-break/granular-dam-break-H-40cm.prm
  examples/dem/3d-dam-break/granular-dam-break.prm
  examples/dem/3d-granular-mixer/granular-mixer.prm
  include/core/serial_solid.h
  include/core/solid_objects_parameters.h
  include/dem/data_containers.h
  include/dem/dem.h
  include/dem/dem_contact_manager.h
  include/dem/particle_wall_broad_search.h
  include/dem/read_checkpoint.h
  include/fem-dem/cfd_dem_coupling.h
  source/core/serial_solid.cc
  source/dem/dem.cc
  source/dem/dem_contact_manager.cc
  source/dem/particle_wall_broad_search.cc
  source/dem/read_checkpoint.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/volume_solid_object_displacement.cc
  tests/dem/volume_solid_object_displacement.output
Labels: Documentation, Reviewed and ready to merge

#1175 Fix partial slip documentation
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
Labels: Documentation, Quick fix, Ready for review

#1172 Dem force chain ghost
  doc/source/parameters/dem/post-processing.rst
  include/dem/dem.h
  include/dem/force_chains_visualization.h
  source/dem/dem.cc
  source/dem/force_chains_visualization.cc
Labels: Documentation, Ready for review, Post-processing

#1174 Checkpointing current_file_id for file insertion
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/restart_file_insertion.mpirun=1.output
  applications_tests/lethe-particles/restart_file_insertion.prm
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.insertion_object
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.particles
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.pvdhandler
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.simulationcontrol
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.triangulation
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.triangulation.info
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.triangulation_fixed.data
  applications_tests/lethe-particles/restart_file_insertion_files/insertion_file_restart.triangulation_variable.data
  applications_tests/lethe-particles/restart_file_insertion_files/particles_00.input
  applications_tests/lethe-particles/restart_file_insertion_files/particles_01.input
  applications_tests/lethe-particles/restart_moving_receptacle.prm
  include/dem/insertion_file.h
  source/dem/insertion_file.cc
Labels: Quick fix, Ready for review
