Repository chaos-polymtl/lethe, pull requests merged in 2024-08, with the labels that each got.

#1218 Write checkpoint when the end time of the simulation is reached
  source/solvers/navier_stokes_base.cc
Labels: Quick fix, Ready for review

#1208 Dem dmt non contact
  applications_tests/lethe-particles/pp_dmt_equilibrium.output
  applications_tests/lethe-particles/pp_dmt_equilibrium.prm
  applications_tests/lethe-particles/pw_dmt_equilibrium.output
  applications_tests/lethe-particles/pw_dmt_equilibrium.prm
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  doc/source/parameters/dem/model_parameters.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  include/core/parameters_lagrangian.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_wall_contact_force.h
  include/dem/particle_wall_dmt_force.h
  include/dem/particle_wall_nonlinear_force.h
  source/core/parameters_lagrangian.cc
  source/dem/force_chains_visualization.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_wall_dmt_force.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Reviewed and ready to merge, Refactoring

#1221 Remove gear3 integrator
  CHANGELOG.md
  include/core/parameters_lagrangian.h
  include/dem/gear3_integrator.h
  source/core/parameters_lagrangian.cc
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/gear3_integrator.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: Maintenance, Ready for review, Refactoring

#1222 Rename all relevant matrix-free files using Fluid Dynamics prefix
  CHANGELOG.md
  applications/lethe-fluid-matrix-free/CMakeLists.txt
  applications/lethe-fluid-matrix-free/fluid_dynamics_matrix_free.cc
  doc/doxygen/main.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/fluid_dynamics_matrix_free_operators.h
  source/solvers/CMakeLists.txt
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Maintenance, Ready for review

#1224 Correct typo in heat transfer documentation
  doc/source/theory/multiphysics/heat_transfer/heat_equation.rst
Labels: Documentation, Quick fix, Ready for review

#1225 Rename all files related to the VANS solver using Fluid Dynamics prefix
  CHANGELOG.md
  applications/lethe-fluid-vans/CMakeLists.txt
  applications/lethe-fluid-vans/fluid_dynamics_vans.cc
  doc/doxygen/main.h
  doc/source/parameters/unresolved-cfd-dem/cfd-dem.rst
  doc/source/parameters/unresolved-cfd-dem/void-fraction.rst
  include/fem-dem/cfd_dem_coupling.h
  include/fem-dem/fluid_dynamics_vans.h
  include/fem-dem/vans_assemblers.h
  source/fem-dem/CMakeLists.txt
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/vans_assemblers.cc
Labels: Maintenance

#1197 Tracer flow rate at boundaries
  CHANGELOG.md
  applications_tests/lethe-fluid/tracer_flow_rate.output
  applications_tests/lethe-fluid/tracer_flow_rate.prm
  doc/source/parameters/cfd/post_processing.rst
  include/core/parameters.h
  include/solvers/tracer.h
  source/core/parameters.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/gls_sharp_navier_stokes.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
Labels: Enhancement, Ready for review, Post-processing

#1227 Correct some warnings in doxygen compilation
  include/core/grids.h
  include/core/manifolds.h
  include/core/parameters_multiphysics.h
  include/core/phase_change.h
  include/core/shape.h
  include/core/tensors_and_points_dimension_manipulation.h
  include/core/utilities.h
  include/solvers/vof.h
Labels: Documentation, Quick fix

#1226 Rename all block Navier Stokes files using Fluid Dynamics prefix
  CHANGELOG.md
  applications/lethe-fluid-block/CMakeLists.txt
  applications/lethe-fluid-block/fluid_dynamics_block.cc
  doc/doxygen/main.h
  include/solvers/fluid_dynamics_block.h
  include/solvers/navier_stokes_assemblers.h
  source/solvers/CMakeLists.txt
  source/solvers/fluid_dynamics_block.cc
  source/solvers/navier_stokes_assemblers.cc
Labels: Maintenance, Ready for review

#1228 Rename all Nitsche files using Fluid Dynamics prefix
  CHANGELOG.md
  applications/lethe-fluid-nitsche/CMakeLists.txt
  applications/lethe-fluid-nitsche/fluid_dynamics_nitsche.cc
  applications/lethe-fluid/gls_navier_stokes.cc
  doc/doxygen/main.h
  include/solvers/fluid_dynamics_nitsche.h
  source/solvers/CMakeLists.txt
  source/solvers/fluid_dynamics_nitsche.cc
Labels: Maintenance, Ready for review

#1230 PID mesh adaptation quick fix
  include/core/mesh_controller.h
Labels: Bug, Reviewed and ready to merge

#1231 Rename all Sharp files using Fluid Dynamics prefix
  CHANGELOG.md
  applications/lethe-fluid-sharp/CMakeLists.txt
  applications/lethe-fluid-sharp/fluid_dynamics_sharp.cc
  doc/doxygen/main.h
  include/fem-dem/fluid_dynamics_sharp.h
  include/fem-dem/ib_particles_dem.h
  source/fem-dem/CMakeLists.txt
  source/fem-dem/fluid_dynamics_sharp.cc
Labels: Maintenance, Reviewed and ready to merge

#1234 Fix pressure interpolation at face bug and other bugs
  applications_tests/lethe-fluid/gls_vof_1_isothermal_compressible_fluid.output
  applications_tests/lethe-fluid/gls_vof_2_isothermal_compressible_fluids.output
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.output
  applications_tests/lethe-fluid/time_dependent_boundaries_vof.output
  include/solvers/navier_stokes_scratch_data.h
  source/solvers/vof.cc
  tests/core/solid_base_33_moving_triangulation.cc
Labels: Reviewed and ready to merge

#1235 Update turbulent taylor couette time stepping in example
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q3.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q3.png
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
Labels: Ready for review

#1215 Average velocity as initial condition
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/buoyant_flow_between_parallel_plates.output
  applications_tests/lethe-fluid/cavity_ht_average_velocity_as_initial_condition.mpirun=1.output
  applications_tests/lethe-fluid/cavity_ht_average_velocity_as_initial_condition.prm
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.averagevelocities
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.pvdhandler
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.simulationcontrol
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.triangulation
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.triangulation.info
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/restart.triangulation_fixed.data
  applications_tests/lethe-fluid/cavity_ht_average_velocity_initial_condition_files/temperature_statistics.checkpoint
  applications_tests/lethe-fluid/cavity_ht_average_velocity_restart.mpirun=1.output
  doc/source/parameters/cfd/initial_conditions.rst
  doc/source/parameters/cfd/multiphysics.rst
  include/core/parameters_multiphysics.h
  include/core/simulation_control.h
  include/solvers/initial_conditions.h
  include/solvers/navier_stokes_base.h
  source/core/parameters_multiphysics.cc
  source/core/simulation_control.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/gls_navier_stokes.cc
  source/solvers/heat_transfer.cc
  source/solvers/heat_transfer_assemblers.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Ready for review, Refactoring

#1236 Rename all GLS Navier Stokes files using Fluid Dynamics prefix
  CHANGELOG.md
  CONTRIBUTING.md
  applications/lethe-fluid/CMakeLists.txt
  applications/lethe-fluid/fluid_dynamics_matrix_based.cc
  contrib/utilities/automatic_launch/launch_lethe.sh
  contrib/utilities/automatic_launch/launch_lethe_locally.py
  doc/doxygen/main.h
  include/fem-dem/fluid_dynamics_sharp.h
  include/fem-dem/fluid_dynamics_vans.h
  include/solvers/fluid_dynamics_matrix_based.h
  include/solvers/fluid_dynamics_nitsche.h
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/fluid_dynamics_sharp.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/solvers/CMakeLists.txt
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_nitsche.cc
  tests/solvers/restart_01.cc
Labels: Maintenance, Reviewed and ready to merge

#1238 Added reference to Arxiv for porous media article
  doc/source/publications.rst
  doc/source/referencing.rst
Labels: Documentation, Ready for review

#1245 Correct minor typos in matrix free documentation
  include/solvers/fluid_dynamics_matrix_free.h
Labels: Documentation, Quick fix

#1249 Fix compilation of prototypes
  prototypes/direct_gls_navier_stokes/direct_gls_navier_stokes.cc
  prototypes/direct_steady_navier_stokes/direct_steady_navier_stokes.cc
  prototypes/matrix_based_advection_diffusion/matrix_based_advection_diffusion.cc
  prototypes/matrix_based_non_linear_poisson/matrix_based_non_linear_poisson.cc
  prototypes/matrix_free_advection_diffusion/matrix_free_advection_diffusion.cc
  prototypes/matrix_free_navier_stokes/matrix_free_navier_stokes.cc
  prototypes/matrix_free_non_linear_poisson/matrix_free_non_linear_poisson.cc
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
Labels: Maintenance, Quick fix

#1250 Add prototypes flag to warnings CI
  .github/workflows/warnings-gcc.yml
  prototypes/direct_gls_navier_stokes/direct_gls_navier_stokes.cc
  prototypes/direct_steady_navier_stokes/direct_steady_navier_stokes.cc
  prototypes/kokkos_poisson/kokkos_poisson.cc
Labels: CI

#1243 Remove all clang tidy warnings from the core library of Lethe
  include/core/bdf.h
  include/core/manifolds.h
  include/core/parameters.h
  include/core/parsed_function_custom.h
  include/core/pvd_handler.h
  include/core/serial_solid.h
  include/core/shape.h
  include/core/shape_parsing.h
  include/core/simulation_control.h
  include/core/solid_base.h
  include/core/solutions_output.h
  include/core/utilities.h
  source/core/bdf.cc
  source/core/lethe_grid_tools.cc
  source/core/manifolds.cc
  source/core/parameters.cc
  source/core/parsed_function_custom.cc
  source/core/pvd_handler.cc
  source/core/serial_solid.cc
  source/core/shape.cc
  source/core/shape_parsing.cc
  source/core/simulation_control.cc
  source/core/solid_base.cc
  source/core/solutions_output.cc
  source/core/utilities.cc
  tests/core/bdf_01.cc
  tests/core/bdf_extrapolation_01.cc
  tests/core/lethe_grid_tool_mesh_cut_by_flat_2.cc
  tests/core/lethe_grid_tool_mesh_cut_by_flat_3.cc
  tests/core/shape_composites.cc
  tests/core/table_read.cc
  tests/core/vector_problem.cc
Labels: Ready for review, Refactoring

#1256 Update all actions to use Ninja instead of make
  .github/workflows/debug.yml
  .github/workflows/examples-parameter-files.yml
  .github/workflows/main_dealii_distributed_vectors.yml
  .github/workflows/release.yml
  .github/workflows/warnings-gcc.yml
  source/dem/visualization.cc
Labels: Ready for review, CI

#1255 Print parameters (lethe-fluid-matrix-free)
  applications/lethe-fluid-matrix-free/fluid_dynamics_matrix_free.cc
Labels: Reviewed and ready to merge

#1257 Git version
  CHANGELOG.md
  CMakeLists.txt
  applications/lethe-fluid-matrix-free/fluid_dynamics_matrix_free.cc
  include/core/revision.h.in
Labels: Reviewed and ready to merge

#1260 Update print parameters for prototype
  prototypes/matrix_based_non_linear_poisson/matrix_based_non_linear_poisson.cc
Labels: Bug

#1261 Fix status badges
  README.md
Labels: Bug

#1262 Improve multigrid parameters documentation
  doc/source/parameters/cfd/linear_solver_control.rst
Labels: Documentation

#1259 [WIP] Update instruction for digital alliance to move to new standard environment.
  doc/source/installation/digital_alliance.rst
Labels: Documentation

#1263 Print intermediate mg iterations
  include/solvers/fluid_dynamics_matrix_free.h
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Reviewed and ready to merge

#1264 Specify GMRES parameters whent iterating intermediate GMG levels
  doc/source/parameters/cfd/linear_solver_control.rst
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Reviewed and ready to merge, Quick fix

#1254 [WIP] - Remove solver warnings
  include/solvers/flow_control.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/fluid_dynamics_matrix_free_operators.h
  include/solvers/postprocessing_velocities.h
  include/solvers/tracer.h
  source/solvers/cahn_hilliard.cc
  source/solvers/flow_control.cc
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
  source/solvers/fluid_dynamics_nitsche.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_velocities.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
  tests/core/solid_base_33_moving_particles.cc
  tests/solvers/restart_01.cc
Labels: WIP

#1265 Refactor cell diameter computation to utilities
  CHANGELOG.md
  include/core/utilities.h
  include/solvers/cahn_hilliard_scratch_data.h
  include/solvers/heat_transfer_scratch_data.h
  include/solvers/navier_stokes_scratch_data.h
  include/solvers/tracer_scratch_data.h
  include/solvers/vof_scratch_data.h
  source/solvers/fluid_dynamics_nitsche.cc
  source/solvers/postprocessing_cfd.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge, Rebased, Refactoring, Utilities

#1270 NavierStokesOperatorBase: precompute forcing term
  include/solvers/fluid_dynamics_matrix_free_operators.h
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Reviewed and ready to merge
