Repository chaos-polymtl/lethe, pull requests merged in 2025-08, with the labels that each got.

#1603 Update first simulation documentation
  doc/source/first_simulation.rst
Labels: Documentation, Ready for review

#1602 Initialize VOF using geometric redistanciation
  CHANGELOG.md
  applications_tests/lethe-fluid/cavity_ht_average_velocity_as_initial_condition.prm
  applications_tests/lethe-fluid/evaporation_static_droplet_constant_mass_flux.prm
  applications_tests/lethe-fluid/gls_vof_dirichlet_boundary_condition.prm
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_rotated_laser.prm
  applications_tests/lethe-fluid/liquid_thermocapillary_droplet.prm
  applications_tests/lethe-fluid/solid_thermocapillary_droplet.prm
  applications_tests/lethe-fluid/uniform_mesh_adapt_limit.prm
  applications_tests/lethe-fluid/vof-algebraic-interface-reinitialization-advected-circle-bdf2-frequency-check.prm
  applications_tests/lethe-fluid/vof-algebraic-interface-reinitialization-advected-circle.prm
  applications_tests/lethe-fluid/vof-geometric-interface-reinitialization-swirling-flow.prm
  doc/source/parameters/cfd/initial_conditions.rst
  examples/multiphysics/3d-dam-break/3d-dam-break.prm
  examples/multiphysics/capillary-wave/capillary-wave-TSM-0_95.prm
  examples/multiphysics/capillary-wave/capillary-wave.tpl
  examples/multiphysics/rayleigh-plateau-instability/3D-delta0_30/rayleigh-plateau-J1-3D.prm
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10.tpl
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10_delta0_20/rayleigh-plateau-J1-We020-Oh0_10_delta0_20.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-constant-sharpening.prm
  examples/multiphysics/rising-bubble/rising-bubble-alge.prm
  examples/multiphysics/rising-bubble/rising-bubble-geo.prm
  examples/multiphysics/rising-bubble/rising-bubble-proj.prm
  examples/multiphysics/static-bubble/static-bubble.prm
  examples/multiphysics/static-irradiation/2D/static-irradiation.prm
  examples/multiphysics/thermocapillary-droplet/thermocapillary-droplet.prm
  include/solvers/fluid_dynamics_block.h
  include/solvers/fluid_dynamics_matrix_based.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/initial_conditions.h
  include/solvers/navier_stokes_base.h
  include/solvers/tracer.h
  source/core/interface_tools.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/heat_transfer.cc
  source/solvers/initial_conditions.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge

#1607 change _ by - in turbulent Taylor-Couette example
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
Labels: Ready for review

#1610 Make Lethe work adequately without metis and fix some issues with null pointers
  CHANGELOG.md
  source/core/grids.cc
  source/solvers/navier_stokes_base.cc
Labels: Bug, Ready for review

#1614 Mortar: fix update function
  CHANGELOG.md
  applications_tests/geo_files/circle.geo
  applications_tests/geo_files/square-with-hole.geo
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/circle.msh
  applications_tests/lethe-fluid/mortar_mms.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms_Q1Q1.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms_gmsh.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms_gmsh.prm
  applications_tests/lethe-fluid/mortar_mms_rotated.mpirun=3.output
  applications_tests/lethe-fluid/mortar_taylorcouette.mpirun=3.output
  applications_tests/lethe-fluid/mortar_taylorcouette.output
  applications_tests/lethe-fluid/mortar_taylorcouette_transient.mpirun=2.output
  applications_tests/lethe-fluid/square-with-hole.msh
  include/solvers/fluid_dynamics_matrix_based.h
  include/solvers/navier_stokes_base.h
  source/core/grids.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/navier_stokes_base.cc
Labels: Bug, Reviewed and ready to merge, Refactoring

#1613 Collision stats logging with multiple MPI processes
  CHANGELOG.md
  include/dem/log_collision_data.h
  source/dem/dem.cc
  source/dem/log_collision_data.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: Enhancement, Reviewed and ready to merge

#1620 Clean assertions
  CHANGELOG.md
  include/core/density_model.h
  include/core/evaporation_model.h
  include/core/mobility_cahn_hilliard_model.h
  include/core/rheological_model.h
  include/core/specific_heat_model.h
  include/core/surface_tension_model.h
  include/core/thermal_conductivity_model.h
  include/core/thermal_expansion_model.h
  include/core/tracer_diffusivity_model.h
  include/core/tracer_reaction_model.h
  include/core/utilities.h
  source/core/rheological_model.cc
Labels: Ready for review

#1609 MortarManagerBase/CouplingOperator: enable 3D
  include/core/mortar_coupling_manager.h
  source/core/mortar_coupling_manager.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  tests/mortar/manager_05.cc
  tests/mortar/manager_05.output
  tests/mortar/poisson_3d_01.cc
  tests/mortar/poisson_3d_01.mpirun=1.output
  tests/mortar/poisson_3d_02.cc
  tests/mortar/poisson_3d_02.mpirun=1.output
  tests/mortar/tests.h
Labels: Ready for review

#1622 Add if multiphysics mf
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/multiphysics_check_tracer.output
  applications_tests/lethe-fluid-matrix-free/multiphysics_check_tracer.prm
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Quick fix, Ready for review

#1625 Change prm file and documentation
  CHANGELOG.md
  doc/source/examples/incompressible-flow/3d-taylor-green-vortex/3d-taylor-green-vortex.rst
  examples/incompressible-flow/3d-taylor-green-vortex/tgv-matrix-free.prm
Labels: Quick fix

#1623 Mortar: explicitly use the information on which side you are
  CHANGELOG.md
  include/core/mortar_coupling_manager.h
  source/core/mortar_coupling_manager.cc
  tests/mortar/manager_02.cc
  tests/mortar/manager_02.output
  tests/mortar/manager_05.cc
  tests/mortar/plot_01.cc
Labels: Reviewed and ready to merge, Quick fix

#1624 Refactor output results into struct
  CHANGELOG.md
  doc/source/parameters/cfd/post_processing.rst
  examples/incompressible-flow/2d-transient-flow-around-cylinder/cylinder.prm
  examples/sharp-immersed-boundary/3d-composite-mixer-with-pbt-impeller/mixer.prm
  examples/sharp-immersed-boundary/3d-opencascade-mixer-with-pbt-impeller/mixer.prm
  examples/sharp-immersed-boundary/inclined-3d-composite-mixer-with-pbt-impeller/mixer.prm
  include/core/parameters.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/navier_stokes_base.h
  include/solvers/output_struct.h
  include/solvers/postprocessors_smoothing.h
  source/core/parameters.cc
  source/solvers/CMakeLists.txt
  source/solvers/navier_stokes_base.cc
  source/solvers/output_struct.cc
  source/solvers/postprocessors_smoothing.cc
Labels: Reviewed and ready to merge, Refactoring

#1628 `PreconditionASM` for local-smoothing MG
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_gcmg_asm.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_gcmg_asm.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_lsmg_asm.prm
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_lsmg_asm.with_dealii.geq.9.6.mpirun=2.output
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Ready to merge after CHANGELOG/Rebase

#1631 Fix bug with constraints when using local smoothing
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Bug

#1632 Update instructions for launching simulations on clusters
  CHANGELOG.md
  doc/source/installation/digital_alliance.rst
Labels: Documentation, Reviewed and ready to merge

#1560 Cfd dem vof - variation of fluid properties with vof
  include/solvers/navier_stokes_scratch_data.h
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/vans_assemblers.cc
  source/solvers/navier_stokes_scratch_data.cc
Labels: Ready for review

#1633 Fix and streamline the particle-fluid assemblers
  CHANGELOG.md
  include/fem-dem/vans_assemblers.h
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/vans_assemblers.cc
Labels: Reviewed and ready to merge, Refactoring

#1630 MG local smoothing: introduce hp-muligrid
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/mms3d_fe2_lsmg.prm
  applications_tests/lethe-fluid-matrix-free/mms3d_fe2_lsmg.with_dealii.geq.9.6.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe2_lsmg.with_dealii.geq.9.6.output
  include/solvers/fluid_dynamics_matrix_free.h
  source/core/parameters.cc
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Reviewed and ready to merge

#1634 Cleanup scratch data for particle-fluid interaction and add defensive assertions
  CHANGELOG.md
  include/solvers/navier_stokes_scratch_data.h
  source/solvers/navier_stokes_scratch_data.cc
Labels: Maintenance, Reviewed and ready to merge
