Repository chaos-polymtl/lethe, pull requests merged in 2025-09, with the labels that each got.

#1636 Add simulations relaunch script for cluster usage
  CHANGELOG.md
  contrib/utilities/relaunch_simulations.sh
Labels: Reviewed and ready to merge, Utilities

#1652 Fix checkpointing
  CHANGELOG.md
  include/core/utilities.h
  source/solvers/cahn_hilliard.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
Labels: Reviewed and ready to merge, Quick fix, Needs more reviewers

#1638 Stabilized ALE Mortar Assembler
  CHANGELOG.md
  applications_tests/lethe-fluid/mortar_tgv.mpirun=3.output
  applications_tests/lethe-fluid/mortar_tgv.prm
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/navier_stokes_assemblers.cc
Labels: Bug, Reviewed and ready to merge

#1658 Hotfix sharp output
  CHANGELOG.md
  source/fem-dem/fluid_dynamics_sharp.cc
Labels: Reviewed and ready to merge

#1665 Add favicon to doxygen
  .github/workflows/doc-github-pages.yml
  doc/doxygen/compile_doxygen_documentation.sh
  doc/doxygen/doxygen-config-file
  doc/doxygen/logo.png
  doc/doxygen/stylesheet.css
Labels: Maintenance, Documentation, Ready for review

#1655 Inlet polynomial function expression script
  CHANGELOG.md
  contrib/utilities/inlet_profile_generator/inlet_profile_generator.py
  doc/source/tools/command-line-interface-options.rst
  doc/source/tools/inlet_profile_generator/img/inlet_profile_generator_plot.png
  doc/source/tools/inlet_profile_generator/inlet_profile_generator.rst
  doc/source/tools/tools.rst
Labels: Reviewed and ready to merge

#1661 Fix issue by attaching dof_handler to DataOut instance + refactor structs to include cell data
  CHANGELOG.md
  include/fem-dem/fluid_dynamics_sharp.h
  include/fem-dem/fluid_dynamics_vans.h
  include/fem-dem/fluid_dynamics_vans_matrix_free.h
  include/solvers/navier_stokes_base.h
  include/solvers/output_struct.h
  source/fem-dem/fluid_dynamics_sharp.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/fluid_dynamics_vans_matrix_free.cc
  source/solvers/navier_stokes_base.cc
Labels: Ready for review, Refactoring

#1672 Clang warnings solver
  CHANGELOG.md
  include/core/mortar_coupling_manager.h
  include/core/parameters.h
  include/core/simulation_control.h
  include/core/utilities.h
  include/solvers/cahn_hilliard_filter.h
  include/solvers/fluid_dynamics_block.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/fluid_dynamics_matrix_free_operators.h
  include/solvers/physics_assemblers.h
  include/solvers/signed_distance_transformation.h
  include/solvers/tracer_assemblers.h
  include/solvers/vof_filter.h
  source/core/parameters.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/navier_stokes_vof_assemblers.cc
  source/solvers/postprocessing_cfd.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
  source/solvers/vof_algebraic_interface_reinitialization.cc
  source/solvers/vof_curvature_projection.cc
  source/solvers/vof_linear_subequations_solver.cc
  source/solvers/vof_phase_gradient_projection.cc
Labels: Ready for review, Refactoring

#1663 Add validation case for sharp
  CHANGELOG.md
  contrib/validation/validation_cases.txt
  contrib/validation/validation_cases_lucille.txt
  examples/sharp-immersed-boundary/sedimentation-1-cuboid/post-process-sedimentation-1-cuboid.py
  examples/sharp-immersed-boundary/sedimentation-1-cuboid/validate.sh
Labels: Maintenance, Ready to merge after final OK

#1679 Remove kokkos-related warnings in the prototypes
  .github/workflows/warnings-gcc.yml
  CHANGELOG.md
  prototypes/direct_gls_navier_stokes/exactsolutions.h
  prototypes/direct_steady_navier_stokes/exactsolutions.h
  prototypes/kokkos_poisson/kokkos_poisson.cc
  prototypes/kokkos_stokes/kokkos_stokes.cc
  prototypes/matrix_based_non_linear_poisson/matrix_based_non_linear_poisson.cc
  prototypes/matrix_free_mortar_poisson_consistent_integration/matrix_free_mortar_poisson_consistent_integration.cc
  prototypes/matrix_free_navier_stokes/matrix_free_navier_stokes.cc
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
  prototypes/template/prototype_template.cc
Labels: Reviewed and ready to merge, Quick fix, CI

#1680 Remove dealii 9.6 version checks in MF solver
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_gcmg.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_gcmg.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_gcmg_asm.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_lsmg.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_lsmg.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/cylinder_kelly_estimator_lsmg_asm.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_gcmg.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe1_lsmg.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe2_lsmg.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mms3d_fe2_lsmg.output
  applications_tests/lethe-fluid-matrix-free/taylor_couette_2d_local_ref.output
  applications_tests/lethe-fluid-matrix-free/taylor_couette_3d_gcmg.output
  applications_tests/lethe-fluid-matrix-free/taylor_couette_3d_lsmg.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.mpirun=1.output
  applications_tests/lethe-fluid-matrix-free/tgv_restart_bdf1.mpirun=2.output
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Reviewed and ready to merge

#1681 Fix the typo
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/spouted_bed_load_balancing.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_mobility_status.mpirun=2.output
  applications_tests/lethe-particles/load_balancing_solid_object.mpirun=2.output
  applications_tests/lethe-particles/packing_in_ball_dynamic_load_balance.mpirun=2.output
  applications_tests/lethe-particles/periodic_boundary_load_balancing.mpirun=2.output
  applications_tests/lethe-particles/resize_containers.mpirun=2.out
  applications_tests/lethe-particles/restart_cell_weight_function.with_dealii.geq.9.7.mpirun=2.output
  source/dem/dem.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: Reviewed and ready to merge, Quick fix

#1687 Added AssertThrow in the read_checkpoint function in the DEM
  source/dem/read_checkpoint.cc
Labels: Quick fix, Ready for review

#1673 Table serialization
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/CMakeLists.txt
  applications_tests/lethe-fluid-particles/generators/gas_solid_fluidized_bed_generator_step_1_dem.prm
  applications_tests/lethe-fluid-particles/generators/gas_solid_fluidized_bed_generator_step_2_cfd-dem.prm
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/pressure_drop.checkpoint
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.particles
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.pvdhandler
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.simulationcontrol
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.triangulation
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.triangulation.info
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.triangulation_fixed.data
  applications_tests/lethe-fluid-particles/restart_fluidized_bed_files/restart.triangulation_variable.data
  applications_tests/lethe-fluid-particles/restart_gas_solid_fluidized_bed.mpirun=2.output
  include/fem-dem/cfd_dem_coupling.h
  include/solvers/fluid_dynamics_nitsche.h
  include/solvers/navier_stokes_base.h
  include/solvers/output_struct.h
  source/fem-dem/cfd_dem_coupling.cc
  source/solvers/fluid_dynamics_nitsche.cc
  source/solvers/navier_stokes_base.cc
Labels: Reviewed and ready to merge

#1682 Mortar matrix-free
  CHANGELOG.md
  applications_tests/lethe-fluid-matrix-free/mortar_mms2d_ilu.mpirun=2.output
  applications_tests/lethe-fluid-matrix-free/mortar_mms2d_ilu.prm
  applications_tests/lethe-fluid-matrix-free/mortar_taylor_couette_2d_ilu.output
  applications_tests/lethe-fluid-matrix-free/mortar_taylor_couette_2d_ilu.prm
  include/solvers/fluid_dynamics_matrix_based.h
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/fluid_dynamics_matrix_free_operators.h
  include/solvers/navier_stokes_base.h
  source/core/mortar_coupling_manager.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Enhancement, Reviewed and ready to merge

#1697 Boundary condition id as list
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/generators/gas_solid_fluidized_bed_generator_step_1_dem.prm
  applications_tests/lethe-fluid-sharp/mms_tracer_reaction_heterogeneous_gaussian.prm
  applications_tests/lethe-fluid/cavity_adjoint_gls.prm
  doc/source/examples/incompressible-flow/2d-lid-driven-cavity-flow/lid-driven-cavity-flow.rst
  examples/incompressible-flow/2d-lid-driven-cavity/Reynolds_7500/cavity.prm
  examples/incompressible-flow/2d-lid-driven-cavity/cavity.prm
  include/core/boundary_conditions.h
  include/core/parameters.h
  include/core/utilities.h
Labels: Enhancement, Reviewed and ready to merge

#1700 Add pre-commit hook for copyright
  contrib/utilities/pre-commit.sh
  contrib/utilities/update_copyright.sh
Labels: Enhancement, Ready for review
