Repository chaos-polymtl/lethe, pull requests merged in 2025-07, with the labels that each got.

#1563 Mortar: Navier Stokes coupling
  CHANGELOG.md
  applications_tests/lethe-fluid/mortar_taylorcouette.mpirun=3.output
  applications_tests/lethe-fluid/mortar_taylorcouette.output
  applications_tests/lethe-fluid/mortar_taylorcouette.prm
  include/core/mortar_coupling_manager.h
  include/solvers/navier_stokes_base.h
  source/core/mortar_coupling_manager.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/navier_stokes_base.cc
Labels: Enhancement, Ready for review

#1566 Update installation instructions for Rorqual
  doc/source/installation/digital_alliance.rst
Labels: Documentation, Ready for review

#1567 Added the nu and fixed the parentheses
  doc/source/theory/multiphysics/fluid_dynamics/fem_formulation.rst
Labels: Documentation, Quick fix

#1569 Flag to delete old vtu files
  CHANGELOG.md
  applications/lethe-fluid-block/fluid_dynamics_block.cc
  applications/lethe-fluid-matrix-free/fluid_dynamics_matrix_free.cc
  applications/lethe-fluid-nitsche/fluid_dynamics_nitsche.cc
  applications/lethe-fluid-particles/cfd_dem_coupling.cc
  applications/lethe-fluid-sharp/fluid_dynamics_sharp.cc
  applications/lethe-fluid-vans-matrix-free/fluid_dynamics_vans_matrix_free.cc
  applications/lethe-fluid-vans/fluid_dynamics_vans.cc
  applications/lethe-fluid/fluid_dynamics_matrix_based.cc
  applications/lethe-particles/dem.cc
  doc/source/tools/command-line-interface-options.rst
  doc/source/tools/tools.rst
  include/core/utilities.h
  source/core/utilities.cc
Labels: Utilities, Reviewed and waiting for changes

#1568 SDIRK stage data
  include/core/parameters.h
  include/core/sdirk_stage_data.h
  source/core/CMakeLists.txt
  source/core/sdirk_stage_data.cc
  tests/core/sdirk_stage.cc
  tests/core/sdirk_stage.output
Labels: Reviewed and waiting for changes

#1571 Add missing references
  doc/source/publications.rst
  doc/source/referencing.rst
Labels: Ready for review

#1564 Unresolved CFD-DEM - Gas-solid Spouted Bed Example
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/gas-solid-spouted-rectangular-bed.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/images/boundary_conditions.png
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/images/boundary_conditions.svg
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/images/drag-model-di-felice.png
  doc/source/examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/images/drag-model-rong.png
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_015.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_030.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_045.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_060.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_075.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/data/spouted_bed_data_080.csv
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/functions_lagrangian.py
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/functions_particles.py
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/gas-solid-spouted-rectangular-bed.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/mesh/spouted_structured.geo
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/mesh_with_restriction/spouted_structured_with_restriction.geo
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/packing-particles.prm
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/postprocessing_lagrangian.py
  examples/unresolved-cfd-dem/gas-solid-spouted-rectangular-bed/postprocessing_particles.py
Labels: Ready for review, Example

#1575 Mortar: add application tests
  CHANGELOG.md
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/mortar_mms.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms.prm
  applications_tests/lethe-fluid/mortar_mms_gmsh.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms_gmsh.prm
  applications_tests/lethe-fluid/square-with-circle.msh
  include/core/mortar_coupling_manager.h
  include/core/utilities.h
  source/core/mortar_coupling_manager.cc
Labels: Bug, Ready for review

#1574 Update validation for lucille
  CHANGELOG.md
  contrib/validation/validate_lethe.sh
  contrib/validation/validation_cases.txt
  contrib/validation/validation_cases_lucille.txt
  contrib/validation/validation_functions.sh
  examples/multiphysics/rising-bubble/rising-bubble-alge.prm
  examples/multiphysics/rising-bubble/rising-bubble-geo.prm
  examples/multiphysics/rising-bubble/rising-bubble-proj.prm
  examples/multiphysics/rising-bubble/rising-bubble.py
  examples/multiphysics/rising-bubble/validate.sh
Labels: Ready for review, CI

#1577 Add get_number_of_stages() utility to SimulationControl
  include/core/simulation_control.h
  source/core/simulation_control.cc
  tests/core/get_number_of_stages.cc
  tests/core/get_number_of_stages.output
Labels: Reviewed and ready to merge

#1579 Mortar: add application test with rotated mesh
  CHANGELOG.md
  applications_tests/lethe-fluid/mortar_mms_rotated.mpirun=3.output
  applications_tests/lethe-fluid/mortar_mms_rotated.prm
  include/core/mortar_coupling_manager.h
  include/core/parameters.h
  include/solvers/navier_stokes_base.h
  source/core/grids.cc
  source/core/mortar_coupling_manager.cc
  source/core/parameters.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/navier_stokes_base.cc
Labels: Bug, Quick fix

#1576 Dynamic particle insertion in CFD-DEM
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/dynamic_particle_insertion.output
  applications_tests/lethe-fluid-particles/dynamic_particle_insertion.prm
  include/fem-dem/cfd_dem_coupling.h
  source/core/parameters_lagrangian.cc
  source/dem/insertion.cc
  source/dem/insertion_file.cc
  source/dem/insertion_list.cc
  source/fem-dem/cfd_dem_coupling.cc
Labels: Enhancement, Reviewed and ready to merge

#1582 Fix warnings introduced by functions now marked for deprecation in deal.II 9.8-pre
  CHANGELOG.md
  prototypes/kokkos_poisson/kokkos_poisson.cc
  prototypes/kokkos_stokes/kokkos_stokes.cc
  prototypes/matrix_based_advection_diffusion/matrix_based_advection_diffusion.cc
  prototypes/matrix_based_non_linear_poisson/matrix_based_non_linear_poisson.cc
  prototypes/matrix_free_advection_diffusion/matrix_free_advection_diffusion.cc
  prototypes/matrix_free_navier_stokes/matrix_free_navier_stokes.cc
  prototypes/matrix_free_non_linear_poisson/matrix_free_non_linear_poisson.cc
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
  source/dem/dem.cc
  source/fem-dem/fluid_dynamics_sharp.cc
  source/fem-dem/void_fraction.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessors_smoothing.cc
  source/solvers/tracer.cc
Labels: Maintenance, Ready for review, CI

#1585 Allow compatibility with 64bit indices
  CHANGELOG.md
  source/core/interface_tools.cc
  source/dem/particle_wall_broad_search.cc
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Bug, Enhancement, Reviewed and ready to merge

#1589 Remove new warnings
  .github/workflows/clang-tidy.disabled
  .github/workflows/warnings-gcc.yml
  CHANGELOG.md
  CMakeLists.txt
  applications/lethe-fluid-block/fluid_dynamics_block.cc
  applications/lethe-fluid/fluid_dynamics_matrix_based.cc
  doc/source/installation/regular_installation.rst
  include/solvers/cahn_hilliard.h
  include/solvers/heat_transfer.h
  include/solvers/postprocessing_scalar.h
  include/solvers/postprocessing_velocities.h
  include/solvers/tracer.h
  include/solvers/vof.h
  include/solvers/vof_algebraic_interface_reinitialization.h
  prototypes/matrix_free_advection_diffusion/matrix_free_advection_diffusion.cc
  prototypes/matrix_free_mortar_poisson_consistent_integration/matrix_free_mortar_poisson_consistent_integration.cc
  prototypes/matrix_free_mortar_rotate/matrix_free_mortar_rotate.cc
  prototypes/matrix_free_navier_stokes/matrix_free_navier_stokes.cc
  prototypes/matrix_free_stokes/matrix_free_stokes.cc
  prototypes/vof_advection/vof_advection.cc
  source/core/grids.cc
  source/core/interface_tools.cc
  source/core/solid_base.cc
  source/dem/insertion_file.cc
  source/dem/insertion_list.cc
  source/dem/insertion_plane.cc
  source/dem/insertion_volume.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/postprocessing_cfd_dem.cc
  source/fem-dem/void_fraction.cc
  source/solvers/cahn_hilliard.cc
  source/solvers/fluid_dynamics_block.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
  source/solvers/heat_transfer.cc
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_cfd.cc
  source/solvers/postprocessors_smoothing.cc
  source/solvers/tracer.cc
  source/solvers/vof.cc
  source/solvers/vof_algebraic_interface_reinitialization.cc
  source/solvers/vof_linear_subequations_solver.cc
Labels: Maintenance, Reviewed and ready to merge

#1588 Remove checks to deal.II versions which are not supported anymore
  CHANGELOG.md
  include/core/shape.h
  include/dem/load_balancing.h
  source/core/shape.cc
  source/dem/load_balancing.cc
  source/dem/particle_point_line_contact_force.cc
  source/solvers/fluid_dynamics_nitsche.cc
  tests/core/lethe_grid_tool_mesh_cut_by_flat_3.cc
  tests/dem/integration_schemes_accuracy.cc
Labels: Maintenance, Reviewed and ready to merge

#1590 Fix workflow status badges
  README.md
Labels: Reviewed and ready to merge, Quick fix

#1591 Remove duplicated function in the QCM void fraction method
  CHANGELOG.md
  include/fem-dem/void_fraction.h
  source/fem-dem/void_fraction.cc
Labels: Ready for review, Refactoring

#1587 Improve application documentation
  doc/source/applications.rst
Labels: Documentation

#1594 Update insertion info documentation
  doc/source/parameters/dem/insertion_info.rst
Labels: Documentation, Ready for review

#1593 Added the same check as the CFD-DEM
  CHANGELOG.md
  source/dem/dem.cc
Labels: Bug, Reviewed and ready to merge, Quick fix

#1596 Simplify documentation and add long indices
  doc/source/installation/digital_alliance.rst
Labels: Reviewed and ready to merge

#1573 Pseudo-2d gas-solid fluidized bed example
  doc/source/examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/images/bed-height.png
  doc/source/examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/images/pressure-fluctuations.png
  doc/source/examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/images/pressure-psd.png
  doc/source/examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/images/void-fraction-fluctuations.png
  doc/source/examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/pseudo-2d-gas-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/unresolved-cfd-dem.rst
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/fluidized-bed-postprocessing.py
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/packing-particles.prm
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/reference/height.csv
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/reference/psd.csv
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/reference/relative_pressure.csv
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/reference/voidage.csv
  examples/unresolved-cfd-dem/pseudo-2d-gas-solid-fluidized-bed/structure.geo
Labels: Reviewed and ready to merge, Example
