Repository chaos-polymtl/lethe, pull requests merged in 2025-02, with the labels that each got.

#1416 Implement vof algebraic interface reinitialization
  CHANGELOG.md
  doc/source/parameters/cfd/linear_solver_control.rst
  doc/source/parameters/cfd/non-linear_solver_control.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  include/core/parameters_multiphysics.h
  include/core/simulation_control.h
  include/core/utilities.h
  include/fem-dem/void_fraction.h
  include/solvers/physics_subequations_solver.h
  include/solvers/simulation_parameters.h
  include/solvers/vof.h
  include/solvers/vof_algebraic_interface_reinitialization.h
  include/solvers/vof_curvature_projection.h
  include/solvers/vof_linear_subequations_solver.h
  include/solvers/vof_phase_gradient_projection.h
  include/solvers/vof_subequations.h
  include/solvers/vof_subequations_interface.h
  source/core/parameters_multiphysics.cc
  source/core/utilities.cc
  source/fem-dem/void_fraction.cc
  source/solvers/CMakeLists.txt
  source/solvers/vof.cc
  source/solvers/vof_algebraic_interface_reinitialization.cc
  source/solvers/vof_assemblers.cc
  source/solvers/vof_curvature_projection.cc
  source/solvers/vof_linear_subequations_solver.cc
  source/solvers/vof_phase_gradient_projection.cc
  source/solvers/vof_subequations_interface.cc
  tests/solvers/vof_subequations_interface_01.cc
  tests/solvers/vof_subequations_interface_01.output
Labels: Enhancement, Ready for review

#1422 Update cylinder examples in DEM with experimental results and fix rotating walls
  CHANGELOG.md
  doc/source/examples/dem/rotating-drum/images/lethe-rotating-drum-comparison-depth.png
  doc/source/examples/dem/rotating-drum/images/lethe-rotating-drum-comparison-free-surface.png
  doc/source/examples/dem/rotating-drum/rotating-drum.rst
  doc/source/examples/dem/small-scale-rotating-drum/small-scale-rotating-drum.rst
  examples/dem/3d-rotating-drum/data_exp.csv
  examples/dem/3d-rotating-drum/depth_velocity.dat
  examples/dem/3d-rotating-drum/load-rotating-drum.prm
  examples/dem/3d-rotating-drum/post_processing_rotating_drum.py
  examples/dem/3d-rotating-drum/rotating-drum.prm
  examples/dem/3d-rotating-drum/validate.sh
  examples/dem/3d-small-scale-rotating-drum/small-rotating-drum-dem.prm
Labels: Ready for review, Example

#1423 fix algebraic reinitialization output issue
  CHANGELOG.md
  source/solvers/vof_algebraic_interface_reinitialization.cc
Labels: Quick fix

#1417 Dem epsd rolling friction model
  CHANGELOG.md
  applications_tests/lethe-particles/epsd_rolling_resistance_model.output
  applications_tests/lethe-particles/epsd_rolling_resistance_model.prm
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  doc/source/parameters/dem/model_parameters.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  include/core/parameters_lagrangian.h
  include/dem/contact_info.h
  include/dem/force_chains_visualization.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_wall_contact_force.h
  include/dem/particle_wall_dmt_force.h
  include/dem/particle_wall_jkr_force.h
  include/dem/particle_wall_linear_force.h
  include/dem/particle_wall_nonlinear_force.h
  include/dem/rolling_resistance_torque_models.h
  source/core/parameters_lagrangian.cc
  source/dem/force_chains_visualization.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_particle_fine_search.cc
  source/dem/particle_wall_dmt_force.cc
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/dem/set_particle_particle_contact_force_model.cc
  source/dem/update_local_particle_containers.cc
  tests/dem/normal_force.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
  tests/dem/post_collision_velocity.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Enhancement, Documentation, Reviewed and ready to merge

#1425 Dem fix segfault solid surfaces
  CHANGELOG.md
  include/dem/insertion.h
  include/fem-dem/ib_particles_dem.h
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/fem-dem/ib_particles_dem.cc
Labels: Bug, Ready for review, CI

#1418 Prototype reinitialization vof
  CHANGELOG.md
  prototypes/CMakeLists.txt
  prototypes/vof_advection/CMakeLists.txt
  prototypes/vof_advection/parameters.prm
  prototypes/vof_advection/vof_advection.cc
Labels: Reviewed and ready to merge, Rebased

#1426 Cooling fin example
  CHANGELOG.md
  doc/source/examples/multiphysics/cooling-fin/cooling-fin.rst
  doc/source/examples/multiphysics/cooling-fin/images/generate_schematic.tex
  doc/source/examples/multiphysics/cooling-fin/images/regenerate_schematic.sh
  doc/source/examples/multiphysics/cooling-fin/images/schematic.svg
  doc/source/examples/multiphysics/cooling-fin/images/temperature_fin.png
  doc/source/examples/multiphysics/heat-transfer.rst
  doc/source/examples/multiphysics/multiphysics.rst
  examples/multiphysics/cooling_fin/compare_solution.py
  examples/multiphysics/cooling_fin/fin.prm
Labels: Ready for review, Example

#1421 Add laser angle
  CHANGELOG.md
  applications_tests/lethe-fluid/CMakeLists.txt
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_rotated_laser.output
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_rotated_laser.prm
  applications_tests/lethe-fluid/lpbf_benchmark_mesh_3D.msh
  doc/source/parameters/cfd/laser_heat_source.rst
  include/core/lethe_grid_tools.h
  include/core/parameters.h
  source/core/lethe_grid_tools.cc
  source/core/parameters.cc
  source/solvers/heat_transfer_assemblers.cc
  tests/core/lethe_grid_tools_point_line_distance.cc
  tests/core/lethe_grid_tools_point_line_distance.output
Labels: Enhancement, Rebased

#1411 Added homogeneous and heterogeneous first order reactions for tracer
  CHANGELOG.md
  applications_tests/lethe-fluid-sharp/mms_tracer_reaction_heterogeneous.output
  applications_tests/lethe-fluid-sharp/mms_tracer_reaction_heterogeneous.prm
  applications_tests/lethe-fluid/mms_tracer_reaction_homogeneous.output
  applications_tests/lethe-fluid/mms_tracer_reaction_homogeneous.prm
  applications_tests/lethe-fluid/mms_tracer_reaction_homogeneous_dg.output
  applications_tests/lethe-fluid/mms_tracer_reaction_homogeneous_dg.prm
  doc/source/parameters/cfd/multiphysics.rst
  doc/source/parameters/cfd/physical_properties.rst
  include/core/ib_particle.h
  include/core/parameters.h
  include/core/physical_property_model.h
  include/core/shape.h
  include/core/tracer_diffusivity_model.h
  include/core/tracer_reaction_model.h
  include/fem-dem/fluid_dynamics_sharp.h
  include/solvers/physical_properties_manager.h
  include/solvers/postprocessors.h
  include/solvers/tracer_assemblers.h
  include/solvers/tracer_scratch_data.h
  source/core/CMakeLists.txt
  source/core/parameters.cc
  source/core/parameters_multiphysics.cc
  source/core/shape.cc
  source/core/tracer_reaction_model.cc
  source/solvers/physical_properties_manager.cc
  source/solvers/tracer.cc
  source/solvers/tracer_assemblers.cc
  source/solvers/tracer_scratch_data.cc
Labels: Enhancement, Reviewed and ready to merge

#1430 Add change to changelog
  CHANGELOG.md
  source/core/dem_properties.cc
Labels: Bug, Quick fix, Ready for review
