Repository chaos-polymtl/lethe, pull requests merged in 2025-04, with the labels that each got.

#1462 Add mortar classes
  CHANGELOG.md
  include/core/mortar_coupling_manager.h
  tests/CMakeLists.txt
  tests/mortar/CMakeLists.txt
  tests/mortar/data_exchange_01.cc
  tests/mortar/data_exchange_01.mpirun=3.output
  tests/mortar/data_exchange_02.cc
  tests/mortar/data_exchange_02.mpirun=1.output
  tests/mortar/data_exchange_02.mpirun=3.output
  tests/mortar/manager_01.cc
  tests/mortar/manager_01.output
  tests/mortar/manager_02.cc
  tests/mortar/manager_02.output
  tests/mortar/multigrid_01.cc
  tests/mortar/multigrid_01.mpirun=1.output
  tests/mortar/multigrid_01.mpirun=3.output
  tests/mortar/plot_01.cc
  tests/mortar/plot_01.mpirun=3.output
  tests/mortar/poisson_01.cc
  tests/mortar/poisson_01.mpirun=1.output
  tests/mortar/poisson_01.mpirun=3.output
  tests/mortar/poisson_02.cc
  tests/mortar/poisson_02.mpirun=1.output
  tests/mortar/poisson_02.mpirun=3.output
  tests/mortar/poisson_03.cc
  tests/mortar/poisson_03.mpirun=1.output
  tests/mortar/poisson_03.mpirun=3.output
  tests/mortar/poisson_04.cc
  tests/mortar/poisson_04.mpirun=1.output
  tests/mortar/poisson_04.mpirun=3.output
  tests/mortar/projection_matrix_01.cc
  tests/mortar/projection_matrix_01.output
  tests/mortar/rad_01.cc
  tests/mortar/rad_01.output
  tests/mortar/stokes_01.cc
  tests/mortar/stokes_01.mpirun=1.output
  tests/mortar/stokes_01.mpirun=3.output
  tests/mortar/tests.h
Labels: Reviewed and ready to merge

#1480 Change Triangulation input in attach_grid_to_triangulation
  include/core/grids.h
  source/core/grids.cc
Labels: Reviewed and ready to merge, Refactoring

#1477 VTU slicing pre-processing script
  contrib/postprocessing/extract-from-vtu/extract-particles-properties-from-vtu.py
  contrib/postprocessing/extract-from-vtu/extract-slice-from-vtu.py
Labels: Ready for review, Post-processing

#1483 DEM default parameters for tests
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/test_particles_functions.h
Labels: Beginner's work, Ready for review

#1482 Move point to rad functions
  include/core/mortar_coupling_manager.h
  include/core/utilities.h
Labels: Quick fix, Ready for review

#1481 Read and merge meshes in mortar control
  doc/source/parameters/cfd/cfd.rst
  doc/source/parameters/cfd/mortar.rst
  include/core/grids.h
  include/core/parameters.h
  include/solvers/simulation_parameters.h
  source/core/grids.cc
  source/core/parameters.cc
  source/solvers/fluid_dynamics_matrix_based.cc
  tests/mortar/read_mortar_data_01.cc
  tests/mortar/read_mortar_data_01.output
  tests/mortar/read_mortar_data_02.cc
  tests/mortar/read_mortar_data_02.output
Labels: Enhancement, Ready for review

#1486 Fix missing header
  include/core/utilities.h
  prototypes/modified_zonal_approach/modified_zonal_approach.cc
  source/dem/output_force_torque_calculation.cc
Labels: Bug, Reviewed and ready to merge

#1478 Particle particle heat transfer
  include/dem/particle_particle_heat_transfer.h
  source/dem/CMakeLists.txt
  source/dem/particle_particle_heat_transfer.cc
  tests/dem/particle_particle_thermal_resistances.cc
  tests/dem/particle_particle_thermal_resistances.output
Labels: Ready for review

#1485 Fix the plot in the rotating drum and refactor
  contrib/validation/validation_functions.sh
  examples/dem/3d-rectangular-hopper/validate.sh
  examples/dem/3d-rotating-drum/post_processing_rotating_drum.py
  examples/dem/3d-rotating-drum/validate.sh
  examples/incompressible-flow/2d-lid-driven-cavity/validate.sh
  examples/incompressible-flow/2d-taylor-couette/validate.sh
  examples/incompressible-flow/3d-taylor-green-vortex/validate.sh
  examples/multiphysics/rising-bubble/validate.sh
Labels: Ready for review

#1487 Dem fix
  contrib/validation/validate_lethe.sh
  doc/source/examples/dem/rectangular-hopper/rectangular-hopper.rst
  doc/source/examples/multiphysics/multiphysics.rst
  examples/dem/3d-rectangular-hopper/hopper_periodic.prm
  examples/dem/3d-rectangular-hopper/hopper_structured.geo
  examples/dem/3d-rectangular-hopper/hopper_structured_periodic.geo
  examples/dem/3d-rectangular-hopper/validate.sh
Labels: Bug, Documentation, Reviewed and ready to merge, Quick fix

#1489 Add particle heat transfer calculation in force calculation
  include/dem/multiphysics_integrator.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_particle_heat_transfer.h
  source/dem/multiphysics_integrator.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_particle_heat_transfer.cc
  tests/dem/integration_temperature.cc
  tests/dem/particle_particle_heat_transfer.cc
  tests/dem/particle_particle_heat_transfer.output
  tests/dem/particle_particle_thermal_resistances.cc
Labels: Ready for review

#1495 Fix level set output when geometry is moving
  CHANGELOG.md
  source/fem-dem/fluid_dynamics_sharp.cc
Labels: Bug, Reviewed and ready to merge, Quick fix

#1492 DEM tangential displacement
  CHANGELOG.md
  doc/source/theory/multiphase/cfd_dem/dem.rst
  include/dem/contact_info.h
  include/dem/dem_action_manager.h
  include/dem/force_chains_visualization.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_particle_fine_search.h
  include/fem-dem/ib_particles_dem.h
  source/dem/particle_wall_contact_force.cc
  source/dem/particle_wall_dmt_force.cc
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/dem/update_local_particle_containers.cc
  source/fem-dem/ib_particles_dem.cc
  tests/dem/full_contact_functions.h
  tests/dem/normal_force.cc
  tests/dem/particle_particle_fine_search.cc
  tests/dem/particle_particle_fine_search.output
Labels: Reviewed and ready to merge

#1496 Fix rayleigh benard example
  CHANGELOG.md
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra1M.prm
Labels: Reviewed and ready to merge, Quick fix, Example

#1501 Update turbulent Taylor-Couette example
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/3d-turbulent-taylor-couette.rst
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_655k_Q3.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q2.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_82k_Q3.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_Q2Q2_153k.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_Q2Q2_942k.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_Q3Q3_153k.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/enstrophy_comparison_Q3Q3_942k.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/mesh.png
  doc/source/examples/incompressible-flow/3d-turbulent-taylor-couette/images/mesh_153kcells.png
  examples/incompressible-flow/3d-turbulent-taylor-couette/tc-matrix-free.prm
Labels: Documentation, Ready for review

#1502 Update initlog
  tests/dem/particle_particle_contact_on_two_processors.mpirun=2.output
  tests/tests.h
Labels: Quick fix, Ready for review

#1490 Mortar update merged triangulation data
  CHANGELOG.md
  doc/source/parameters/cfd/mortar.rst
  include/core/grids.h
  include/core/mortar_coupling_manager.h
  include/core/utilities.h
  source/core/grids.cc
  tests/mortar/manager_02.cc
  tests/mortar/manager_02.output
  tests/mortar/read_mortar_data_01.cc
  tests/mortar/read_mortar_data_01.mpirun=3.output
  tests/mortar/read_mortar_data_01.output
  tests/mortar/read_mortar_data_02.cc
  tests/mortar/read_mortar_data_02.mpirun=3.output
  tests/mortar/read_mortar_data_02.output
Labels: Refactoring, Ready to merge after CHANGELOG/Rebase

#1504 Refactor call to force calculation function
  CHANGELOG.md
  include/dem/dem.h
  include/dem/particle_interaction_outcomes.h
  include/dem/particle_particle_contact_force.h
  include/fem-dem/cfd_dem_coupling.h
  source/dem/dem.cc
  source/dem/particle_particle_contact_force.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/full_contact_functions.h
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_particle_heat_transfer.cc
  tests/dem/particle_particle_thermal_resistances.cc
  tests/dem/test_particles_functions.h
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Reviewed and ready to merge

#1509 Remove invalid comment on boundary conditions
  doc/source/parameters/cfd/boundary_conditions_cfd.rst
Labels: Documentation, Reviewed and ready to merge

#1511 Add find-line-sphere-intersection
  CHANGELOG.md
  include/core/lethe_grid_tools.h
  source/core/lethe_grid_tools.cc
Labels: Ready for review, Utilities, Hackathon

#1512 Add template to the find_cell_neighbors function
  CHANGELOG.md
  include/dem/find_cell_neighbors.h
  source/dem/find_cell_neighbors.cc
  tests/dem/find_cell_neighbors.cc
  tests/dem/find_cell_neighbors.output
Labels: Reviewed and ready to merge, Quick fix, Hackathon
