Repository chaos-polymtl/lethe, pull requests merged in 2025-01, with the labels that each got.

#1398 Add two publications to documentation
  doc/source/publications.rst
Labels: Documentation

#1403 Resolves Rayleigh-Bénard Convection issue #1356
  doc/source/examples/multiphysics/rayleigh-benard-convection/images/geometry.png
  doc/source/examples/multiphysics/rayleigh-benard-convection/images/schematic_rayleigh-benard.svg
  doc/source/examples/multiphysics/rayleigh-benard-convection/images/solution-rayleigh-uy.png
  doc/source/examples/multiphysics/rayleigh-benard-convection/images/solution-rayleigh-xv.png
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra1M.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.py
Labels: Ready for review, Example

#1408 Parameter void fraction smoothing length redefinition
  CHANGELOG.md
  applications_tests/lethe-fluid-particles/adaptive_sparse_contacts.prm
  applications_tests/lethe-fluid-particles/dynamic_contact_search.prm
  applications_tests/lethe-fluid-particles/generators/gas_solid_fluidized_bed_generator_step_2_cfd-dem.prm
  applications_tests/lethe-fluid-particles/generators/restart_particle_sedimentation_generator.prm
  applications_tests/lethe-fluid-particles/liquid_fluidized_bed.prm
  applications_tests/lethe-fluid-particles/particle_sedimentation.prm
  applications_tests/lethe-fluid-particles/periodic_particles_qcm.prm
  applications_tests/lethe-fluid-particles/periodic_particles_qcm_opposite_flow.prm
  applications_tests/lethe-fluid-particles/restart_gas_solid_fluidized_bed.prm
  applications_tests/lethe-fluid-particles/restart_particle_sedimentation.prm
  applications_tests/lethe-fluid-vans/beetstra_packed_bed.prm
  applications_tests/lethe-fluid-vans/dallavalle_packed_bed.prm
  applications_tests/lethe-fluid-vans/difelice_packed_bed.prm
  applications_tests/lethe-fluid-vans/gidaspow_packed_bed.prm
  applications_tests/lethe-fluid-vans/kochhill_packed_bed.prm
  applications_tests/lethe-fluid-vans/pcm_packed_bed.prm
  applications_tests/lethe-fluid-vans/qcm_packed_bed.prm
  applications_tests/lethe-fluid-vans/rong_packed_bed.prm
  applications_tests/lethe-fluid-vans/spm_packed_bed.prm
  doc/source/examples/unresolved-cfd-dem/cylindrical-packed-bed/cylindrical-packed-bed.rst
  doc/source/examples/unresolved-cfd-dem/dense-pneumatic-conveying/dense-pneumatic-conveying.rst
  doc/source/examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.rst
  doc/source/examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.rst
  doc/source/parameters/unresolved-cfd-dem/void-fraction.rst
  examples/unresolved-cfd-dem/cylindrical-packed-bed/flow-in-bed.prm
  examples/unresolved-cfd-dem/dense-pneumatic-conveying/pneumatic-conveying.prm
  examples/unresolved-cfd-dem/gas-solid-fluidized-bed/gas-solid-fluidized-bed.prm
  examples/unresolved-cfd-dem/liquid-solid-fluidized-bed/liquid-solid-fluidized-bed.prm
  include/fem-dem/parameters_cfd_dem.h
  include/fem-dem/void_fraction.h
  source/fem-dem/parameters_cfd_dem.cc
  source/fem-dem/void_fraction.cc
Labels: Reviewed and ready to merge, Rebased

#1409 Update deal.II version in the installation instruction to 9.6
  CHANGELOG.md
  doc/source/installation/regular_installation.rst
  doc/source/installation/windows_wsl.rst
Labels: Documentation

#1410 Update clang tidy CI
  .github/workflows/clang-tidy.yml
  CHANGELOG.md
Labels: Refactoring

#1414 Update mac instructions and add comments about troubleshooting
  doc/source/installation/apple_arm.rst
Labels: Documentation, Ready for review

#1413 Rotating drum validation test
  CHANGELOG.md
  contrib/validation/validation_cases.txt
  examples/dem/3d-rotating-drum/post_processing_rotating_drum.py
  examples/dem/3d-rotating-drum/rotating-drum.prm
  examples/dem/3d-rotating-drum/validate.sh
Labels: Enhancement, Maintenance, Ready for review
