Repository chaos-polymtl/lethe, pull requests merged in 2025-03, with the labels that each got.

#1436 Fix velocity average solution transfer adapt grid
  CHANGELOG.md
  source/solvers/navier_stokes_base.cc
  source/solvers/postprocessing_velocities.cc
Labels: Bug

#1437 Removed the useless parameter in the serialize and deserialize functions
  include/dem/insertion.h
  include/dem/insertion_file.h
  include/dem/insertion_list.h
  include/dem/insertion_plane.h
  include/dem/insertion_volume.h
  source/dem/read_checkpoint.cc
  source/dem/write_checkpoint.cc
Labels: Maintenance, Quick fix, Ready for review

#1441 Fix typo in documentation for DEM parameters
  doc/source/parameters/dem/model_parameters.rst
Labels: Documentation

#1429 Add interface reconstruction utilities
  CHANGELOG.md
  include/core/interface_tools.h
  include/solvers/vof.h
  source/core/CMakeLists.txt
  source/core/interface_tools.cc
  tests/core/CMakeLists.txt
  tests/core/interface_tools_sphere_reconstruction.cc
  tests/core/interface_tools_sphere_reconstruction.output
  tests/core/interface_tools_sphere_volume.cc
  tests/core/interface_tools_sphere_volume.output
Labels: Ready for review, Rebased, Utilities

#1443 Fix velocity subsection in ale parameters doc
  doc/source/parameters/cfd/ale.rst
Labels: Documentation, Reviewed and ready to merge, Rebased

#1442 Fix mesh adaptation controller parameter in doc
  doc/source/parameters/cfd/mesh_adaptation_control.rst
Labels: Documentation, Reviewed and ready to merge

#1444 Fix typo in the theory doc
  doc/source/theory/multiphase/cfd_dem/dem.rst
Labels: Beginner's work, Quick fix, Ready for review

#1433 DEM Example 2D Sandpile
  doc/source/examples/dem/dem.rst
  doc/source/examples/dem/sandpile-formation/images/figure-height-comparison.png
  doc/source/examples/dem/sandpile-formation/images/figure-height-different-prn-seeds.png
  doc/source/examples/dem/sandpile-formation/images/formed-sandpile.png
  doc/source/examples/dem/sandpile-formation/images/mesh-sandpile.png
  doc/source/examples/dem/sandpile-formation/sandpile-formation.rst
  examples/dem/2d-sandpile-formation/data/reference/extraction_model_constant.csv
  examples/dem/2d-sandpile-formation/data/reference/extraction_model_epsd.csv
  examples/dem/2d-sandpile-formation/data/reference/extraction_model_viscous.csv
  examples/dem/2d-sandpile-formation/sandpile-constant.prm
  examples/dem/2d-sandpile-formation/sandpile-epsd.prm
  examples/dem/2d-sandpile-formation/sandpile-height-comparison.py
  examples/dem/2d-sandpile-formation/sandpile-postprocessing.py
  examples/dem/2d-sandpile-formation/sandpile-viscous.prm
  examples/dem/2d-sandpile-formation/sandpile.geo
Labels: Ready for review, Example

#1447 DEM tests particle_particle_contact_force linear and nonlinear cleanup
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/test_particles_functions.h
Labels: Beginner's work, Ready for review

#1452 Remove muparser
  CHANGELOG.md
  doc/source/installation/apple_arm.rst
  doc/source/installation/digital_alliance.rst
  doc/source/installation/regular_installation.rst
  doc/source/installation/windows_wsl.rst
  include/core/mu_parser_internal.h
  include/core/parsed_function_custom.h
  source/core/CMakeLists.txt
  source/core/mu_parser_internal.cc
  source/core/parsed_function_custom.cc
  tests/core/custom_parsed_functions.cc
  tests/core/custom_parsed_functions.output
Labels: Maintenance, Ready for review

#1451 Vof geometric reinitialization architecture
  CHANGELOG.md
  include/core/interface_tools.h
  include/core/parameters_multiphysics.h
  include/solvers/vof.h
  source/core/interface_tools.cc
  source/core/parameters_multiphysics.cc
  source/solvers/vof.cc
  tests/core/interface_tools_signed_distance.cc
  tests/core/interface_tools_signed_distance.output
Labels: Reviewed and ready to merge, Ready for review

#1453 Dem test and function full contact
  tests/dem/full_contact_functions.h
  tests/dem/particle_particle_full_contact.cc
  tests/dem/particle_particle_full_contact.output
Labels: Reviewed and ready to merge

#1457 Core library cleanup
  include/core/bdf.h
  include/core/boundary_conditions.h
  include/core/dem_properties.h
  include/core/density_model.h
  include/core/grids.h
  source/core/bdf.cc
  source/core/boundary_conditions.cc
  source/core/dem_properties.cc
  source/core/density_model.cc
  source/core/grids.cc
  source/dem/dem.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/fluid_dynamics_vans.cc
  source/fem-dem/fluid_dynamics_vans_matrix_free.cc
  tests/dem/distribution_normal.cc
  tests/dem/insertion_plane.cc
  tests/dem/insertion_volume_1.cc
  tests/dem/insertion_volume_2.cc
  tests/dem/integration_euler.cc
  tests/dem/integration_schemes_accuracy.cc
  tests/dem/integration_velocity_verlet.cc
  tests/dem/normal_force.cc
  tests/dem/particle_handler_conversion_1.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_contact_on_two_processors.cc
  tests/dem/particle_particle_fine_search.cc
  tests/dem/particle_point_contact.cc
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
  tests/dem/particle_wall_fine_search.cc
  tests/dem/post_collision_velocity.cc
  tests/dem/two_particles_multiple_contacts_parallel.cc
Labels: Reviewed and ready to merge, Refactoring

#1455 Example 2D Sudden Expansion Flow
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/2d-sudden-expansion-flow.rst
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds610-5.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds610-6.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds610-7.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds610-poiseuille.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds70-0.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds70-1.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds70-2.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds70-3.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/Reynolds70-poiseuille.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/expansion-geometry.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/mesh-adaptation-Re70.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/streamlines-Re610.png
  doc/source/examples/incompressible-flow/2d-sudden-expansion-flow/image/streamlines-Re70.png
  doc/source/examples/incompressible-flow/incompressible-flow.rst
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-10mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-140mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-200mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-290mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-35mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-440mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-50mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610-600mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-10mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-140mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-200mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-290mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-35mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-440mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-50mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reference-Data/Durst-Re610exp-600mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds610/Reynolds610-jet.prm
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70-10mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70-140mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70-35mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70-50mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70exp-10mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70exp-140mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70exp-35mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Durst-Re70exp-50mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Kanna-Re70-140mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Kanna-Re70-35mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reference-Data/Kanna-Re70-50mm.txt
  examples/incompressible-flow/2d-sudden-expansion-flow/Reynolds70/Reynolds70-jet.prm
  examples/incompressible-flow/2d-sudden-expansion-flow/two-dimensional-jet.geo
  examples/incompressible-flow/2d-sudden-expansion-flow/velocity_profiles.py
Labels: Reviewed and ready to merge, Example

#1459 Add algebraic reinitialisation to theory guide
  doc/source/parameters/cfd/volume_of_fluid.rst
  doc/source/theory/multiphase/cfd/vof.rst
Labels: Documentation, Reviewed and ready to merge, Rebased

#1463 Throw exception for non-Newtonian fluid in MF solver
  CHANGELOG.md
  source/solvers/fluid_dynamics_matrix_free.cc
Labels: Reviewed and ready to merge, Quick fix

#1456 Periodic boundary conditions for auxiliary physics
  CHANGELOG.md
  applications_tests/lethe-fluid/cahn_hilliard_periodic_boundaries.output
  applications_tests/lethe-fluid/cahn_hilliard_periodic_boundaries.prm
  applications_tests/lethe-fluid/gls_vof_periodic_boundary_condition.prm
  applications_tests/lethe-fluid/heat_transfer_periodic_boundaries.output
  applications_tests/lethe-fluid/heat_transfer_periodic_boundaries.prm
  applications_tests/lethe-fluid/tracer_periodic_boundaries.output
  applications_tests/lethe-fluid/tracer_periodic_boundaries.prm
  applications_tests/lethe-fluid/vof-velocity-extrapolation.prm
  doc/source/examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-instability.rst
  doc/source/parameters/cfd/boundary_conditions_multiphysics.rst
  examples/multiphysics/capillary-wave/capillary-wave-postprocess.py
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10_delta0_20/rayleigh-plateau-J1-We020-Oh0_10_delta0_20.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor_postprocess.py
  examples/multiphysics/sloshing-in-rectangular-tank/sloshing_postprocessing.py
  include/core/boundary_conditions.h
  source/solvers/cahn_hilliard.cc
  source/solvers/heat_transfer.cc
  source/solvers/tracer.cc
  source/solvers/tracer_assemblers.cc
  source/solvers/vof.cc
  source/solvers/vof_linear_subequations_solver.cc
Labels: Enhancement, Reviewed and ready to merge

#1468 Fix compilation of Kokkos prototypes
  prototypes/kokkos_poisson/kokkos_poisson.cc
  prototypes/kokkos_stokes/kokkos_stokes.cc
Labels: Ready for review

#1460 Add parameters for thermal DEM
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  include/core/dem_properties.h
  include/core/parameters_lagrangian.h
  source/core/dem_properties.cc
  source/core/parameters_lagrangian.cc
Labels: Reviewed and ready to merge

#1469 Add template instantiations for DEMMPProperties
  CHANGELOG.md
  source/core/lethe_grid_tools.cc
  source/dem/adaptive_sparse_contacts.cc
  source/dem/dem.cc
  source/dem/dem_contact_manager.cc
  source/dem/dem_post_processing.cc
  source/dem/explicit_euler_integrator.cc
  source/dem/find_contact_detection_step.cc
  source/dem/force_chains_visualization.cc
  source/dem/integrator.cc
  source/dem/lagrangian_post_processing.cc
  source/dem/load_balancing.cc
  source/dem/particle_particle_broad_search.cc
  source/dem/particle_particle_contact_force.cc
  source/dem/particle_point_line_broad_search.cc
  source/dem/particle_point_line_contact_force.cc
  source/dem/particle_point_line_fine_search.cc
  source/dem/particle_wall_broad_search.cc
  source/dem/particle_wall_contact_force.cc
  source/dem/particle_wall_dmt_force.cc
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/dem/set_particle_particle_contact_force_model.cc
  source/dem/set_particle_wall_contact_force_model.cc
  source/dem/velocity_verlet_integrator.cc
  source/dem/visualization.cc
Labels: Reviewed and ready to merge

#1471 Add feature for last output and fix example results
  CHANGELOG.md
  doc/source/examples/multiphysics/rising-bubble/images/bubble-contour.png
  doc/source/examples/multiphysics/rising-bubble/images/bubble-rise-velocity.png
  doc/source/examples/multiphysics/rising-bubble/images/ymean-t.png
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/parameters/cfd/simulation_control.rst
  examples/multiphysics/rising-bubble/rising-bubble.prm
  source/core/simulation_control.cc
  tests/core/simulation_control_03.output
Labels: Reviewed and ready to merge, Quick fix, Example

#1467 Vof change sharpening and reinitialization parameters
  CHANGELOG.md
  applications_tests/lethe-fluid/generators/heat_transfer_vof_lpbf_benchmark_box_ref_generator.prm
  applications_tests/lethe-fluid/generators/heat_transfer_vof_lpbf_benchmark_generator.prm
  applications_tests/lethe-fluid/gls_vof_ht_heated-walls.prm
  applications_tests/lethe-fluid/gls_vof_ht_heated-walls_heat-flux.prm
  applications_tests/lethe-fluid/gls_vof_ht_heated-walls_multivar_adapt.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark.prm
  applications_tests/lethe-fluid/heat_transfer_vof_lpbf_benchmark_box_ref.prm
  applications_tests/lethe-fluid/interface_sharpening_blurred_circle.prm
  applications_tests/lethe-fluid/interface_sharpening_blurred_circle_adaptive_mass_conservation.prm
  doc/source/examples/multiphysics/air-bubble-compression/air-bubble-compression.rst
  doc/source/examples/multiphysics/dam-break/dam-break.rst
  doc/source/examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability.rst
  doc/source/examples/multiphysics/rising-bubble/rising-bubble.rst
  doc/source/examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.rst
  doc/source/parameters/cfd/volume_of_fluid.rst
  doc/source/theory/multiphase/cfd/vof.rst
  examples/multiphysics/air-bubble-compression/air-bubble-compression.prm
  examples/multiphysics/dam-break/dam-break-Martin-and-Moyce.prm
  examples/multiphysics/rayleigh-plateau-instability/3D-delta0_30/rayleigh-plateau-J1-3D.prm
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10.tpl
  examples/multiphysics/rayleigh-plateau-instability/rayleigh-plateau-J1-We020-Oh0_10_delta0_20/rayleigh-plateau-J1-We020-Oh0_10_delta0_20.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-adaptive-sharpening.prm
  examples/multiphysics/rayleigh-taylor-instability/rayleigh-taylor-instability-constant-sharpening.prm
  examples/multiphysics/rising-bubble/rising-bubble.prm
  examples/multiphysics/static-irradiation/2D/static-irradiation.prm
  examples/multiphysics/thermocapillary-droplet/thermocapillary-droplet.prm
  examples/multiphysics/water-injection-in-a-closed-cell/water-injection-in-a-closed-cell.prm
  include/core/parameters_multiphysics.h
  include/solvers/vof.h
  include/solvers/vof_algebraic_interface_reinitialization.h
  include/solvers/vof_curvature_projection.h
  include/solvers/vof_phase_gradient_projection.h
  source/core/parameters_multiphysics.cc
  source/solvers/multiphysics_interface.cc
  source/solvers/vof.cc
  source/solvers/vof_algebraic_interface_reinitialization.cc
  source/solvers/vof_subequations_interface.cc
  tests/solvers/vof_subequations_interface_01.cc
Labels: Refactoring, Ready to merge after final OK

#1473 Thermal DEM temperature integration
  include/dem/multiphysics_integrator.h
  source/dem/CMakeLists.txt
  source/dem/multiphysics_integrator.cc
  tests/dem/integration_temperature.cc
  tests/dem/integration_temperature.output
Labels: Reviewed and ready to merge

#1474 Apply filter before starting reinitialization process
  CHANGELOG.md
  applications_tests/lethe-fluid/vof-algebraic-interface-reinitialization-advected-circle.output
  applications_tests/lethe-fluid/vof-algebraic-interface-reinitialization-advected-circle.prm
  source/solvers/vof.cc
Labels: Reviewed and ready to merge, Quick fix, Ready for review

#1476 Add gravity term in coupling of NS and HT in doc
  doc/source/examples/multiphysics/melting-cavity/melting-cavity.rst
  doc/source/examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection.rst
Labels: Documentation, Quick fix, Ready for review

#1446 Dem variable cell weight for load balancing
  CHANGELOG.md
  applications_tests/lethe-particles/CMakeLists.txt
  applications_tests/lethe-particles/restart_cell_weight_function.prm
  applications_tests/lethe-particles/restart_cell_weight_function.with_dealii.geq.9.7.mpirun=2.output
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function.checkpoint_controller
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.insertion_object
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.particles
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.pvdhandler
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.simulationcontrol
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.triangulation
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.triangulation.info
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.triangulation_fixed.data
  applications_tests/lethe-particles/restart_cell_weight_function_files/restart_cell_weight_function_1.triangulation_variable.data
  applications_tests/lethe-particles/restart_generators/restart_cell_weight_function_generator.prm
  doc/source/parameters/dem/model_parameters.rst
  include/core/parameters_lagrangian.h
  include/dem/dem_solver_parameters.h
  include/dem/load_balancing.h
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/load_balancing.cc
  source/dem/set_particle_wall_contact_force_model.cc
  source/fem-dem/cfd_dem_coupling.cc
  tests/dem/particle_particle_contact_force_linear.cc
  tests/dem/particle_particle_contact_force_nonlinear.cc
  tests/dem/particle_particle_full_contact.cc
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
Labels: Enhancement, Good first issue, Reviewed and ready to merge
