Repository chaos-polymtl/lethe, pull requests merged in 2025-06, with the labels that each got.

#1542 Add particle-wall heat transfer 3/3
  CHANGELOG.md
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  doc/source/parameters/dem/model_parameters.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  include/core/parameters_lagrangian.h
  include/dem/dem.h
  include/dem/particle_particle_contact_force.h
  include/dem/particle_wall_contact_force.h
  source/core/parameters_lagrangian.cc
  source/dem/dem.cc
  source/dem/particle_wall_contact_force.cc
  tests/dem/particle_particle_heat_transfer.cc
  tests/dem/test_particles_functions.h
Labels: Ready for review

#1549 Mortar: nonlinear Poisson tests
  doc/source/parameters/cfd/mortar.rst
  include/core/mortar_coupling_manager.h
  include/core/parameters.h
  include/solvers/fluid_dynamics_matrix_based.h
  source/core/grids.cc
  source/core/mortar_coupling_manager.cc
  source/core/parameters.cc
  source/solvers/navier_stokes_base.cc
  tests/mortar/poisson_matrix_based_nonlinear_01.cc
  tests/mortar/poisson_matrix_based_nonlinear_01.mpirun=3.output
  tests/mortar/poisson_matrix_based_nonlinear_01.output
  tests/mortar/poisson_matrix_based_nonlinear_02.cc
  tests/mortar/poisson_matrix_based_nonlinear_02.output
Labels: Enhancement, Ready for review

#1553 Sharp: added dynamic_flow_control function call
  CHANGELOG.md
  source/fem-dem/fluid_dynamics_sharp.cc
Labels: Bug, Reviewed and ready to merge

#1556 Add capability to calculate the void fraction from particles in the matrix-free VANS solver
  CHANGELOG.md
  applications_tests/lethe-fluid-vans-matrix-free/CMakeLists.txt
  applications_tests/lethe-fluid-vans-matrix-free/generators/packed_bed_generator.prm
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem.checkpoint_controller
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.insertion_object
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.particles
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.pvdhandler
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.simulationcontrol
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.triangulation
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.triangulation.info
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.triangulation_fixed.data
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_0.triangulation_variable.data
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.insertion_object
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.particles
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.pvdhandler
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.simulationcontrol
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.triangulation
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.triangulation.info
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.triangulation_fixed.data
  applications_tests/lethe-fluid-vans-matrix-free/packed_bed_files/dem_1.triangulation_variable.data
  applications_tests/lethe-fluid-vans-matrix-free/qcm_packed_bed_no_drag.output
  applications_tests/lethe-fluid-vans-matrix-free/qcm_packed_bed_no_drag.prm
  include/fem-dem/fluid_dynamics_vans_matrix_free.h
  source/fem-dem/fluid_dynamics_vans_matrix_free.cc
Labels: Reviewed and ready to merge, Reviewed and waiting for changes

#1559 Add get_mapping and rotate_mapping functions
  include/solvers/navier_stokes_base.h
  source/solvers/fluid_dynamics_matrix_based.cc
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/navier_stokes_base.cc
Labels: Ready for review, Refactoring

#1561 Multiphysic DEM - Heated Packed Bed example
  CHANGELOG.md
  doc/source/examples/dem-mp/dem-mp.rst
  doc/source/examples/dem-mp/heated-packed-bed/heated-packed-bed.rst
  doc/source/examples/dem-mp/heated-packed-bed/images/heated-steel-final.png
  doc/source/examples/dem-mp/heated-packed-bed/images/heated-steel-rake.png
  doc/source/examples/dem-mp/heated-packed-bed/images/heated-steel-side.png
  doc/source/examples/dem-mp/heated-packed-bed/images/heights.png
  doc/source/examples/dem-mp/heated-packed-bed/images/mean-temperatures-friction.png
  doc/source/examples/dem-mp/heated-packed-bed/images/mean-temperatures.png
  examples/dem-mp/3d-heated-packed-bed/bed-postprocessing.py
  examples/dem-mp/3d-heated-packed-bed/flip-packed-bed.prm
  examples/dem-mp/3d-heated-packed-bed/heat-packed-bed.prm
  examples/dem-mp/3d-heated-packed-bed/load-packed-bed.prm
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.040_error1.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.040_error2.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.040_experiment.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.040_rough.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.060_error1.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.060_error2.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.060_experiment.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.060_rough.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.073_error1.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.073_error2.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.073_experiment.csv
  examples/dem-mp/3d-heated-packed-bed/reference/steel_Beaulieu_0.073_rough.csv
  examples/dem-mp/3d-heated-packed-bed/square-rake.geo
  examples/dem-mp/3d-heated-packed-bed/square-side.geo
  examples/dem-mp/3d-heated-packed-bed/square-top.geo
  source/dem/particle_heat_transfer.cc
Labels: Reviewed and ready to merge, Example

#1565 Add save path for extracted slice
  contrib/postprocessing/extract-from-vtu/extract-slice-from-vtu.py
Labels: Ready for review, Post-processing
