Repository chaos-polymtl/lethe, pull requests merged in 2025-05, with the labels that each got.

#1517 PRM indent examples and tests
  applications_tests/lethe-fluid-vans-matrix-free/case2_vans_A.prm
  applications_tests/lethe-fluid/vof-geometric-interface-reinitialization-swirling-flow.prm
  applications_tests/lethe-particles/restart_generators/restart_cell_weight_function_generator.prm
  applications_tests/lethe-particles/single-time-step-list-insertion.prm
  examples/dem/3d-rectangular-hopper/hopper_periodic.prm
  examples/incompressible-flow/2d-mms/mms_quad/mms_2d_steady.prm
  examples/incompressible-flow/2d-mms/mms_simplex/mms_2d_steady.prm
  examples/multiphysics/rayleigh-benard-convection/rayleigh-benard-convection-Ra10k.prm
  examples/unresolved-cfd-dem/single-particle-sedimentation/initial-particles.prm
  examples/unresolved-cfd-dem/single-particle-sedimentation/single-particle-sedimentation.prm
Labels: Reviewed and ready to merge

#1510 Discontinuous Galerkin implementation for VOF
  CHANGELOG.md
  applications_tests/lethe-fluid/dg_vof_advection_tanh.output
  applications_tests/lethe-fluid/dg_vof_advection_tanh.prm
  examples/multiphysics/rising-bubble/rising-bubble.prm
  include/core/parameters.h
  include/solvers/physics_assemblers.h
  include/solvers/vof.h
  include/solvers/vof_assemblers.h
  include/solvers/vof_scratch_data.h
  source/core/parameters.cc
  source/solvers/vof.cc
  source/solvers/vof_assemblers.cc
Labels: Reviewed and ready to merge, Hackathon

#1508 Add Cuboid Sedimentation Example Present in Lethe Paper
  doc/source/examples/sharp-immersed-boundary/resolved-cfd-dem.rst
  doc/source/examples/sharp-immersed-boundary/sedimentation-1-cuboid/images/velocity-comparison.png
  doc/source/examples/sharp-immersed-boundary/sedimentation-1-cuboid/sedimentation-1-cuboid.rst
  examples/sharp-immersed-boundary/sedimentation-1-cuboid/S18.dat
  examples/sharp-immersed-boundary/sedimentation-1-cuboid/post-process-sedimentation-1-cuboid.py
  examples/sharp-immersed-boundary/sedimentation-1-cuboid/sedimentation-1-cuboid.prm
Labels: Example, Ready to merge after final OK

#1519 cuboid example YT embed link corrected
  doc/source/examples/sharp-immersed-boundary/sedimentation-1-cuboid/sedimentation-1-cuboid.rst
Labels: Ready for review, Example

#1522 Fix two warnings
  source/core/parameters.cc
  source/dem/insertion_volume.cc
Labels: Quick fix

#1525 Correct year in changelog entries
  CHANGELOG.md
Labels: Quick fix, Ready for review

#1505 Add conjugated heat transfer (CHT) example
  doc/source/examples/multiphysics/cylinder-cooling/cylinder-cooling.rst
  doc/source/examples/multiphysics/cylinder-cooling/images/geometry.png
  doc/source/examples/multiphysics/cylinder-cooling/images/results.png
  doc/source/examples/multiphysics/heat-transfer.rst
  examples/multiphysics/cylinder-cooling/cylinder-xi-0_01.prm
  examples/multiphysics/cylinder-cooling/cylinder-xi-1.prm
  examples/multiphysics/cylinder-cooling/cylinder-xi-100.prm
  examples/multiphysics/cylinder-cooling/cylinder.msh
  examples/multiphysics/cylinder-cooling/cylinder.pw
  examples/multiphysics/cylinder-cooling/plot-avg-temperature.py
  examples/multiphysics/cylinder-cooling/post-process-avg-temperature.py
Labels: Reviewed and waiting for changes, Example

#1524 Add buoyancy term to matrix-free operators and GMG
  CHANGELOG.md
  include/solvers/fluid_dynamics_matrix_free.h
  include/solvers/fluid_dynamics_matrix_free_operators.h
  include/solvers/navier_stokes_base.h
  source/solvers/fluid_dynamics_matrix_free.cc
  source/solvers/fluid_dynamics_matrix_free_operators.cc
Labels: Reviewed and ready to merge

#1529 Mortar: add in-code documentation
  include/core/mortar_coupling_manager.h
  source/core/mortar_coupling_manager.cc
Labels: Documentation, Quick fix, Ready for review

#1531 Add missing .dat file
  examples/dem/3d-rotating-drum/free_surface_velocity.dat
Labels: Quick fix

#1533 Update define_constraints Functions
  CHANGELOG.md
  source/solvers/navier_stokes_base.cc
  source/solvers/vof.cc
  source/solvers/vof_algebraic_interface_reinitialization.cc
Labels: Bug, Reviewed and ready to merge, Quick fix

#1520 Refactor particle-wall contacts
  CHANGELOG.md
  applications_tests/lethe-particles/force_boundary_box.output
  applications_tests/lethe-particles/force_boundary_box.prm
  applications_tests/lethe-particles/torque_boundary_box.output
  applications_tests/lethe-particles/torque_boundary_box.prm
  include/core/parameters_lagrangian.h
  include/dem/contact_info.h
  include/dem/dem.h
  include/dem/particle_wall_contact_force.h
  include/dem/particle_wall_dmt_force.h
  include/dem/particle_wall_jkr_force.h
  include/dem/particle_wall_linear_force.h
  include/dem/particle_wall_nonlinear_force.h
  include/dem/particle_wall_rolling_resistance_torque.h
  include/dem/set_particle_wall_contact_force_model.h
  include/fem-dem/cfd_dem_coupling.h
  source/dem/CMakeLists.txt
  source/dem/dem.cc
  source/dem/particle_wall_contact_force.cc
  source/dem/particle_wall_dmt_force.cc
  source/dem/particle_wall_fine_search.cc
  source/dem/particle_wall_jkr_force.cc
  source/dem/particle_wall_linear_force.cc
  source/dem/particle_wall_nonlinear_force.cc
  source/dem/set_particle_wall_contact_force_model.cc
  source/fem-dem/cfd_dem_coupling.cc
  source/fem-dem/ib_particles_dem.cc
  tests/dem/normal_force.cc
  tests/dem/normal_force.output
  tests/dem/particle_wall_contact_force_linear.cc
  tests/dem/particle_wall_contact_force_nonlinear.cc
  tests/dem/post_collision_velocity.cc
Labels: Reviewed and ready to merge, Refactoring

#1535 Add generate triangles flag when extracting slice from vtu
  contrib/postprocessing/extract-from-vtu/extract-slice-from-vtu.py
Labels: Quick fix

#1537 Mortar: add Poisson matrix-based test
  tests/mortar/poisson_matrix_based.cc
  tests/mortar/poisson_matrix_based.mpirun=3.output
  tests/mortar/poisson_matrix_based.output
Labels: Quick fix, Ready for review

#1532 Add thermal DEM documentation
  doc/source/parameters/dem/insertion_info.rst
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  doc/source/parameters/dem/model_parameters.rst
  doc/source/theory/multiphase/cfd_dem/dem.rst
  doc/source/theory/multiphase/cfd_dem/images/particle_particle_resistances.png
  doc/source/theory/multiphase/cfd_dem/images/particle_particle_resistances.svg
  doc/source/theory/multiphase/cfd_dem/images/particle_wall_resistances.png
  doc/source/theory/multiphase/cfd_dem/images/particle_wall_resistances.svg
Labels: Documentation, Ready for review

#1538 Add particle-wall heat transfer parameters
  doc/source/parameters/dem/lagrangian_physical_properties.rst
  doc/source/parameters/dem/solid_objects.rst
  include/core/parameters_lagrangian.h
  include/core/serial_solid.h
  include/core/solid_objects_parameters.h
  source/core/parameters_lagrangian.cc
  source/core/serial_solid.cc
  source/core/solid_objects_parameters.cc
  tests/dem/test_particles_functions.h
Labels: Reviewed and ready to merge

#1541 Fix mass conservation table output in VOF
  CHANGELOG.md
  source/solvers/vof.cc
Labels: Reviewed and ready to merge, Quick fix
